### ISSUE TITLE
Webdev serve runs build for all folders when no output dir is provided

### ISSUE THREAD

**Issue by missvalentinep** [dart-lang/webdev#1023]
I can't find a logical connection, why the lack of specified output directory makes the build run for everything. Could you please explain it, or is it a bug?

Example: 
1. I run my project as `pub run webdev serve web:8080 `
2. Here - https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/serve/dev_workflow.dart#L132 - you register a build target as 'web', which is correct.
3. But a couple of lines later - https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/serve/dev_workflow.dart#L146 - you register `''` as a build target, because no output directory was provided. Since that means, that the build should run for everything, it turns out that you are ignoring the previously defined target.
4. As a result, build runs for all folders, which is not an expected behaviour for me, at all.

**Comment by jakemac53** [comment]
I think we are expecting this whole condition to be skipped due to `configuration.outputInput` being `null`. If it is defaulting to the empty string instead then that is likely what is causing the problem.

**Comment by missvalentinep** [comment]
@jakemac53 but it's not null. 
If the value for the output flag was not provided, it [sets it ](https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/command/configuration.dart#L295) to default value, which is 'NONE'. And a couple of lines later, - [here](https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/command/configuration.dart#L303) - it sets configuration.outputInput to `''`

**Comment by jakemac53** [comment]
Yes this definitely sounds like a bug then.

cc @grouma can you take a look? I think [this if](https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/serve/dev_workflow.dart#L137) should be checking for `&& configuration.outputPath != null` and the nested if can be removed. But I am not totally confident that won't break something else.
