### ISSUE TITLE
[dwds] eval broken?

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/webdev#1060]
Neither hover or repl work for me in VSCode since I did a `flutter upgrade` this morning.

Via REPL, I see messages: `InternalError: frontend server failed to compile 'cards'`

fyi - @annagrin @grouma 

I upgraded to:
```
Flutter 1.20.0-1.0.pre.128 • channel master • https://github.com/flutter/flutter.git
Framework • revision fbdc79e448 (3 minutes ago) • 2020-06-19 14:48:57 -0700
Engine • revision f135581548
Tools • Dart 2.9.0 (build 2.9.0-17.0.dev 62cc07dbca)
```

**Comment by annagrin** [comment]
I was not able to repro - eval works for me if I upgrade master:

```
Flutter 1.20.0-1.0.pre.132 • channel master • git@github.com:annagrin/flutter.git
Framework • revision 5995661777 (29 minutes ago) • 2020-06-19 16:15:58 -0700
Engine • revision 676cd566f7
Tools • Dart 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)
```

I wonder if something changed in between our versions or if there is something on our machines that interferes. Would you be able so run it with verbose logs? It can be done by adding the following line in `settings.json`:

```
"dart.flutterAdditionalArgs": [ "-v", ],
```

**Comment by grouma** [comment]
I wasn't able to reproduce. Did your configurations get reset? Are you sure you are running with the frontend server enabled etc?

**Comment by vsmenon** [comment]
I bumped to the same as @annagrin 's above.  I can't repro any more either.  Eval and hover work for me now. If I hit again, I'll try `-v`.
