### ISSUE TITLE
"webdev serve example/" return 404 for *.dart.js

### ISSUE THREAD

**Issue by a14n** [dart-lang/webdev#1062]
With webdev 2.5.9 I see 404 response code for every `.dart.js` files. If I move the files in web/ folder the problem disappears.

**Comment by jakemac53** [comment]
I think maybe this is actually a shelf issue? Does it work if you do `webdev serve example` (without the trailing `/`)? There was a bug in the latest shelf release that broke for the trailing slash case.

**Comment by a14n** [comment]
Indeed it works without the trailing `/`. Thanks!
Feel free to close the issue if you think it's a shelf issue.

**Comment by jakemac53** [comment]
I think a pub upgrade may also fix it - or the fix should be released soon at least. I am going to close as I am pretty confident that was the problem.
