### ISSUE TITLE
snapshot error

### ISSUE THREAD

**Issue by J4ckTh3R1qp3r** [dart-lang/webdev#1068]
hi, i am making an angular dart website and cant figure out the problem with webdev serve/build commands. I had this error with master branch and made another from few days ago commit. the new commit worked fine and i just copied and pasted all the changes from broken master branch. but then i merged new working branch to master and it stopped working with the same error. If i switch to 2 days ago commit i can run webdev serve and if i switch to the latest commit then webdev refreshes and works fine until i stop it. After stop i run webdev serve and the same error appears. Sorry if I am not providing all necessary information, I am new to programming. Would appreciate any help! Here is the error:

paul@iMac-Paul quantumart_old % webdev serve
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
[SEVERE] This is likely caused by a misconfigured builder definition.
[SEVERE] ../../../../.pub-cache/hosted/pub.dartlang.org/test_core-0.3.7/lib/test_core.dart:69:5: Error: 'unawaited' is imported from both 'package:meta/meta.dart' and 'package:test_api/src/utils.dart'.    unawaited(Future.error('Dummy exception to set exit code.'));    ^^^^^^^^^
Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)
<asynchronous suspension>
#2      connectClient (package:webdev/src/daemon_client.dart:17:23)
#3      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:26:18)
#4      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:191:24)
#5      ServeCommand.run (package:webdev/src/command/serve_command.dart:101:27)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#7      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)

**Comment by jakemac53** [comment]
You will need to pin the `meta` package to version `1.1.8` (even if you don't directly depend on it today):

```dart
dependencies:
  meta: 1.1.8
```

The problem is that you are not on the latest version of `test`, because `angular` doesn't allow the latest `analyzer` (making some assumptions about your setup, but most likely this is the issue).
