### ISSUE TITLE
How to include images from another package into build folder?

### ISSUE THREAD

**Issue by lucasdidur** [dart-lang/webdev#1074]
I have a project with multiples clients and I want to add a logo image for each one. 
So a create a project `client_common` and added a `logo.png` image. 
But this file is not included when I build.

How to pack this image on `webdev build` and use on my html?

**Comment by jakemac53** [comment]
Only files under the `lib/` directory of packages are copied into the `build` folder, you likely need to move them from some other directory into `lib`, and then reference them with a `packages/<package>/<path-under-lib>` uri in your html.

**Comment by lucasdidur** [comment]
I've already tried this, but there is no `packages/client_common/image/logo.png` file. Just a `main.ddc.js` file
