### ISSUE TITLE
Migrate to Debugger.setBreakpointByUrl

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#1076]
We currently set breakpoints by script ID. This has a number of drawbacks, especially around re-establishing breakpoints. There is an [API](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setBreakpointByUrl) to set breakpoints by URL. This API has the benefit of persisting across reloads.

> Sets JavaScript breakpoint at given location specified either by URL or URL regex. Once this command is issued, all existing parsed scripts will have breakpoints resolved and returned in locations property. Further matching script parsing will result in subsequent breakpointResolved events issued. This logical breakpoint will survive page reloads.

**Comment by natebosch** [comment]
Would the URL point into the `.js` file or would it consider a source map? What happens if the JS code is shifted around in the reload, does that cause any issues?

**Comment by grouma** [comment]
The URL would point to the containing module of the Dart file which would be a `.js` file. If the code get's shifted around we would have the same issue as Chrome does today which sets breakpoints as a per line basis.
