### ISSUE TITLE
URGENT: `webdev` release is depending on a pre-release package! Impossible to use `webdev` in SDK until fix!

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/webdev#1099]
Why a standard tool like `webdev`, in a release (2.6.0), depends on a pre-release version (`build_web_compilers` version `2.12.0-dev.1`)?!

This is breaking usage of `webdev`! Even pub.dev can't build and analyse the `webdev` package anymore!

When running `webdev server/build` it won't work with Dart 2.9.3.

Very odd to see this.

Any one that runs `pub global activate webdev` won't be able to use it!

New users or any IntelliJ developer won't be able to use the current `webdev` release.

FYI: You need a better CI steps.

**Comment by gmpassos** [comment]
Even the `CHANGELOG.md` points out the error:

# 2.6.0
- Require at least build_web_compilers version 2.12.0-dev.1.

**Comment by gmpassos** [comment]
pub.dev too:

![image](https://user-images.githubusercontent.com/6723954/92693258-bd129680-f31b-11ea-87c4-70950cdcf73f.png)

**Comment by gmpassos** [comment]
$> webdev serve

webdev could not run for this project.
The `build_web_compilers` version – 2.11.0 – is not within the allowed constraint – >=2.12.0-dev.1 <3.0.0.

**Comment by gmpassos** [comment]
dev_dependencies:
  build_runner: 1.10.1
  build_web_compilers: 2.11.0
  pedantic: ^1.9.2

**Comment by esaborit4code** [comment]
Downgrading as workaround till dependency is fixed:
```
pub global activate webdev 2.5.9
```

**Comment by gmpassos** [comment]
Pull request:
https://github.com/dart-lang/webdev/pull/1100

**Comment by jakemac53** [comment]
cc @grouma @annagrin

**Comment by grouma** [comment]
This should be resolved.
