### ISSUE TITLE
Serve on Windows spawns many terminals

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#111]
Root cause of issue outlined here: https://github.com/dart-lang/webdev/pull/110

I *believe* one solution is to update the persistent workers in `package:build_modules` to also start from the snapshot instead of the `.bat` files.

**Comment by grouma** [comment]
We'll need to update `package:build_modules` to always spawn with mode `detachedWithStdio`. We'll also need to work around https://github.com/dart-lang/sdk/issues/35874

**Comment by natebosch** [comment]
Why do we need `detachedWithStdio` if we're running from a snapshot?

If we want to run from a snapshot, should we run in an isolate?

**Comment by grouma** [comment]
The daemon needs to continue to run when webdev is killed. `detachedWithStdio` provides this behavior. I don't think it's possible to do this with an isolate.

**Comment by natebosch** [comment]
The persistent workers in build_mosules have the same lifespan at the daemon... Are those the workers under discussion?

**Comment by grouma** [comment]
Sorry, there are a couple things going on so let me be clear.

WebDev starts the daemon through `package:build_daemon` here:
https://github.com/dart-lang/build/blob/master/build_daemon/lib/client.dart#L75

Obviously this process needs to be long running and thus uses `detachedWithStdio`. Right now it works around pub spawning a new terminal by calling the snapshot directly:
https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/serve/daemon_client.dart#L20

Ideally it would call `pub.bat` instead of the snapshot.

Now this daemon process spins up a bunch of worker processes through `package:build_modules` here: https://github.com/dart-lang/build/blob/master/build_modules/lib/src/workers.dart#L68

These don't necessarily have to be long running. Since they are spawned with the default process mode, they create new terminals. See why here: https://github.com/dart-lang/sdk/issues/35809

We could change them to be isolates but that would be a breaking change to `BazelWorkerDriver`. These worker processes already properly shutdown if the daemon shuts down. I think it makes sense to leave them as processes and just update their mode.

**Comment by grouma** [comment]
This is mostly resolved. There is still a single flash of a terminal due to https://github.com/dart-lang/pub/issues/2042

**Comment by jakemac53** [comment]
@grouma should we close this?

**Comment by grouma** [comment]
There is no work to be done on webdev. This issue will be fully resolved once dart-lang/pub#2042 is resolved.

**Comment by grouma** [comment]
Closing this since there isn't work to be done in webdev.
