### ISSUE TITLE
Flutter web app doesn't work on Edge

### ISSUE THREAD

**Issue by xlf14leena** [dart-lang/webdev#1154]
flutter doctor output
C:\Programs\flutter>flutter doctor -v
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\Programs\flutter
    • Framework revision 198df796aa (5 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\LSHAH\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\LSHAH\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\LSHAH\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] VS Code, 64-bit edition (version 1.46.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Web Server (web)             • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 86.0.4240.75

• No issues found!

Below is the error
Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

ReferenceError: 'EventSource' is not defined
ReferenceError: 'EventSource' is not defined
   at W.EventSource__factoryEventSource (http://localhost:60549/dwds/src/injected/client.js:7265:7)
   at M.SseClient.prototype.SseClient$1 (http://localhost:60549/dwds/src/injected/client.js:22062:7)
   at M.SseClient$ (http://localhost:60549/dwds/src/injected/client.js:7937:7)
   at Anonymous function (http://localhost:60549/dwds/src/injected/client.js:22387:15)
   at Anonymous function (http://localhost:60549/dwds/src/injected/client.js:3793:15)
   at P._wrapJsFunctionForAsync_closure.prototype.call$2 (http://localhost:60549

**Comment by grouma** [comment]
Which version of Edge are you using? The last version based on Chromium should support `EventSource`: https://caniuse.com/?search=eventsource

**Comment by xlf14leena** [comment]
I was using version 44.18362.449.0. Thanks groupma. I updated my Edge to the latest version and it works now.
