### ISSUE TITLE
Shelf error handling prevents catching absolute URI exception, not exported

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/webdev#1182]
* The type is not exported so It cannot be caught without a source import.
* Shelf has the default behavior to catch and log all exceptions, which means the tool has nothing to catch

Would it be feasible for Dwds to expose a handler type API without involving shelf?

**Comment by grouma** [comment]
This is something we should be able to provide. Can you provide some links to the types you are referring to?

**Comment by jonahwilliams** [comment]
Its the AbsoluteImportUriException
