### ISSUE TITLE
Unhandled error detected in the injected client.js script.

### ISSUE THREAD

**Issue by fmatuszewski** [dart-lang/webdev#1205]
It is related to https://github.com/dart-lang/webdev/issues/1133
I can not resolve it by upgrading flutter because I have package dependencies that are not compatible with null safety functionality right now and I cant use the newer version. It would be great to cherry-pick this fix into the previous version.

Flutter 1.20.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (4 months ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

**Comment by grouma** [comment]
Can you not upgrade to a version before null safety? I believe the fix has been available for some time. Nonetheless, this issue doesn't belong here since we can't do anything from this package. Please re-open on the Flutter repo.
