### ISSUE TITLE
At instance method breakpoints, cannot always evaluate `this`

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/webdev#1264]
See the examples in #1263.  `this` shows in the variables window, but is not available in watch or eval.

**Comment by grouma** [comment]
This may be related to b/180673880

**Comment by grouma** [comment]
cc @annagrin is going to look at this as her work may resolve this.

**Comment by annagrin** [comment]
Judging by the error in the example, this failure is likely due to dart-lang/sdk#45266, which is already fixed - would you be able to try this on a current flutter version?

**Comment by grouma** [comment]
Can this be closed now?

**Comment by annagrin** [comment]
Closing for now, @vsmenon let's reopen it if it happens again.
