### ISSUE TITLE
On break on exception, displayed stack trace is unmapped JavaScript, not Dart.

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/webdev#1265]
Flutter issue: https://github.com/flutter/flutter/issues/101888

This is more of nit, but the hover displayed stack trace here is unmapped (not matching the stack trace window):

![Screen Shot 2021-03-06 at 12 13 30 PM](https://user-images.githubusercontent.com/2119553/110249727-5ec21b80-7f2c-11eb-8524-25c483c0dd02.png)

This might be `toString` on the thrown exception object - perhaps there is a way to intercept that.

fyi - @annagrin @grouma

**Comment by grouma** [comment]
I'm wondering if this is a `package:dwds` issue or just Flutter Web bootstrap issue. Internally we load a `stack_trace_mapper` as a part of the bootstrap to translate errors. I thought we override the `toString` of these exceptions and use the mapper to format them. I'm not super familiar with this infrastructure however.

cc @sigmundch @Markzipan are you more familiar with this infrastructure?

**Comment by Markzipan** [comment]
I'm not super familiar with how the mapper's hooked up, but this seems like hover events/exceptions are not being intercepted properly - as Vijay mentioned. Is it possible the hover tip's just receiving the stringified JS stackTrace object instead of a mapped version?

@nshahan for more input

**Comment by grouma** [comment]
I tested this yesterday and I don't believe this uses the `hover` feature, it just looks that way. When you hit an exception you are automatically presented with this view. I think the exception is simply returned as a string.

**Comment by nshahan** [comment]
Does the output change when you enable source maps in the browser where the app is running?

**Comment by grouma** [comment]
They should already be enabled. I'm not sure how that would impact this. Note this is outside of the browser and in VS Code.

**Comment by nshahan** [comment]
I don't know what paths the stack trace goes through to get from chrome to the VSCode UI. I was just curious if it does get source mapped before it leaves Chrome. Sounds like not. 

Which parts of the infrastructure are in play when you debug from VSCode? Does the same problem exist when you debug with DevTools? Do we need to add source mapping logic to these traces in DWDS?

**Comment by Markzipan** [comment]
Another point - did this tip used to be source mapped before?

**Comment by grouma** [comment]
@nshahan is going to dig into this but not immediately.

**Comment by grouma** [comment]
Note that in the Chrome console the logged exception is translated to Dart:

```
errors.dart:187 Uncaught Error: here
    at Object.throw_ [as throw] (errors.dart:233)
    at main.dart:22
    at isolate_helper.dart:80
```

However in Chrome DevTools I see this error when looking at the sources pane:
```
Could not load content for http://127.0.0.1:8080/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```

It looks like the `Exception` object in JS has a `stack` member that contains the untranslated error message:
```
"Error: here
    at Object.throw_ [as throw] (http://127.0.0.1:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4856:11)
    at http://127.0.0.1:8080/main.unsound.ddc.js:65:17
    at http://127.0.0.1:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:21874:9"
```


From a `package:dwds` perspective, we get a handle on that JS `Exception` object and "translate" it to an `InstanceRef` [here](https://github.com/dart-lang/webdev/blob/b2532e084bcdf900ac27ae8bf582bd2cb45c6645/dwds/lib/src/debugging/debugger.dart#L514).

@nshahan it'd be great if we could properly translate that exception there using some shared logic.

**Comment by annagrin** [comment]
Encountered this while playing with flutter code, so this is still happening. According to the logs, it looks like VSCode is displaying the exception object as string, not translating it to dart. 

@nshahan what needs to be done to translate this string to dart? I see that the stack trace is translated in chrome devtools, wonder if  we can wire dart code and dwds to do something similar.

**Comment by nshahan** [comment]
AFAIK the stack traces you see in chrome devtools will be mapped if you turn on the "Enable Javascript source maps" option and is performed entirely on their side. I find that if you turn it off and reload the stack frames will all be in Javascript.

That is to say I'm not aware of any translation being done on the DDC side. Is there a mapping being performed in Dart DevTools to translate the stack frames from javascript to dart when possible? If that exists, I'd expect we would want to use the same technique for VsCode.

**Comment by obeobe** [comment]
Please note that this also happens in Android Studio.

**Comment by obeobe** [comment]
I had a similar issue with non-mapped exceptions being printed in Android Studio console.
I wrote a small tool to work around it: https://github.com/obeobe/flutter-web-exception-mapper .
I actually don't think it would solve the specific problem in this issue, but maybe it could be adjusted to solve it or otherwise help.
https://github.com/obeobe/flutter-web-exception-mapper

**Comment by nshahan** [comment]
@annagrin I have discovered some more context regarding how to map a stack trace. If a stack trace mapper has been injected into the global namespace already (I think it is likely already there) You can call this `stackTraceMapper` getter https://github.com/dart-lang/sdk/blob/0e5f3f49c3917c838b13b79afdaf262d4b1b5d3d/sdk/lib/_internal/js_dev_runtime/private/debugger.dart#L980. It returns the function injected by the bootstrapping infrastructure to map Javascript stack trace to a Dart stack trace.

**Comment by annagrin** [comment]
Thanks @nshahan! I think we need to detect the object's type (StackTrace) and convert it to dart using the `stackTraceMapper` getter. We just need to find the right place to do so - the exception is shown as a string in `PauseException` event as seen in the logs, do you think exception's `toString()` method can be modified to do the translation?

**Comment by annagrin** [comment]
It seems to me that dwds can do some translation from JS to dart using the stack trace mapper at 

https://github.com/dart-lang/webdev/blob/88da408abcc6fcc2f820d8403c3245780b0be56a/dwds/lib/src/services/chrome_proxy_service.dart#L845

and/or here

https://github.com/dart-lang/webdev/blob/88da408abcc6fcc2f820d8403c3245780b0be56a/dwds/lib/src/debugging/debugger.dart#L551
