### ISSUE TITLE
Migrate dwds to null safety

### ISSUE THREAD

**Issue by jmagman** [dart-lang/webdev#1327]
`dwds` 11.0.2 is not null safe:
https://github.com/dart-lang/webdev/blob/b851f7491acc29973fad069623148bc58663026c/dwds/lib/dwds.dart#L5

This is preventing the `flutter_tool` from migrating to null safety.
https://github.com/flutter/flutter/blob/4a33813b3500308bb579a1dad5560971baec899f/packages/flutter_tools/lib/src/isolated/resident_web_runner.dart#L9

Note `dds` just published a null safe 2.0 https://github.com/dart-lang/sdk/issues/45756.

**Comment by jmagman** [comment]
\cc @jonahwilliams

**Comment by grouma** [comment]
What's the priority here?

**Comment by jonahwilliams** [comment]
This is low priority but nice to have

**Comment by devoncarew** [comment]
Is this issue complete (package:dwds is now null safe?)?

**Comment by devoncarew** [comment]
ping @elliette - do you know the status here?

**Comment by elliette** [comment]
All files have been migrated and DWDS is now null-safe, but the null-safe version has not yet been released (planning to do that this week)

**Comment by devoncarew** [comment]
Thanks! Can you update this (and https://github.com/dart-lang/webdev/issues/1640) when that happens?

**Comment by elliette** [comment]
Just published null-safe DWDS (`v.16.0.0`), therefore closing as completed.
