### ISSUE TITLE
Evaluate expression does not support `scope`

### ISSUE THREAD

**Issue by jacob314** [dart-lang/webdev#1336]
See the optional scope parameter from the evaluate method.
https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#evaluate
It appears to be ignored on the web

Repro:
Evaluate expression
`"object is Element || object is RenderObj"`
where scope is `{'object', validInstanceRefId}`

Result:
`[ErrorRef id: 2062, kind: error, message: CompilationError: Getter not found: 'object'.`

**Comment by annagrin** [comment]
Idea: modify the `evaluate()` with scope to compile `(scope) => expression` to `jsExpression` and then send `Runtime.callFunctionOn(jsExpression, [scopeIds])` to chrome.

**Comment by jacob314** [comment]
That is what the polyfill for `scope` I've temporarily added to DevTools does. https://github.com/flutter/devtools/pull/3112
