### ISSUE TITLE
Numerous CI flakes and failures due to failure to load dill files 

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1345]
A few PRs got stuck lately in CI due to failures to load dill files in the expression compiler worker on linux and windows.

I can repro it on a local windows machine, but not on linux or a mac machine, on a recent dev SDK (2.14.0-216.0.dev)
but not on stable SDK (2.12.3)

See CI failures on linux and windows on the following PR: 
https://github.com/dart-lang/webdev/pull/1343

Investigation showed the following:
- build runner sends the whole file in response to a HEAD request
- expression compiler worker uses HttpFileSystemEntity that sends a HEAD requests to check if a file exists,
   but does not read the body, end closes the connection while the server is still sending bytes.
- This causes an intermittent 'broken pipe' error during loading dill files.
- Since those failures are happening more often that before, I suspect a change in SDK that uncovered the problem,
  i.e. some change in scheduling async calls or a change to sockets. 

Suggested short term fix:
- read the response for HEAD requests in dwds's proxy and send a new empty response to the client.

Suggested long term fix:
- update the build_runner not to send the file contents in response to a HEAD request
  https://github.com/dart-lang/build/issues/3129

- update HttpFileSystemEntity to read the response on HEAD requests
  https://github.com/dart-lang/sdk/issues/46388
   still needed even with the empty body to receive the headers)

**Comment by grouma** [comment]
cc @kevmoo as I believe you were mucking around with HEAD requests lately.

**Comment by kevmoo** [comment]
Yup. CC @natebosch . We started doing work here w/ pkg:shelf_static  That's landed.

Happy to chat more!

**Comment by annagrin** [comment]
@kevmoo I am not sure if those failures are caused by your change, but if they are, you change seemed to uncover some bugs... I see the content-length header in the responses coming from the server though.

- Server (Server.dart in build_runner) adds 'contents-length' header and the full file contents on all requests: 
 https://github.com/dart-lang/build/blob/fc6ea9fe3d6d201191e043f438ac11edf245e459/build_runner/lib/src/server/server.dart#L367

- Client  (HttpFileSystemEntity in SDK) does not read the 'HEAD' request's contents and closes the client connection too early:
https://github.com/dart-lang/sdk/blob/82ea8416ed2a22e40c5c67252cb37bebec3a57e8/pkg/vm/lib/http_filesystem.dart#L32

- Client also seems to have a missing await when getting responses which can close the client early as well:
https://github.com/dart-lang/sdk/blob/82ea8416ed2a22e40c5c67252cb37bebec3a57e8/pkg/vm/lib/http_filesystem.dart#L66

Strangely this only happens on some machines - and alas not on my mac so I cannot easily repro.

**Comment by kevmoo** [comment]
There have been changes to the SDK, too. I'm not sure. 🤷

**Comment by annagrin** [comment]
I think I have a fix (on the client side for now): https://dart-review.googlesource.com/c/sdk/+/203841

Will check out how it works with webdev CI after it lands in the SDK.

**Comment by annagrin** [comment]
The previous fix did not remove flakes. I managed to cause similar errors on my local machine and created another PR in the SDK that makes the AssetFileSystem more fault-tolerant:

https://dart-review.googlesource.com/c/sdk/+/204880

Will see if flakes improve after it lands and gets published.
Might be related: https://github.com/flutter/flutter/issues/84012

**Comment by annagrin** [comment]
Update: flakes happen less often, but still seem to be an issue, for example, in https://github.com/dart-lang/webdev/pull/1349.

Fix is in https://dart-review.googlesource.com/c/sdk/+/206581, already published and is running in the CI.

Will keep this open a little longer to verify the issues are gone.

**Comment by annagrin** [comment]
Update: seems like broken connections are still happening, submitted another (hopefully final) fix above.
