### ISSUE TITLE
build_config 1.0.0

### ISSUE THREAD

**Issue by garyng2000** [dart-lang/webdev#1354]
I tried to include web3dart in my flutter web app but dart complains incompatibility due to the build_config use between webdev and web3dart

the author said this is a webdev issue as it doesn't support the latest and said I should complain here

https://github.com/simolus3/web3dart/issues/181

so what gives ?

**Comment by grouma** [comment]
This may be addressed by https://github.com/dart-lang/webdev/pull/1351

What version of build_config is required?

**Comment by garyng2000** [comment]
build_config 1.0.0 and a number of other build related packages(looks like there was a pretty major change due to null safety).

**Comment by natebosch** [comment]
Yeah this should have been fixed by https://github.com/dart-lang/webdev/pull/1351

If you are still having trouble resolving to the latest `build_config` please post the pub error.
