### ISSUE TITLE
Consider adding a level field to package:build_daemon's server log

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#137]
See https://github.com/dart-lang/webdev/pull/125 for context

**Comment by jakemac53** [comment]
We should also add the logger name

**Comment by jakemac53** [comment]
and we should consider adding `error` and `stackTrace` fields also, although those would have to be serialized which might diminish their value

**Comment by grouma** [comment]
Closing in favor of https://github.com/dart-lang/build/issues/2208
