### ISSUE TITLE
Debugger intermittently hangs on start with multiple breakpoints in source

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1381]
Parent issue: https://github.com/Dart-Code/Dart-Code/issues/3518

@DanTup I cannot comment on the original issue for some reason...

@DanTup @apadol-adeo I tried to repro the problem and only got partial success - I can cause the hang on setting more than one breakpoints about every 10th start of the debugger, but it is easily fixed on my machine by stopping the debugger and starting again. The issue seems to be in chrome - a couple of simultaneous calls to `setBreakpointByUrl` sometimes return `Inspector.targetCrashed` notification. 

Needing to reboot the machine does not seem related to dwds or flutter tools since `flutter run -d chrome --web-port=5000` works. Not sure if it is related to VSCode or some machine configuration though.

I will try to workaround this issue and will reach the chrome team so we can have it fixed - hopefully this will help with the machine needing reboot as well, if only by removing the cause.

**Comment by apadol-adeo** [comment]
From what I can see, it seems related to breakpoints indeed.
I did some work on my project this morning, and had maybe one or two breakpoints set, and everyting worked fine.

I did a test run with 8 breakpoints (inside the same file), and ended up with the broken chrome window described in the original ticket.
I removed the breakpoints, and did another test run, and the initial good behavior came back.
I'll try some other scenarios to try to give you more infos on how to reproduce it.
