### ISSUE TITLE
frontend_server_client test times out in CI on windows

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1386]
See: https://github.com/dart-lang/webdev/pull/1384/checks?check_run_id=3363791474

**Comment by jakemac53** [comment]
See also https://github.com/dart-lang/webdev/issues/1383 - I wonder if this was not actually related to hot reload but just slow compilation on windows?

What happens if we just increase the timeouts?

**Comment by annagrin** [comment]
Timeout increase might help, but windows sometimes flushes out race conditions that create hangs, since the async scheduling is a bit different.

**Comment by jakemac53** [comment]
Ya, the question is if this is actually hanging or just being slow. I think it makes sense to double the timeout, unskip the other tests, and see if we still see timeouts?

**Comment by jakemac53** [comment]
Based on a bit of investigation this definitely seems related to a hang and not just slowness. When it passes it passes very quickly. Trying to figure out where exactly it is failing.

**Comment by jakemac53** [comment]
For now skipping the test is probably fine.
