### ISSUE TITLE
We should support webdev.yaml

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#139]
We should support providing a `webdev.yaml` which contains desired configuration. This will also allow us to change out certain configuration on the fly without needing to restart webdev, e.g. if auto-refresh is enable.

**Comment by natebosch** [comment]
Changing config on the fly by editing a file is, I think, one of the less intuitive options. Would a separate serving port and a web UI work for this?

I think that a config file works best when it's either global in the user's home directory, or something that changes infrequently but is specific to the project.

**Comment by grouma** [comment]
Yes the long term goal is to enable configuration editing through a UI, much like we do internally. My initial implementation for this has the configuration scoped to the project. Depending on how well the hot-restart feature works, I imagine it won't be updated too frequently. Otherwise I can see folks toggling through our supported workflows fairly often.

**Comment by grouma** [comment]
Closing for now. We may come back to this.
