### ISSUE TITLE
Finalize all restart/reload/refresh args and workflow

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/webdev#140]
We already have decided that we want to rename `--live-reload` to `--auto-refresh`. There is a separate but related issue with the `--hot-restart` and `--hot-reload` flags, where really what they are doing is enabling the _automatic_ restart/reload after each build, as well as enabling/disabling the feature via the injected JS.

As we move to a model where reloads/restarts/refreshes can be triggered by other actions other than a build, I don't think the existing naming make sense any more. We always need support in all apps to perform any of those actions, based on arbitrary triggers.

Therefore, I think we should do the following:

- Always inject the code to support all types of actions
- Drop the `--hot-restart` and `--hot-reload` flags.
- Make a new `auto` _option_, which allows 3 values `refresh` (refreshes the entire window), `restart` (reloads changed modules and re-runs main), and `reload` (performs a stateful hot reload).
  - This would replace the `--auto-refresh` idea, but its essentially the same `--auto=refresh`.

cc @kevmoo @grouma @natebosch @vsmenon wdyt?

**Comment by jakemac53** [comment]
ping @kevmoo @natebosch wdyt about the proposed args?

**Comment by natebosch** [comment]
SGTM

**Comment by kevmoo** [comment]
Let's talk tomorrow. I was OOO
