### ISSUE TITLE
Cannot use Chrome extension with flutter CLI 

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/webdev#1410]
Repro:

- Sync down flutter samples and run https://github.com/flutter/samples/tree/master/navigation_and_routing/
- ` flutter run -d web-server`
- open the URL in chrome with the extention installed (v1.23)
- click on the extension

The top bit drops down saying things are running – but I don't see the UI!

```
Flutter 2.6.0-0.0.pre • channel dev • git@github.com:flutter/flutter
Framework • revision 83b9e99cfb (3 weeks ago) • 2021-08-23 19:03:21 +0200
Engine • revision d5adde01dd
Tools • Dart 2.15.0 (build 2.15.0-42.0.dev)
```

**Comment by kevmoo** [comment]
CC @jacob314

**Comment by annagrin** [comment]
Looked at that a bit - debugger service does start but devtools are not launched. Looks like flutter tools does not pass the devtools launcher to dwds:

https://github.com/flutter/flutter/blob/fa0782b696dbaa141936d29332ce9d3807dc9acd/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L274

**Comment by annagrin** [comment]
Closing this issue in favor of a flutter one.
