### ISSUE TITLE
Eliminate DevTools pub dependencies

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/webdev#1474]
As of DevTools version 2.8.0, DevTools will no longer be shipped on pub. However, a recent need to update the devtools_server package on pub brought to light that we still have outstanding dependencies on devtools packages in the ecosystem. 

webdev depends on package:devtools and package:devtools_server.
dwds has dev_dependencies on package:devtools and package:devtools_server.

Can we eliminate these dependencies? 

CC @bkonyi

**Comment by annagrin** [comment]
We would need to switch to starting a process instead of serving devtools via an API. This might increase Devtools IPL. Will try and report back.
