### ISSUE TITLE
I want to change the resource path of the built index.html dynamically

### ISSUE THREAD

**Issue by myConsciousness** [dart-lang/webdev#1493]
Hi, developers!

I don't know if this question should be asked in this repository, but I did some research and didn't find any clues.

Is there any way to dynamically change the resource path in index.html when building with flutter build web?For example, when I run flutter build web with default values, it builds with the following code, but in the environment where I want to deploy this source, it should be `xxxxxxx/main.dart.js`. The same applies to resources other than main.dart.js.

Currently, I am manually changing the resource path of the built index.html, but if this can be done in the flutter settings, I would like to adopt that.

```dart
      function loadMainDartJs() {
        if (scriptLoaded) {
          return;
        }
        scriptLoaded = true;
        var scriptTag = document.createElement("script");
        scriptTag.src = "main.dart.js";
        scriptTag.type = "application/javascript";
        document.body.append(scriptTag);
      }
```

Thank you!

**Comment by annagrin** [comment]
@myConsciousness this is best to ask on flutter repo - `index.html` and `main.dart.js` are generated by flutter tools:

https://github.com/flutter/flutter/blob/2a4e573dcdf5455ebdf0a2b3541e190021a649f1/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L816

and added to index file here: https://github.com/flutter/flutter/blob/2a4e573dcdf5455ebdf0a2b3541e190021a649f1/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L71
