### ISSUE TITLE
Process events from other devtools pages

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1517]
Dwds uses Devtools pageReady event from the debugger page to determine the load time of Devtools.  For flutter apps, the first event would need to come from the Inspector page instead. Change dwds to record the first pageReady event from any page instead:

https://github.com/dart-lang/webdev/blob/40f826520a3b5ba3ba72f0864572a49410174c88/dwds/lib/src/dwds_vm_client.dart#L155

**Comment by jyameo** [comment]
related: https://github.com/dart-lang/webdev/issues/2394
