### ISSUE TITLE
white page / webddev serve not working

### ISSUE THREAD

**Issue by superandrew** [dart-lang/webdev#1544]
I have an existent flutter project. I enabled web in this project, and I am able to run the application in chrome. Enabling web created a `web` folder with this content. When I build, there's a `build` folder with this content.

<img width="342" alt="CleanShot 2022-03-22 at 10 14 18@2x" src="https://user-images.githubusercontent.com/71364/159446790-e4ba10d7-293b-47cf-bfc3-ffc06ca7d8df.png">

<img width="347" alt="CleanShot 2022-03-22 at 10 14 55@2x" src="https://user-images.githubusercontent.com/71364/159446894-5861d0a2-84fa-45f9-b066-3142aeb3ef10.png">

If I run `webdev serve` (with the options `--delete-conflicting-outputs   ` otherwise it won't build) I get this output 

```
❯ webdev serve -- --delete-conflicting-outputs      
[INFO] Reading cached asset graph completed, took 557ms
[INFO] Checking for updates since last build completed, took 1.2s
[INFO] Serving `web` on http://127.0.0.1:8080
[INFO] Running build completed, took 266ms
[INFO] Caching finalized dependency graph completed, took 643ms
[INFO] Succeeded after 927ms with 0 outputs (0 actions)
[INFO] ------------------------------------------------------------------------------------------------------------------------------------------------
```
However, when I open the page in chrome, this is the only output in console.

<img width="840" alt="CleanShot 2022-03-22 at 10 16 58@2x" src="https://user-images.githubusercontent.com/71364/159447260-cf5a4e98-e227-41c8-a146-c48bcc1a9b77.png">

I'm not sure if this is a bug or a misconfiguration. I tried to follow all instructions on the webdev package but I still don't understand if it's supposed to serve the `./build/web` folder or the `web` folder and I don't know where to look to understand what's going on.

**Comment by elliette** [comment]
Hi @superandrew - `webdev` isn't intended to be used with Flutter apps. Is there a reason why you are trying to use it instead for `flutter run`? Thanks!
