### ISSUE TITLE
Better error handling for Dart Debug Extension

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#1549]
Currently when a user sends a start debugging / start inspecting request from the embedded Dart panels, we have no error handling logic. This means that if the request is unsuccessful, the panel will be blank until the closes and reopens Chrome DevTools. 

- [ ] If there is an error, we should re-enable the "Start debugging / start inspecting" button and show the error. Ideally we could also add analytics reporting. 
- [ ] If the debugger disconnects, it would be great if we could detect that as well

**Comment by bkonyi** [comment]
Closing since the debug extension was rewritten since this issue was filed.
