### ISSUE TITLE
Breakpoints don't work with Chrome version 100.0.4896.75

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1557]
See: https://github.com/flutter/flutter/issues/101139, https://github.com/flutter/flutter/issues/101318

**Comment by annagrin** [comment]
The root cause is an empty `CallFrame.url` field in call  frames inside the stack trace returned from chrome remote debugging. Looks like Chrome removed the `CallFrame.url` intentionally:

See https://chromium.googlesource.com/v8/v8/+/21f72f82ce854762d6bc1c780d3b108dc1947f5d and https://bugs.chromium.org/p/chromium/issues/detail?id=1270316

I am looking if we can find the url via other means.

**Comment by DanTup** [comment]
> I am looking if we can find the url via other means.

I don't know if it's relevant/useful, though in the linked bug it mentions:

> there's no point in transmitting a copy of the URL for every CallFrame, especially when the scriptId already can resolve to the URL via `Debugger.scriptParsed` events.

**Comment by annagrin** [comment]
Not fixed yet, seems like the PR above closed it by a way if a glitch:)

**Comment by longtimedeveloper** [comment]
@annagrin  @DanTup pray that you and the team can sort this out.  Thank you for your hard work for us.  I'm starting a new project later this week, working from Ukraine and Moldova.  Blessings, Karl

**Comment by furkanvatandas** [comment]
Same problem in Version 100.0.4896.88 (Official Build) (x86_64)

**Comment by fhuonder** [comment]
https://github.com/dart-lang/webdev/issues/1581

**Comment by annagrin** [comment]
This is now fixed in https://github.com/dart-lang/webdev/issues/1557 and https://github.com/dart-lang/webdev/pull/1588.
