### ISSUE TITLE
Create hotfix for chrome 100 update support for dwds-v12.1.0

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1568]
Create hotfix for chrome 100 update support for dwds-v11.5.1

We need to update next version of stable flutter to unblock users affected by https://github.com/flutter/flutter/issues/101224

Related: https://github.com/dart-lang/webdev/issues/1567
Related: https://github.com/dart-lang/webdev/issues/1557
Original issue: https://github.com/flutter/flutter/issues/101224

**Comment by longtimedeveloper** [comment]
@annagrin thank you for sorting this out.  We are feeling the pain out here in the field.

**Comment by annagrin** [comment]
@longtimedeveloper you are very welcome! Sorry it is taking so long but it needs a lot of hot fixes to properly work everywhere. This one should fix debugging for the users of the current webdev version and next flutter stable.

**Comment by annagrin** [comment]
Fixed in https://github.com/dart-lang/webdev/pull/1570

**Comment by longtimedeveloper** [comment]
@annagrin thank you very much for a quick response to this external issue. Bless you and the Dart/Flutter Team.  Karl
