### ISSUE TITLE
Mismatch in behavior for extension debugger and webkit debugger on restart/reload

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1581]
Extension debugger is clearing the scripts map on `Page.frameStartedLoading` event, and Webkit debugger is clearing the scripts on `Debugger.globalObjectCleared`. The former is fired during hot restart or page reload, and the latter is not. 

**Extension debugger**

https://github.com/dart-lang/webdev/blob/17a84a2f1e12fb79dac72f53d61abd79b1e487de/dwds/lib/src/servers/extension_debugger.dart#L266

**Webkit debugger**

https://github.com/google/webkit_inspection_protocol.dart/blob/da43164be2387157671c88be9d3acd26a1806b47/lib/src/debugger.dart#L162

This causes differences in behavior in flutter for web:
- Using debug extension with `Web server` device: breakpoints are not resolved correctly after a reload/restart
- Using webkit debugger with `Chrome` device: breakpoints are working normally.

See: https://github.com/flutter/flutter/issues/101224#issuecomment-1097565580

**Comment by fhuonder** [comment]
Hi

Would be great when this is going to be fixed soon.
Due to our development environment with vscode/devcontainer (Windows 10 / Docker with WSL2 backend) we must use the `web server device`.

**Comment by longtimedeveloper** [comment]
@fhuonder do you have a link or docs on how to use the `web server device`?  This mess is painful for us.  Thank you, blessings, Karl

**Comment by fhuonder** [comment]
When you run `flutter devices --show-web-server-device` the web server device is shown. This is hidden by default.
Then you can run your application with `flutter run -d web-server`.

The IDE plugins normally support for that, e.g. in vscode (when you run `Select Device` from the command palette) it looks like this:
![image](https://user-images.githubusercontent.com/39723648/163319074-ee319913-7422-462c-bf2c-935c0c078ff7.png)

Hope this helps...

**Comment by longtimedeveloper** [comment]
@fhuonder thank you SO MUCH!!!!!!!!!!!  Blessings from Ukraine.  

One day when this war is over, Lord willing I want to visit these two places in Switzerland.

International Museum of the Reformation, Rue du Cloître 4 CH-1204 Geneva Switzerland 
https://www.musee-reforme.ch/en/

Patek Philippe Museum, Rue des Vieux-Grenadiers 7, 1205 Genève, Switzerland  
https://www.patek.com/en/company/patek-philippe-museum
