### ISSUE TITLE
Support VM version 8.3.0

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1585]
The version adds an optional parameter `libraryFilters` to the `getSourceReport` VM service API.

```dart
@override
  Future<SourceReport> getSourceReport(
    String isolateId,
    /*List<SourceReportKind>*/ List<String> reports, {
    String? scriptId,
    int? tokenPos,
    int? endTokenPos,
    bool? forceCompile,
    bool? reportLines,
    List<String>? libraryFilters,
  }) ```

**Comment by liamappelbe** [comment]
The _libraryFilters_ parameter is intended to be used when gathering coverage for the whole isolate. If it is provided, the _SourceReport_ will only contain results from scripts with URIs that start with one of the filter strings. For example, pass `["package:foo/"]` to only include scripts from the foo package.

https://github.com/dart-lang/sdk/issues/48754
