### ISSUE TITLE
`dart pub global activate` fails (Dart 2.18.0-104.0.dev)

### ISSUE THREAD

**Issue by laurinneff** [dart-lang/webdev#1605]
<details>
<summary><code>dart pub global activate webdev</code></summary>
<pre><code>Resolving dependencies...
+ _fe_analyzer_shared 34.0.0 (39.0.0 available)
+ args 2.3.0
+ async 2.9.0
+ browser_launcher 1.1.0
+ build_daemon 3.1.0
+ built_collection 5.1.1
+ built_value 8.3.0
+ charcode 1.3.1
+ checked_yaml 2.0.1
+ collection 1.16.0
+ convert 3.0.1
+ crypto 3.0.2
+ dds 2.2.0
+ dds_service_extensions 1.3.0
+ devtools_shared 2.13.1
+ dwds 12.1.1 (14.0.1 available)
+ fixnum 1.0.0
+ http 0.13.4
+ http_multi_server 3.2.0
+ http_parser 4.0.0
+ io 1.0.3
+ json_annotation 4.5.0
+ json_rpc_2 3.0.1
+ logging 1.0.2
+ meta 1.7.0
+ mime 1.0.2
+ package_config 2.0.2
+ path 1.8.1
+ pedantic 1.11.1
+ pool 1.5.0
+ pub_semver 2.1.1
+ pubspec_parse 1.2.0
+ shelf 1.3.0
+ shelf_packages_handler 3.0.0
+ shelf_proxy 1.0.1
+ shelf_static 1.1.0
+ shelf_web_socket 1.0.1
+ source_maps 0.10.10
+ source_span 1.9.0
+ sse 4.1.0
+ stack_trace 1.10.0
+ stream_channel 2.1.0
+ stream_transform 2.0.0
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ usage 4.0.2
+ uuid 3.0.6
+ vm_service 8.3.0
+ watcher 1.0.1
+ web_socket_channel 2.2.0
+ webdev 2.7.8
+ webkit_inspection_protocol 1.0.1
+ yaml 3.1.0
Building package executables...
Failed to build webdev:webdev:
../Pub/Cache/hosted/pub.dartlang.org/dwds-12.1.1/lib/src/services/chrome_proxy_service.dart:540:24: Error: The method 'ChromeProxyService.getSourceReport' has fewer named arguments than those of overridden method 'VmServiceInterface.getSourceReport'.
  Future<SourceReport> getSourceReport(String isolateId, List<String> reports,
                       ^
../Pub/Cache/hosted/pub.dartlang.org/vm_service-8.3.0/lib/src/vm_service.dart:846:24: Context: This is the overridden method ('getSourceReport').
  Future<SourceReport> getSourceReport(
                       ^
../Pub/Cache/hosted/pub.dartlang.org/dwds-12.1.1/lib/src/services/chrome_proxy_service.dart:540:24: Error: The method 'ChromeProxyService.getSourceReport' doesn't have the named parameter 'libraryFilters' of overridden method 'VmServiceInterface.getSourceReport'.
  Future<SourceReport> getSourceReport(String isolateId, List<String> reports,
                       ^
../Pub/Cache/hosted/pub.dartlang.org/vm_service-8.3.0/lib/src/vm_service.dart:846:24: Context: This is the overridden method ('getSourceReport').
  Future<SourceReport> getSourceReport(
</code></pre>
</details>

<details>
<summary><code>flutter doctor -v</code></summary>
<pre><code>[✓] Flutter (Channel master, 2.13.0-0.0.pre.1030, on Microsoft Windows [Version 10.0.22000.652], locale de-CH)
    • Flutter version 2.13.0-0.0.pre.1030 at C:\Users\lan\AppData\Local\Programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7c822310ee (15 minutes ago), 2022-05-11 10:34:05 -0400
    • Engine revision b39d1f2e41
    • Dart version 2.18.0 (build 2.18.0-104.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\lan\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.67.1)
    • VS Code at C:\Users\lan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.652]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
</code></pre>
</details>

**Comment by dany-nonstop** [comment]
same error here. tried both choco and flutter install. I cannot believe this obvious bug was not tested in dart release. Installing webdev 2.7.7 however works fine.

```
dart.exe pub global activate webdev 2.7.7
Resolving dependencies...
+ args 2.3.1
+ async 2.9.0
+ browser_launcher 1.1.0
+ build_daemon 3.1.0
+ built_collection 5.1.1
+ built_value 8.3.0
+ charcode 1.3.1
+ checked_yaml 2.0.1
+ clock 1.1.0
+ collection 1.16.0
+ convert 3.0.1
+ crypto 3.0.2
+ dds 2.1.6+3 (2.2.0 available)
+ devtools 2.8.0 (2.9.4 available)
+ devtools_server 2.8.0 (2.9.4 available)
+ devtools_shared 2.8.0 (2.13.1 available)
+ dwds 11.5.2 (14.0.1 available)
+ fixnum 1.0.0
+ http 0.13.4
+ http_multi_server 3.2.0
+ http_parser 4.0.0
+ intl 0.17.0
+ io 1.0.3
+ json_annotation 4.5.0
+ json_rpc_2 3.0.1
+ logging 1.0.2
+ meta 1.7.0
+ mime 1.0.2
+ package_config 2.0.2
+ path 1.8.1
+ pedantic 1.11.1
+ pool 1.5.0
+ pub_semver 2.1.1
+ pubspec_parse 1.2.0
+ shelf 1.3.0
+ shelf_packages_handler 3.0.0
+ shelf_proxy 1.0.1
+ shelf_static 1.1.0
+ shelf_web_socket 1.0.1
+ source_maps 0.10.10
+ source_span 1.9.0
+ sse 4.1.0
+ stack_trace 1.10.0
+ stream_channel 2.1.0
+ stream_transform 2.0.0
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ usage 4.0.2
+ uuid 3.0.6
+ vm_service 7.5.0 (8.3.0 available)
+ watcher 1.0.1
+ web_socket_channel 2.2.0
+ webdev 2.7.7 (2.7.8 available)
+ webkit_inspection_protocol 1.0.1
+ yaml 3.1.0
Downloading webdev 2.7.7...
Downloading dwds 11.5.2...
Downloading vm_service 7.5.0...
Downloading intl 0.17.0...
Downloading clock 1.1.0...
Downloading dds 2.1.6+3...
Downloading devtools_server 2.8.0...
Downloading devtools_shared 2.8.0...
Downloading devtools 2.8.0...
Building package executables...
Built webdev:webdev.
Installed executable webdev.
Warning: Pub installs executables into C:\Users\yudan\AppData\Local\Pub\Cache\bin, which is not on your path.
You can fix that by adding that directory to your system's "Path" environment variable.
A web search for "configure windows path" will show you how.
Activated webdev 2.7.7.
```

**Comment by L3odr0id** [comment]
Same error

<details>
  <summary>flutter doctor -v</summary>
  
  [✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale ru-RU)
    • Flutter version 2.10.4 at /Users/null/fvm/versions/2.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (7 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/null/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by Sominemo** [comment]
Fails with the same error on Dart 2.17.0 for me too

<details>
  <summary>flutter doctor -v</summary>
<pre>
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22000.613], locale en-150)
    • Flutter version 3.0.0 at C:\Users\Sominemo\DEV\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Sominemo\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\Sominemo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.613]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.64
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</pre>
</details>

**Comment by elliette** [comment]
Sorry for the inconvenience, this issue should now be fixed. See https://github.com/dart-lang/webdev/issues/1607

Run `dart pub global activate webdev 2.7.9` to get the lastest Webdev. Thanks!
