### ISSUE TITLE
publish package:frontend_server_client

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#1606]
Can we publish package:frontend_server_client? The last published version has the root of this repo in it's pubspec `repository` field - instead of the full repo url including the monorepo path - and that's causing issues with some tooling I'm writing.

The repository field in the pubspec at head is correct - it was updated in a recent commit.

**Comment by annagrin** [comment]
Ah apologies, got confused with the frontend_server_common:) Will publish!

**Comment by devoncarew** [comment]
(also, I noticed a stay todo: in the readme file; https://github.com/dart-lang/webdev/pull/1617)

**Comment by jakemac53** [comment]
Should be fine to publish

**Comment by annagrin** [comment]
published frontend-server-client-v2.1.3
