### ISSUE TITLE
Cannot activate webdev with Dart 2.17

### ISSUE THREAD

**Issue by mnordine** [dart-lang/webdev#1607]
Unfortunately, once again, `webdev` has broke our CI pipelines.

```
$ dart pub global activate webdev
+ _fe_analyzer_shared 34.0.0 (39.0.0 available)
+ args 2.3.1
+ async 2.9.0
+ browser_launcher 1.1.0
+ build_daemon 3.1.0
+ built_collection 5.1.1
+ built_value 8.3.0
+ charcode 1.3.1
+ checked_yaml 2.0.1
+ collection 1.16.0
+ convert 3.0.1
+ crypto 3.0.2
+ dds 2.2.0
+ dds_service_extensions 1.3.0
+ devtools_shared 2.13.1
+ dwds 12.1.1 (14.0.1 available)
+ fixnum 1.0.0
+ http 0.13.4
+ http_multi_server 3.2.0
+ http_parser 4.0.0
+ io 1.0.3
+ json_annotation 4.5.0
+ json_rpc_2 3.0.1
+ logging 1.0.2
+ meta 1.7.0
+ mime 1.0.2
+ package_config 2.0.2
+ path 1.8.1
+ pedantic 1.11.1
+ pool 1.5.0
+ pub_semver 2.1.1
+ pubspec_parse 1.2.0
+ shelf 1.3.0
+ shelf_packages_handler 3.0.0
+ shelf_proxy 1.0.1
+ shelf_static 1.1.0
+ shelf_web_socket 1.0.1
+ source_maps 0.10.10
+ source_span 1.9.0
+ sse 4.1.0
+ stack_trace 1.10.0
+ stream_channel 2.1.0
+ stream_transform 2.0.0
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ usage 4.0.2
+ uuid 3.0.6
+ vm_service 8.3.0
+ watcher 1.0.1
+ web_socket_channel 2.2.0
+ webdev 2.7.8
+ webkit_inspection_protocol 1.0.1
+ yaml 3.1.0
Building package executables... (1.0s)
Failed to build webdev:webdev:
../../.pub-cache/hosted/pub.dartlang.org/dwds-12.1.1/lib/src/services/chrome_proxy_service.dart:540:24: Error: The method 'ChromeProxyService.getSourceReport' has fewer named arguments than those of overridden method 'VmServiceInterface.getSourceReport'.
  Future<SourceReport> getSourceReport(String isolateId, List<String> reports,
                       ^
../../.pub-cache/hosted/pub.dartlang.org/vm_service-8.3.0/lib/src/vm_service.dart:846:24: Context: This is the overridden method ('getSourceReport').
  Future<SourceReport> getSourceReport(
                       ^
../../.pub-cache/hosted/pub.dartlang.org/dwds-12.1.1/lib/src/services/chrome_proxy_service.dart:540:24: Error: The method 'ChromeProxyService.getSourceReport' doesn't have the named parameter 'libraryFilters' of overridden method 'VmServiceInterface.getSourceReport'.
  Future<SourceReport> getSourceReport(String isolateId, List<String> reports,
                       ^
../../.pub-cache/hosted/pub.dartlang.org/vm_service-8.3.0/lib/src/vm_service.dart:846:24: Context: This is the overridden method ('getSourceReport').
  Future<SourceReport> getSourceReport(
                       ^
```

**Comment by mnordine** [comment]
SO question: https://stackoverflow.com/questions/72200137/dart-pub-global-run-webdev-serve-building-package-executable-failed-to-build

**Comment by marandaneto** [comment]
Same here, I can reproduce locally on macOS Monterey 12.3.1

**Comment by mnordine** [comment]
Yeah, I tried forking this project and activating webdev, but that doesn't work with `--git-path`, apparently: https://github.com/dart-lang/sdk/issues/49001

**Comment by bkonyi** [comment]
Unfortunately this is a tricky one to work around since there hasn't been a change to `webdev`, just one of its dependencies, so we'd need to try a version that has a `vm_service` version `<8.0.0`. Let me see if I can find one that still works as a bandaid until someone comes into the office that can publish a new `webdev` with fixed constraints.

**Comment by mnordine** [comment]
8.2.2 works

**Comment by bkonyi** [comment]
A quick workaround is to just activate `webdev` version `2.7.7`. I don't think anything significant has changed since that version was published, other than some bug fixes.

Just run this:

`dart pub global activate webdev 2.7.7`

**Comment by bkonyi** [comment]
> > Unfortunately this is a tricky one to work around since there hasn't been a change to webdev, just one of its dependencies
> 
> Not sure I understand. Wouldn't you "just" update dependencies and release `2.7.9`?

Yes, that's the fix, but I don't have the permissions to publish a new version, which makes it tricky to work around until someone with the right permissions comes online :-)

**Comment by mnordine** [comment]
Hopefully `2.7.7` works for now, thx for the workaround!

**Comment by GhostCore07** [comment]
> A quick workaround is to just activate `webdev` version `2.7.7`. I don't think anything significant has changed since that version was published, other than some bug fixes.
> 
> Just run this:
> 
> `dart pub global activate webdev 2.7.7`

Thank you I ran this command although I do not understand what it's doing and it fixed for now. Will I need to "undo" this command sometime down the line when the problem "fixes itself" the same way it "broke itself"? How would I do that?

**Comment by elliette** [comment]
> > A quick workaround is to just activate `webdev` version `2.7.7`. I don't think anything significant has changed since that version was published, other than some bug fixes.
> > Just run this:
> > `dart pub global activate webdev 2.7.7`
> 
> Thank you I ran this command although I do not understand what it's doing and it fixed for now. Will I need to "undo" this command sometime down the line when the problem "fixes itself" the same way it "broke itself"? How would I do that?

Hi! That command tells Dart to use Webdev version 2.7.7 (instead of the latest, Webdev version 2.7.8). Once Webdev 2.7.9 is released, you can run `dart pub global activate webdev 2.7.9`

See: https://dart.dev/tools/pub/cmd/pub-global#version-constraint

**Comment by elliette** [comment]
New version of Webdev has beeb published, this should be fixed.
