### ISSUE TITLE
Implement the rest of the `Debug` stream events as applicable

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/webdev#166]
All the events include:

- [ ] PauseStart (isolate pauses on startup)
- [ ] PauseExit (isolate paused on exit)
- [x] PauseBreakpoint
- [x] PauseInterrupted (partially done, but no breakpoint set)
- [x] PauseException
- [ ] PausePostRequest (pause after a service request)
- [x] Resume
- [x] BreakpointAdded
- [ ] BreakpointResolved
- [x] BreakpointRemoved
- [ ] Inspect
- [ ] None (likely not applicable)

**Comment by alan-knight** [comment]
See also #352

**Comment by grouma** [comment]
What does `PauseExit` look like for the web?

**Comment by alan-knight** [comment]
Maybe that the page is about to close? Or that we're running off the end of main and there are no pending futures? Not sure how well we can detect that.

**Comment by grouma** [comment]
Closing this one. Most of these have been resolved. We can open specific bugs for stream events that we need.
