### ISSUE TITLE
webdev freezes the OS and makes it unresponsive

### ISSUE THREAD

**Issue by tejainece** [dart-lang/webdev#170]
Running `webdev` on my project freezes and renders my desktop unresponsive. I am forced to the restart the computer. I am not sure if it is CPU time, memory usage or io usage that is crashing the desktop. I would guess CPU usage. However, running it using `cpulimit` did not help.

I am using version `1.0.0`.

This issue also seems to be relevant: https://github.com/dart-lang/angular/issues/1704

**Comment by jakemac53** [comment]
You can try running with `--low-resources-mode` and see if that helps. If you have a really large single application package then the structure of the package also affects build performance a lot.

Essentially, if all your files are public (under `lib` but not `lib/src`) or visa-versa, then you will get pathological behavior (very small modules which is inefficient).

We use public dart files as a signal for creating modules, essentially we try to create as large of modules as possible while satisfying the constraint that importing a public file won't cause you to load any code that wasn't imported by that file.

**Comment by jakemac53** [comment]
You can also break your package up into smaller packages which follow pub package conventions (a few public entrypoints, most files under lib/src), and things will generally "just work".

**Comment by tejainece** [comment]
@jakemac53 Thanks! I don't use `lib/src` at the moment and put all sub-directories directly under `lib`. I will fix this and check if it improves things.

Also, thanks for heads up on `--low-resources-mode`.

**Comment by tejainece** [comment]
@jakemac53 The improvements you suggested seems to have helped a lot for now. I am closing this issue.

**Comment by jakemac53** [comment]
Glad you got things working better. In the future we can try and detect these sorts of situations and do something a bit better or at least warn the user about it more pro-actively. It usually doesn't matter until  your application reaches a certain (fairly large) size so it hasn't been much of an issue yet.

We could also provide a way of creating a totally custom module structure which might work out better but would also be a bit of a pain to maintain - you can't have cycles between modules but you can between dart libraries, so custom module structures are probably difficult to maintain.

**Comment by tejainece** [comment]
@jakemac53 Warning with information about `src` directory and `--low-resources-mode` would be very helpful.

> We could also provide a way of creating a totally custom module structure which might work out better but would also be a bit of a pain to maintain - you can't have cycles between modules but you can between dart libraries, so custom module structures are probably difficult to maintain.

I don't see any problem with the current settings really. `--low-resources-mode` runs smoothly and atleast for my project i did not notice any substantial slowing down.

Thanks again!

**Comment by supermuka** [comment]
@tejainece, thanks if you can share your recent experience to solve problems related to CPU usage when running `webdev` for now. The `--low-resources-mode` parameter no longer exists in the current version and in my project I have tried to structure the folders within the suggested conventions (`lib` which is used by several packages, and `lib/src` for specific packages/components).

Still, the CPU usage is very something. I'm using Windows 10.

**Comment by natebosch** [comment]
@supermuka - to use `--low-resources-mode` with `webdev` use an extra `--` to separate out the directly forwarded arguments.

`webdev serve -- --low-resources-mode`

**Comment by jakemac53** [comment]
Note that this is most likely due to the file watcher though, see https://github.com/dart-lang/webdev/issues/436 and the linked sdk issue.

**Comment by tejainece** [comment]
@supermuka `--low-resources-mode` helps. Without it, my computer hangs. Even with `--low-resources-mode`, it is slightly resource hungry.

@jakemac53 Its not just file watcher. It hangs when I do `pub get` in pre-compilation stage too. It also hangs on `pub run build_runner build web`, etc.

**Comment by jakemac53** [comment]
If you are having issues during `pub get` pre-compilation there likely isn't anything we can do here. We are effectively doing that same type of work just differently.
