### ISSUE TITLE
Add support for hot reloading while maintaining the application state.

### ISSUE THREAD

**Issue by Hawmex** [dart-lang/webdev#1748]
Currently, `webdev` supports hot restart. But developing in this mode gets difficult as applications grow. It would be nice to see hot reloading without losing state added as a feature.

**Comment by annagrin** [comment]
Thank you @Hawmex for the feature suggestion. 

Note that dwds is just a proxy between the UI and Chrome that pretends to be a VM. As a result, we do not have access to the heap, which is what the real VM needs to implement stateful hot reload. 

As a result, supporting hot reload actually needs to be done in the dev compiler (dwds and webdev would only need minor modifications after, if any):

https://github.com/dart-lang/sdk/issues/46958

Please note that this is a big feature and will take time to design and implement. We are not sure at this time that a reasonable implementation is possible.  We don't have it currently planned, but are thinking about investigating it in the future.

Also, please see the conversation in flutter request for the same feature:
https://github.com/flutter/flutter/issues/53041

**Comment by bkonyi** [comment]
Closed in favor of https://github.com/dart-lang/webdev/issues/2516
