### ISSUE TITLE
Publish frontend_server_client 3.1.0

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/webdev#1762]
`frontend_server_client/pubspec.yaml` contains a dependency override

```
dependency_overrides:
  # Necessary to get a version solve until test_core allows version 3.x of
  # this package
  test_core: ^0.4.13
```

Added in:

* https://github.com/dart-lang/webdev/pull/1641

Causing pub to complain on trying to publish.

```
Package validation found the following potential issue:
* Your pubspec.yaml is overriding non-dev dependencies.
  
  This indicates you are not testing your package against the same versions of its
  dependencies that users will have when they use it.
  
  This might be necessary for packages with cyclic dependencies.
  
  Please be extra careful when publishing.
```

This override was in the pubspec when 3.0.0 was published.

* https://github.com/dart-lang/webdev/pull/1721

However, when downloading the sources for 3.0.0 from pub the dependency override is not in the pubspec.

@jakemac53 did you remove the dependency override before publishing 3.0.0? Should we do the same for 3.1.0?

**Comment by jakemac53** [comment]
Yes, it used to be required that you remove it by hand (it was the only way to publish, and it's only a dev dependency so it is ~harmless to do so). I think pub allows you to just bypass this check now and publish anyways though, so if it will let you publish with it still in that is ideal.

**Comment by jakemac53** [comment]
Side note but the dependency override is likely not required any longer? I believe that package:test has updated to version 3.0.0 now which fixes the issue.
