### ISSUE TITLE
[DWDS] pass app name when communicating to chrome

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1765]
Parent: https://github.com/dart-lang/webdev/issues/1769

DWDS communications with chrome frequently load libraries, evaluate expressions in them, etc. 
To support multi-app scenario, DWDS always needs to know the app name it need to pass to the library loader functions. 

- pass the app name to the library loading functions
- add app name to objects returned the vm_service
- add app names to object IDs

**Comment by bkonyi** [comment]
This work has been deprioritized, so I'm going to close this for now.
