### ISSUE TITLE
[DWDS] Allow mapping one app to one isolate in multi-app scenarios

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1766]
For smooth Dart DevTools experience, we might need to represent an app in multi-app setup as an isolate.
Add a mode to DWDS to represent app as an isolate if requested.

**Comment by Abhi149209** [comment]
@annagrin please elabotate the issue .

**Comment by annagrin** [comment]
@Abhi149209 sorry I missed your question. The issue is a part of a bigger feature (see parent issue https://github.com/dart-lang/webdev/issues/1769), which is not a top priority at the moment, thought that might change in the future.
