### ISSUE TITLE
Support debugging for multi-app scenario in the browser

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1769]
This is a parent issue for debugging support for multiple apps loaded on the same browser page.

Design and prototype:
  - [Create multi-app design document](https://github.com/dart-lang/webdev/issues/1705)
  - [Create prototype for debugging the whole app solution](https://github.com/dart-lang/webdev/issues/1706)

Implementation:
  - [[DDC] Pass app name to dart_library.import in during expression evaluation](https://github.com/dart-lang/sdk/issues/50296)
  - [[SDK] pass app name to emitDebugEvent in developer.postEvent](https://github.com/dart-lang/sdk/issues/50298)
  - [[dart_library.js] pass app name to module loader function](https://github.com/dart-lang/sdk/issues/50297)
  - [[DWDS] Allow multi-app connections](https://github.com/dart-lang/webdev/issues/1764)
  - [[DWDS] pass app name when communicating to chrome](https://github.com/dart-lang/webdev/issues/1765)
  - Roll and connect DWDS to all debugger launchers (Flutter tools, IntelliJ, internal tools)
     TODO: add issues
 
Cleanup:
  - [Make expression evaluation interface less fragile for multi apps](https://github.com/dart-lang/sdk/issues/50299)

Additional features:
 - [[DWDS] Allow mapping one app to one isolate in multi-app scenarios](https://github.com/dart-lang/webdev/issues/1766)

**Comment by bkonyi** [comment]
This work has been deprioritized, so I'm going to close this for now.
