### ISSUE TITLE
Call stack tests break if `main.dart` in `fixtures/_testPackageSound` / `fixtures/_testPackage` is formatted

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#1831]
We should fix the tests so that they pass when the file is formatted.

**Comment by jyameo** [comment]
Formatting `fixtures/_testPackageSound/web/main.dart` doesn't seem to cause any breakage. I've verified that no changes occur after applying `dart format`, so I'll go ahead and close this issue.
