### ISSUE TITLE
Tests with long timeouts should be moved to a cron job 

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#1846]
We have a few tests with timeouts of 5 minutes, e.g. the `devtools_test`. This test has recently been flaking, because it times out after 5 minutes, eg: https://github.com/dart-lang/webdev/actions/runs/3743002547/jobs/6354677288

I think it would be best to move these long running tests into a separate cron job, to improve the velocity of Github CI testing.

**Comment by elliette** [comment]
Related: https://github.com/dart-lang/webdev/issues/1847

**Comment by bkonyi** [comment]
@elliette has made other improvements to reduce the amount of time needed to run testing (e.g., sharding), so this isn't as relevant anymore.
