### ISSUE TITLE
Dwds crashes on unintialized DwdsStats._devToolsStart 

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1874]
Repro:

- run `flutter run -d chrome`
- copy and paste the DevTools uri into a browser
- dwds throws an exception while processing `DevtoolsEvent` event sent from the Flutter Inspector panel.

**Comment by elliette** [comment]
@bkonyi for context 

When I run an app with `flutter run -d chrome` and open the observatory url in a Chrome window (see below) I see the following: 

`Cannot connect directly to the VM service as a Dart Development Service (DDS) instance has taken control and can be found at http://127.0.0.1:51403/8Muq67PEPQo=/.`

For Anna, that URL opens Flutter DevTools and the running Flutter app crashes. 

Is that URL supposed to open DevTools?

```
Changed 4 dependencies!
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             18.7s
This app is linked to the debug service: ws://127.0.0.1:50799/n51gpz9oSlU=/ws
Debug service listening on ws://127.0.0.1:50799/n51gpz9oSlU=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
```

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:50799/n51gpz9oSlU= <---- THIS ONE
The Flutter DevTools debugger and profiler on Chrome is available at: [http://127.0.0.1:9102?uri=http://127.0.0.1:50799/n51gpz9oSlU=](http://127.0.0.1:9102/?uri=http://127.0.0.1:50799/n51gpz9oSlU=)

**Comment by bkonyi** [comment]
The Observatory URI is actually the DDS URI and shouldn't be serving any assets for the web. That verbage needs to be updated to `A Dart VM service is available at:`.

**Comment by annagrin** [comment]
Ok i was able to connect a devtools to it so it is indeed a DDS uri. The message needs to be corrected though.
