### ISSUE TITLE
Remove weak null safety tests when we no longer support weak null safety

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1899]
Remove weak null safety tests when we no longer support weak null safety:

- Remove all tests fixtures for weak null safety.
- Remove `TestContext.withWeakNullSafety`, related code, and the tests that use the weak mode.
- Remove weak-null-safety-related paths from the `SdkLayout` and `SdkConfiguration`
- Remove generating unsafe assets from the `SdkAssetGenerator`.
- Remove testing for SDK version `3.0.0-134.0.dev` to determine the SDK layout (and support for the old layout) after stable dart SDK version is >=3.0.

**Comment by bkonyi** [comment]
Closing in favor of https://github.com/dart-lang/webdev/issues/2427.
