### ISSUE TITLE
Webdev tests breakages on `main` Dart SDK branch

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#1922]
- See test failures in https://github.com/dart-lang/webdev/pull/1920

These were passing on `3.0.0-edge.f6d41b95fbe902b38e2aeb886e485e42bea986a8`, began failing with `3.0.0-edge.0a60ff13e2f8856972d3cd0c7e9e8fb789c0f104`. Chatted with @nshahan  offline, most likely cause is  https://github.com/dart-lang/sdk/commit/d56b9b3988e74fe4e3b4a0adfa6ed2cc79caddf4 which matches with the failure timeline. 

@annagrin It seems like we might have missed generating a `.dill` file for some of the tests.

**Comment by elliette** [comment]
Actually issue is same as https://github.com/dart-lang/webdev/issues/1878, can't run webdev tests with unsound null-safety currently

**Comment by annagrin** [comment]
This should be fixed in https://github.com/dart-lang/webdev/pull/1960
