### ISSUE TITLE
Update dwds for new DDC type system

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1949]
New type system tracking issue: https://github.com/dart-lang/sdk/issues/48585

We use old logic in many places in dwds, for example, for determining the object's runtime kind here: https://github.com/dart-lang/webdev/blob/47287e340436211f8dd5cd6230258af2bcbd1458/dwds/lib/src/debugging/metadata/class.dart#L71

The logic will break with the new types system. Make sure that dwds can handle both cases (and roll internally) before flipping the flag that enables new type system in ddc.

Work tracking:

**SDK**
 - [x] Add `--canary` flag to  frontend server
   - https://github.com/dart-lang/sdk/issues/52774
   - https://dart-review.googlesource.com/c/sdk/+/311149
 - [x] Add `--canary` flag to  expression compiler worker
   - https://github.com/dart-lang/sdk/issues/52776
   - https://dart-review.googlesource.com/c/sdk/+/311151
 - [x] Create runtime debugger API in DDC to support both old and new type systems
    - https://github.com/dart-lang/sdk/issues/52773
    - https://dart-review.googlesource.com/c/sdk/+/311154
 - [x] Run canary expression evaluation tests on canary bots
    - https://github.com/dart-lang/sdk/issues/53077
    - https://dart-review.googlesource.com/c/sdk/+/317448
 - [ ] Run canary expression compiler tests on canary bots
    - https://github.com/dart-lang/sdk/issues/53145
    - https://dart-review.googlesource.com/c/sdk/+/318080

**build_web_compilers**
 - [x] Allow passing `--canary` flag to ddc
    - https://github.com/dart-lang/build/issues/3535
    - https://github.com/dart-lang/build/pull/3536
  
**DWDS**
 - [x]  Support running tests with `--canary` flag
   - for frontend server
      - https://github.com/dart-lang/webdev/issues/2155
      - https://github.com/dart-lang/webdev/pull/2169
   - for build daemon and expression compiler service
      - https://github.com/dart-lang/webdev/issues/2156
      - https://github.com/dart-lang/webdev/pull/2171
 - [x]  Run `instance/instance_test.dart` in frontend server compilation mode (currently only runs with build daemon)
     - https://github.com/dart-lang/webdev/issues/2158
     - https://github.com/dart-lang/webdev/pull/2160
 - [x] Prepare to run all instance tests with `--canary` flag
     - https://github.com/dart-lang/webdev/issues/2175
     - https://github.com/dart-lang/webdev/pull/2174
     - https://github.com/dart-lang/webdev/pull/2176
 - [x] Update dwds to use new debugging API, run all instance tests with `--canary` flag
   - https://github.com/dart-lang/webdev/issues/2157
   - https://github.com/dart-lang/webdev/pull/2159

**Comment by annagrin** [comment]
@nshahan this should be blocking flipping the new type system flag in ddc.
@elliette FYI

**Comment by bkonyi** [comment]
It looks like all referenced issues here are closed, so I'm just going to close this.
