### ISSUE TITLE
Debugging experience for patterns needs a cleanup

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1974]
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/12737689/219825647-9b990b32-ede1-4eb5-9a8e-938bce861107.png">

- Stepping into the statement on the breakpoint line seems to stuck forever on the same spot 
  - I suppose it goes through all ddc statements the patterns has been translated to
  - Can we remove unnecessary locations in source maps?

- Compiler-generated locals appear in the variables window

**Comment by nshahan** [comment]
@bkonyi Are there any expectations for how stepping through patterns like this works when debugging on the VM?

**Comment by bkonyi** [comment]
I'm not sure what the behavior will be like as it depends on where we insert breakpoints into generated code. Maybe @alexmarkov will have a better idea or know who will?

**Comment by alexmarkov** [comment]
Debugger behavior depends on how patterns are lowered in the front-end and how source positions are assigned to the AST nodes.

However, VM has a logic to avoid stopping at the same position repeatedly:

https://github.com/dart-lang/sdk/blob/b8dc6762921aa2fd3ef3c7415d3d7f946ee6f21b/runtime/vm/debugger.cc#L3809-L3814

So even if there are many AST nodes with the same source position, VM would stop at the first one and then skip the rest of the stops, until the source position changes.

**Comment by nshahan** [comment]
Looking at the screenshot, there are a few initial questions that come to my mind. 

- If you set a breakpoint and pause on line 15 then step where would you expect the next pause to be? 
- If you set a breakpoint on line 16 and the debugger pauses there do we expect the evaluation to be paused before the `when`?
- Is there any point that you can hover over variables in the patterns like `[var a, int n]`to see values?

I don't expect these all to be answered already but I'd like to get the discussion started and I'm not sure who should be involved.

**Comment by annagrin** [comment]
I am going to split this into a few things:

- (DDC) do not show temp variables generated by CFE
- (DDC, or maybe dwds?) minimize the number of debugger steps through CFE code
- (dwds, DevTools, dart-code?) cleanup hover over and evaluation behavior

**Comment by annagrin** [comment]
All done!
