### ISSUE TITLE
Allow specifying port number

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/webdev#198]
I routinely run multiple local servers at the same time, e.g. when I need to compare the behavior between multiple versions of the same app. However, `webdev` only supports port 8080 and complains when it's already in use:

```
[SEVERE] Error starting server at 127.0.0.1:8080, address is already in use. Please kill the server running on that port or serve on a different port and restart this process.
```

**Comment by jakemac53** [comment]
It does actually support this, but the syntax is a bit weird because you have to choose a different port per top level directory, so there isn't a `--port` argument.

Instead, you can add `:<port>` after the top level directory you are serving, so `webdev serve web` would become `webdev serve web:8082` or whatever port you want.

**Comment by yjbanov** [comment]
Ah, didn't even occur to me to look there :)

The following worked, but looks weird to my untrained eyes: `webdev serve .:8080`

**Comment by jakemac53** [comment]
huh.. we shouldn't be allowing you to serve the top level dir like that, I am not sure what the behavior actually is there haha

**Comment by yjbanov** [comment]
Wait, which directory am I supposed to point it to? I'm at the root of a pub package.

**Comment by jakemac53** [comment]
`web`, `test`, `example`, wherever your app entrypoint is

dart4web only supports serving top level directories in your package, and it serves them as the root, so you don't need to include `web` or `test` in your uri, as well as to prevent you from loading resources from other top level directories in an attempt to enforce package layout conventions

**Comment by pahosler** [comment]
vscode's debug will give you a random port

**Comment by pouledodue** [comment]
@pahosler do you know how to specify the port in vscode config?

**Comment by DanTup** [comment]
It's not possible to specify a specific port when launching from VS Code yet. I've opened https://github.com/dart-lang/webdev/issues/424 for extending the daemon to support it, and I have https://github.com/Dart-Code/Dart-Code/issues/1769 for implementing it once that's supported.
