### ISSUE TITLE
File open when the debugger opens feels random and confusing

### ISSUE THREAD

**Issue by nshahan** [dart-lang/webdev#2010]
When you open the debugger for the first time a file is open in the source view pane. How is this file selected?

It always feels like a completely random file out of the thousands that make up a large application. I usually find it distracting since it typically has nothing to do with the reason why I came to DevTools in the first place but it seems to be highlighted since it is appearing in the largest portion of the UI for some reason.

Looking at the same scenario in Chrome DevTools you get something like this:

<img width="942" alt="Screenshot 2023-03-01 at 2 25 05 PM" src="https://user-images.githubusercontent.com/2498387/222279322-22ddb066-ccb4-4105-9cbb-830a968656d8.png">

This feels more intuitive to me because it is guiding me what action to take next.

I think we could do even better by showing the hotkeys tip to open a file and also make the tip clickable to perform the same operation as the hotkey.

**Comment by elliette** [comment]
Closing in favor of https://github.com/flutter/devtools/issues/5350
