### ISSUE TITLE
Handle page refreshes better with devtools open

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/webdev#202]
If you refresh the page with devtools open, then devtools no longer works. Worse, refreshing the page doesn't fix it, because the debug service is no longer running at all, and even when it does start up it will choose a different port.

A full page refresh can happen after initiating a hot restart (if the module structure changes), so its possible that just clicking hot restart in the devtools UI will cause this behavior.

I think the ideal scenario here would be to:

- only shut down the dwds service if all clients disconnect, so if devtools is still open it will remain open
- watch for refresh events and fire an IsolateExit event on the Isolate stream.
  - also the `isolate` field should be set to null, which means it needs to be mutable and will cause some refactoring
- when an SSE connection opens, we should check if we already have a dwds instance for that application and create a new isolate for the page right away, instead of waiting for an alt+d.
  - this should also fire IsolateStart (and probably IsolateRunnable) events.

There is one edge case here which happens if you open up the same app in multiple tabs. We can recognize this if when starting the SSE connection we find an existing dwds instance that already has a valid isolate. We could just throw an unsupported error for now in that case, essentially that means you can only debug one version of the same app at a time.

**Comment by jakemac53** [comment]
cc @grouma

**Comment by jakemac53** [comment]
To start this off I am going to start a bit of the isolate refactoring so that we create new isolates and fire the correct events for a **hot restart**, since this should be modeled that way too (even if it doesn't require a full page refresh).

**Comment by grouma** [comment]
Discussed offline.

As a part of this work we will make edits to build_web_compilers:

- Add an extra hook to build_web_compilers right before the main is called
- Update the injected client to include an application ID and move it to the new hook
- When the application connects through SSE, we will send the application ID (embedded by WebDev) back down to the server
- When `--debug` is used we will automatically make the debug connection and ALT+D will now just launch DevTools
