### ISSUE TITLE
`integration_test` failing on Dart SDK main due to recent pub changes

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2050]
Some of the webdev `integration_test` cases are failing on the `main` branch of the Dart SDK, most likely due to https://github.com/dart-lang/pub/pull/3844

These test cases seem to actually be testing pub validation, and string matching against the validation messages generated by pub. I don't think this is useful for us to test. We probably want to change the `integration_test` to actually test the validation that we control.

**Comment by bkonyi** [comment]
Is this still relevant @elliette?
