### ISSUE TITLE
Support VM Service API methods used by DevTools performance panel 

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2110]
Those include: 

`getVMTimelineMicros`
`getVMTimeline`
`setVMTimelineFlags`

Also need to investigate whether or not the performance panel is even useful with DDC. DWDS does not work with dart2js, so more work would be needed to support connecting to an app running in release-mode. 

See https://github.com/flutter/devtools/issues/4652 for more details

**Comment by bkonyi** [comment]
Closing this as we're making use of performance tooling in Chrome DevTools instead.
