### ISSUE TITLE
Remove uses of .__proto__ from JS code 

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#2118]
We currently have a case where we call `__proto__` to determine if the object is  a plain JS object:

Use of `__proto__ should be replaced by `Object.getPrototypeOf(#)`. Or maybe we can use the object runtime metadata to determine its type?

See more information in https://github.com/dart-lang/sdk/issues/52372

https://github.com/dart-lang/webdev/blob/2b2ae0e833c66a5756aba64a4a5d2bbdfbd4ec76/dwds/lib/src/debugging/inspector.dart#L219

**Comment by jyameo** [comment]
Is this a duplicate issue of https://github.com/dart-lang/sdk/issues/52372? Looks like the issue has already been closed.

**Comment by bkonyi** [comment]
I don't think so. There's still references to `this.__proto__` in DWDS.
