### ISSUE TITLE
Trying to resume an isolate that is not paused throws the wrong error code

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#2133]
In Flutter we're seeing some crash reports with this error:

```
RPCError: resume: (-32603) resume: WipError -32000 Can only perform operation while paused.
at new _OutstandingRequest(vm_service.dart:1865)
at VmService._call(vm_service.dart:2417)
at VmService.resume(vm_service.dart:2292)
at IsolateManager.resumeThread(isolate_manager.dart:288)
at IsolateManager._handlePause(isolate_manager.dart:502)
at IsolateManager.handleEvent(isolate_manager.dart:178)
at <asynchronous gap>(async)
at DartDebugAdapter._configureExistingIsolates.<anonymous closure>(dart.dart:759)
```

This happens when we try to unpause an "isolate" that's already running. I don't know the cause of this (but suspect it may be when multiple debuggers are involved, and might both be trying to resume pause isolates when they start/restart/etc.) but for the VM (where we've seen similar issues) we handle the error with code [`kIsolateMustBePaused`](https://github.com/dart-lang/sdk/blob/80a9e513a7f3e553d19feca570d12ee8a1536ce6/pkg/dds/lib/src/rpc_error_codes.dart#L34).

For compatibility, I think DWDS should throw the same kind of error (perhaps by catching this one and mapping it) so that the same client handling works without needing to do string checks on the error text.

**Comment by elliette** [comment]
Some notes:

- Opened from https://github.com/Dart-Code/Dart-Code/issues/4543
- The RPC error codes should be exposed by the `vm_service` so that they can be used in DWDS: https://github.com/dart-lang/sdk/issues/52636
