### ISSUE TITLE
google3 updates needed for the next roll of this repo

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#2172]
We'll need some google3 updates when we next roll this repo internally; there are some implementations of AssetReader that will need to be updated.

```
ERROR: dart/.../lib/src/core/features/dwds/asset_reader.dart

5: class BoltAssetReader implements AssetReader { Missing concrete implementation of 'getter AssetReader.basePath'.
                                                  #non_abstract_class_inherits_abstract_member
```

https://github.com/dart-lang/webdev/commit/cbb0d76acc24daab15e1af9cd4cd2dd7cf2ac70b#r121214154

**Comment by elliette** [comment]
Thanks! Yes we will need to add this getter to the `BoltAssetReader`:

```
 @override
  String get basePath => '';
```

**Comment by elliette** [comment]
DWDS has been updated in Google3, therefore closing
