### ISSUE TITLE
`events_test.dart` is flaky

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2181]
See: https://github.com/dart-lang/webdev/actions/runs/5752276393/job/15593002960

**Comment by bkonyi** [comment]
This test likely started failing when DevTools started displaying the home page instead of the debugger page by default. We should probably be looking for different events that reference the home page being opened instead.

**Comment by jyameo** [comment]
Related issue with more details: #2394

**Comment by jyameo** [comment]
Will close this as this issue is being tracked in https://github.com/dart-lang/webdev/issues/2394
