### ISSUE TITLE
Getters should be marked with isGetter when fetching class definitions with getObject()

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#2184]
https://github.com/dart-lang/sdk/issues/52920 added a new `isGetter` field to members returned in class definitions via `getObject()`, but it's not currently populated by DWDS:

```js
{
	"type": "@Function",
	"id": "methods|classes|package:flutter_hello_world/getters.dart|Danny|kind",
	"name": "kind",
	"owner": {
		"type": "@Class",
		"id": "classes|package:flutter_hello_world/getters.dart|Danny",
		"name": "Danny",
		"library": {
			"type": "@Library",
			"id": "package:flutter_hello_world/getters.dart",
			"name": "package:flutter_hello_world/getters.dart",
			"uri": "package:flutter_hello_world/getters.dart"
		}
	},
	"static": false,
	"const": false,
	"implicit": false,
	"abstract": false,
	"isGetter": false, // <-- expected to be true
	"isSetter": false
},
```

DAP isn't using `isGetter` yet (it currently checks `f.json?['_kind'] == 'GetterFunction` which also isn't true here), but I'm going to switch it over to that shortly.

**Comment by annagrin** [comment]
@DanTup this should be now resolved with https://github.com/dart-lang/webdev/pull/2159. Please let me know if it still not showing as expected.

**Comment by DanTup** [comment]
Sorry for the delay - yes, I can see `isGetter` populated now. Thanks! :-)
