### ISSUE TITLE
Safari Throws FormatException for Local Development URLs

### ISSUE THREAD

**Issue by ShamanJaggia** [dart-lang/webdev#2204]
Environment:

Dart SDK Version: 3.1.0
Webdev Version: 3.0.7
Browser: Safari (Version 16.5 (18615.2.9.11.4))
Issue Description:

When running a Dart web app locally on Safari, I encounter a FormatException related to the URL @http://localhost:8080/main.dart.bootstrap.js. The error message indicates:

[INFO] Reading cached asset graph completed, took 108ms
[INFO] Checking for updates since last build completed, took 407ms
[INFO] Serving `web` on http://127.0.0.1:8080
[INFO] Running build completed, took 71ms
[INFO] Caching finalized dependency graph completed, took 83ms
[INFO] Succeeded after 157ms with 0 outputs (0 actions)
[INFO] ------------------------------------------------------------------------------------
ERROR - 2023-08-30 11:28:46.477337
GET /@http://127.0.0.1:8080/main.dart.bootstrap.js
Error thrown by handler.
FormatException: Scheme not starting with alphabetic character (at character 1)
@http://127.0.0.1:8080/main.dart.bootstrap.js
^

dart:core                                          _SimpleUri.resolve
package:shelf_proxy/shelf_proxy.dart 42:28         proxyHandler.<fn>
package:shelf/src/cascade.dart 77:53               Cascade.handler.<fn>.<fn>
===== asynchronous gap ===========================
package:shelf/shelf_io.dart 91:9                   serveRequests.<fn>.<fn>
===== asynchronous gap ===========================
package:shelf/shelf_io.dart 89:3                   serveRequests
package:webdev/src/util.dart 22:5                  serveHttpRequests.<fn>
package:stack_trace                                Chain.capture
package:webdev/src/util.dart 21:16                 serveHttpRequests
package:webdev/src/serve/webdev_server.dart 192:5  WebDevServer.start

This issue doesn't occur on other browsers like Chrome, and the web app runs as expected there.

Steps to Reproduce:

Run Dart bare bones web app and use webdev serve.
open loclhost:8080 or 127.0.0.1:8080 on safari.
Observe the mentioned FormatException.
Additional Notes:

Clearing Safari's cache didn't resolve the issue.
The problem persists even when using the IP 127.0.0.1 directly instead of localhost.
No specific reference to the URL @http://localhost:8080/main.dart.bootstrap.js is found in the code or build output.
Any assistance on this would be greatly appreciated.

**Comment by elliette** [comment]
Thank you for the report! I'm able to reproduce. I see a related error:

```
[Error] Refused to execute http://127.0.0.1:8080/@http://127.0.0.1:8080/main.dart.bootstrap.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
Error: Script error for "main.dart.bootstrap"
```

**Comment by elliette** [comment]
Did some debugging of this issue:

It looks like the invalid URI is being generated by a combination of `build_web_compilers` and `ddc`. 

It's being created in the `main.dart.js` file, by prefixing the bootstrap module (in this case `"main.dart.bootstrap"`) with the `currentDirectory` (in this case `"@http://127.0.0.1:8080"`)

Here is where the URI is being constructed: https://github.com/dart-lang/build/blob/292a62348cb1f69b062f3846a8c3587fbb5e36dc/build_web_compilers/lib/src/dev_compiler_bootstrap.dart#L250

Here is where the current directory is being constructed: https://github.com/dart-lang/build/blob/292a62348cb1f69b062f3846a8c3587fbb5e36dc/build_web_compilers/lib/src/dev_compiler_bootstrap.dart#L277-L306

See screenshot:

<img width="1299" alt="Screenshot 2023-09-20 at 2 15 44 PM" src="https://github.com/dart-lang/webdev/assets/21270878/b81e84a9-89e6-4623-8da1-924c490d7453">

@annagrin @jakemac53 Could one of you take a look? Thanks!

**Comment by elliette** [comment]
Thanks for the report! Unfortunately we only support Chrome development workflows for WebDev. 

However, if you would like to be able to develop in Safari, feel free to open up a PR. I believe this line would need to be updated: https://github.com/dart-lang/build/blob/292a62348cb1f69b062f3846a8c3587fbb5e36dc/build_web_compilers/lib/src/dev_compiler_bootstrap.dart#L298
