### ISSUE TITLE
Global stylesheet breaks rendering of web pages

### ISSUE THREAD

**Issue by macjohnny** [dart-lang/webdev#2278]
# Problem
The [global stylesheet](https://github.com/dart-lang/webdev/blob/5ad79c240b000a50057612d6af4573f6e649f65c/dwds/debug_extension_mv3/web/static_assets/styles.css#L5) that is injected in https://github.com/dart-lang/webdev/blob/5ad79c240b000a50057612d6af4573f6e649f65c/dwds/debug_extension_mv3/web/manifest_mv3.json#L35 causes websites to render incorrectly, e.g. iframes are changed:

<img width="316" alt="Screenshot 2023-11-01 at 11 13 11" src="https://github.com/dart-lang/webdev/assets/5589029/25b0e29a-d77b-488f-bcf1-d118dceb2d01">

# Workaround
Disabling the extension

# Bug introduced
in https://github.com/dart-lang/webdev/pull/2271/files#diff-3dcc6c849a8a2bc972c0d3b2890bfc4047a131fc4430bfef95c2e5b76d667699

# Other references
the issue is also noticed in the [reviews](https://chromewebstore.google.com/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm):

<img width="1158" alt="Screenshot 2023-11-01 at 11 48 19" src="https://github.com/dart-lang/webdev/assets/5589029/4d39dc40-0f8b-4e5f-9cd1-527819898b9c">

**Comment by mihalycsaba** [comment]
I think this is what causing my issue too on steamgifts.com, the ads on the page appear above other elements in the wrong position, disabling the extension solves the problem.
![Screenshot 2023-11-01 153755](https://github.com/dart-lang/webdev/assets/50019470/2f8de615-affb-45e2-a310-ac05e45841a4)

**Comment by elliette** [comment]
Sorry for this! The rolled-back extension has been submitted to the Chrome web store. It usually takes a couple hours from submission for it to be published. For now, you can disable or remove the extension from chrome://extensions. I will report back here when the new version has been published.

**Comment by alanknight-wk** [comment]
Breaks JIRA too, though that might be regarded as a feature.

**Comment by elliette** [comment]
Version 1.39.0 (the rollback version) was just published to the Chrome Web Store. Re-installing the extension from https://chromewebstore.google.com/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm should resolve any rendering issues. 

My apologies for all the confusion this has caused!
