### ISSUE TITLE
Errors from the `BatchedExpressionEvaluator` on object inspection

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2309]
See for example inspecting a `Record` on chrome:

![Screenshot 2023-12-18 at 2 11 21 PM](https://github.com/dart-lang/webdev/assets/21270878/6c31fe80-b235-4fa5-8fd3-f98f89505523)

versus on macos:

![Screenshot 2023-12-18 at 2 13 21 PM](https://github.com/dart-lang/webdev/assets/21270878/f5dd9dba-b8ab-40e4-b004-258db1c8fb94)

This is because the library (and therefore the library URI) for the `evaluate` request is `null`: https://github.com/dart-lang/webdev/blob/7543345873b4ea4457a584a86677b38755001d9d/dwds/lib/src/services/chrome_proxy_service.dart#L626

FYI @annagrin

**Comment by elliette** [comment]
I did some looking into this. There are a few things we can do to improve this:

- https://github.com/dart-lang/webdev/issues/2336
- https://github.com/dart-lang/webdev/issues/2337

**Comment by annagrin** [comment]
AFAIK there should be no evaluate() calls here - how is the example debugged? Are the images from vscode or devtools?

**Comment by annagrin** [comment]
Here is what I see in VSCode, for example:

<img width="1088" alt="image" src="https://github.com/dart-lang/webdev/assets/12737689/88d247fd-d4a7-4566-a02e-c2070bd5cc63">

**Comment by annagrin** [comment]
And devtools:

<img width="1171" alt="image" src="https://github.com/dart-lang/webdev/assets/12737689/e6bc338f-6bd1-4738-b83e-2cf484b6fd1c">

**Comment by annagrin** [comment]
I suspect some different logic is used here then we do normally - it would be useful to understand where the evaluate is called from and with with what arguments (might be just not a correct usage of evaluate or a bug in dwds)

**Comment by elliette** [comment]
@annagrin figured out what the difference was (why she couldn't initially reproduce whereas I could). She had:

```
"dart.previewSdkDaps": false
```

@DanTup - what is the rollout status for the new DAPs?
https://github.com/Dart-Code/Dart-Code/blob/b939d2c45adf2638eac672095c7ac8ed390cffbc/package.json#L2663

**Comment by DanTup** [comment]
We're at 100% using SDK DAPs for both Dart and Flutter now:

https://github.com/Dart-Code/Dart-Code/blob/b939d2c45adf2638eac672095c7ac8ed390cffbc/src/extension/experiments.ts#L20-L21

The `dart.previewSdkDaps` setting will soon be renamed and inverted (to become something like `dart.useLegacyDebugAdapters`) and I would not recommend anyone has it set to `false`.

(If you think there are bugs in the SDK DAPs that aren't in the legacy DAPs, please let me know)

**Comment by annagrin** [comment]
I found what is going on - we never supported `evaluate()` calls on targets other than a library. Looks like DAP sends evaluate requests on getting variables. Will send a PR to fix!

**Comment by annagrin** [comment]
Depends on: https://github.com/dart-lang/sdk/issues/54609

**Comment by elliette** [comment]
One note - this is affecting more than just `Records`. For example, here is what I see when inspecting a Flutter widget's state:

![Screenshot 2024-01-12 at 9 56 49 AM](https://github.com/dart-lang/webdev/assets/21270878/98151c65-ab3d-48f4-88ad-16cda0781f6a)

**Comment by annagrin** [comment]
> One note - this is affecting more than just Records

Yes, I could fix the original bug but the records still are not displaying correctly due to that additional SDK issue:)

**Comment by annagrin** [comment]
Depends on: https://github.com/dart-lang/sdk/issues/54694
