### ISSUE TITLE
Frontend server client tests are failing with most recent Dart SDK

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2315]
See: https://github.com/dart-lang/webdev/actions/runs/7281930354/job/19843422857?pr=2312

**Comment by derekxu16** [comment]
I've managed to reproduce this locally. The `Bad state: No elements` error gets thrown when trying to [`await stdoutLines.next`](https://github.com/dart-lang/webdev/blob/7543345873b4ea4457a584a86677b38755001d9d/frontend_server_client/test/frontend_sever_client_test.dart#L88) when [the process started above](https://github.com/dart-lang/webdev/blob/7543345873b4ea4457a584a86677b38755001d9d/frontend_server_client/test/frontend_sever_client_test.dart#L78) exits immediately.

The way I reproduced this was by running another another program with `dart run --observe` before starting the test. This makes the process started by the test exit immediately with `Could not start the VM service: localhost:8181 is already in use`.

We need to find out why the process started by the test is exiting immediately on CI.
