### ISSUE TITLE
Filter out type generic for Classes with new DDC type system

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2316]
For context: https://github.com/dart-lang/webdev/pull/2312

**Comment by annagrin** [comment]
We should fix the issues:

- Filter out type fields on objects: '\$ti'
- Filter out variables in scope that we don't want to display:
  https://github.com/dart-lang/webdev/blob/7543345873b4ea4457a584a86677b38755001d9d/dwds/lib/src/debugging/dart_scope.dart#L79

  - internal type representations (rti objects  or, in old type system, Legacy type, Nullable types, Function types, abstract function type, Record types, etc)
 - make sure showing used or unused type variables in closures matches VM experience (ether filter it out or convert to dart type)
 - See https://github.com/dart-lang/webdev/blob/4d1de266fbe61d5284f4d6c21c8e291e89f14b8f/fixtures/_testSound/example/scopes/main.dart#L102


Alternatively, consider moving the code for getting object properties and variables in scope to ddc debugger runtime API, splitting the runtime and chrome debugger API calls approproately.
