### ISSUE TITLE
Unable to connect to debugger websocket from NodeJS (localhost vs 127.0.0.1?)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#233]
When trying to connect to the debugger WebSocket in NodeJS I always get `ERRCONREFUSED`:

```js
{"event":"app.debugPort","params":{"appId":"e2de9ykHdzXpXar9bVUHYQ==","port":53399,"wsUri":"ws://localhost:53399"}}
```

```
rejected promise not handled within 1 second: Error: connect ECONNREFUSED 127.0.0.1:53399
extensionHostProcess.js:700
stack trace: Error: connect ECONNREFUSED 127.0.0.1:53399
extensionHostProcess.js:700
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

After much debugging, I found there is a difference between connecting to `localhost` and `127.0.0.1`. Here's a repro w/ `curl`:

```
dantup$ curl -i -N \
  -H "Connection: Upgrade" \
  -H "Upgrade: websocket" \
  -H "Sec-WebSocket-Version: 13" \
  -H "Sec-WebSocket-Key: eZWkxxVlwvap82nkzsiNdg==" \
  -H "Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits" \
  http://localhost:53399

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: nQ4ntnV+FTgaVsv8MpcAJyvC/TA=
```

```
dantup$ curl -i -N \
  -H "Connection: Upgrade" \
  -H "Upgrade: websocket" \
  -H "Sec-WebSocket-Version: 13" \
  -H "Sec-WebSocket-Key: eZWkxxVlwvap82nkzsiNdg==" \
  -H "Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits" \
  http://127.0.0.1:53399 \

curl: (7) Failed to connect to 127.0.0.1 port 53399: Connection refused
```

So it seems if I connect to `localhost` things work, but if I connect to `127.0.0.1` they do not. Unfortunately in NodeJS I'm not specifically connecting to `127.0.0.1`, I'm connecting to `localhost` (using the URL provided), so presumably something internal is resolving it before connecting.

My first thought was that maybe `localhost` is actually IPv6 and the server is listening there, however a) resolving `localhost` gives `127.0.0.1` and b) if that was the case, I'd expect Node to resolve it the same way.

So, this is a cry for help :-)

**Comment by DanTup** [comment]
Oh, actually IPv6 is exactly what's up:

```
dantup$ netstat -anp tcp | grep -i "listen"
tcp6       0      0  ::1.53399              *.*                    LISTEN     
```

So I guess the question is why the WebDev daemon sees `localhost == ::1` whereas my terminal/VS Code/NodeJS see it as `127.0.0.1` 🤔

**Comment by DanTup** [comment]
Ugh, I tried to test this in a small Dart sample, and had the opposite issue:

<img width="608" alt="Screenshot 2019-03-26 at 9 41 46 am" src="https://user-images.githubusercontent.com/1078012/54987108-db5fc780-4fab-11e9-8eda-acd36487b723.png">

```
dantup$ nslookup localhost
Server:		192.168.0.2
Address:	192.168.0.2#53

Name:	localhost
Address: 127.0.0.1
```

**Comment by grouma** [comment]
I now set the default hostname based off the ipv6 support. In doing so, all of the following succeed:

```
$ curl -i -N \
  -H "Connection: Upgrade" \
  -H "Upgrade: websocket" \
  -H "Sec-WebSocket-Version: 13" \
  -H "Sec-WebSocket-Key: eZWkxxVlwvap82nkzsiNdg==" \
  -H "Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits" \
  http://localhost:53399
```

```
$ curl -i -N \
  -H "Connection: Upgrade" \
  -H "Upgrade: websocket" \
  -H "Sec-WebSocket-Version: 13" \
  -H "Sec-WebSocket-Key: eZWkxxVlwvap82nkzsiNdg==" \
  -H "Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits" \
  http://127.0.0.1:53399
```

```
$ curl -i -N \
  -H "Connection: Upgrade" \
  -H "Upgrade: websocket" \
  -H "Sec-WebSocket-Version: 13" \
  -H "Sec-WebSocket-Key: eZWkxxVlwvap82nkzsiNdg==" \
  -H "Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits" \
  http://0.0.0.0:53399
```

In the case of IPv6 support we actually display the hostname as `0.0.0.0` which is a little odd given that all other hosts work but I can address that later if need be.

**Comment by DanTup** [comment]
Great thanks - I tested with the IPv6 branch and the issue seems resolved 👍
