### ISSUE TITLE
Send untruncated dart:developer logs to debugging clients 

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2330]
Creating a DWDS-specific issue from https://github.com/flutter/devtools/issues/3222

- Currently, `dart:developer` uses the `console.log` web API for `developer.log`: https://github.com/dart-lang/sdk/blob/7933cd741d01239367c58f9a384a2bad4a086c4f/sdk/lib/_internal/js_dev_runtime/patch/developer_patch.dart#L70
- By default, Chrome truncates any `console.log` messages over a certain character limit (you can view the untruncated message by clicking the expand arrow in Chrome DevTools
- However, when DWDS reads from the `console.log` stream, it is getting only the truncated messages: https://github.com/dart-lang/webdev/blob/4d1de266fbe61d5284f4d6c21c8e291e89f14b8f/dwds/lib/src/services/chrome_proxy_service.dart#L1243
- This means that when DWDS forwards those messages to debugging clients (e.g. Flutter DevTools) those clients only have access to the truncated message

Some options:

1. Is there some way to get the non-truncated `console.log` messages from Chrome's log stream? 

2. If not, we can use `emitDebugEvent` in `devleoper_patch` to send messages to DWDS instead of console.logging them (this is what https://github.com/dart-lang/sdk/commit/c83eeac5b89ada105c6df3be75b54bce97d5de1b did for `postEvent`). This is the proposal here: https://github.com/flutter/devtools/issues/3222#issuecomment-885230588

**Comment by annagrin** [comment]
There is an old issue for this with links to the ones in the sdk: https://github.com/dart-lang/webdev/issues/1619
