### ISSUE TITLE
Migrate injected client to package:web

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#2338]
The currently used JS interop is restrictive and does not allow for passing structured data between the client and dwds. 

Switch to the new package:web to allow for new features.

**Comment by bkonyi** [comment]
It looks like most of the work for this is done (see #2306) but we need to investigate if there's going to be any breakages in google3.

**Comment by bkonyi** [comment]
We'll also want to follow up and migrate webdev as well.
