### ISSUE TITLE
Expression evaluation fails in global scope

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#2358]
*Repro*

Run a flutter app in VSCode without pausing and try evaluating 'true':

*Expected* 
evaluation succeeds with `true`

*Actual*

DAP gives an error `'Unable to find the library for file:///...'`

<img width="1002" alt="image" src="https://github.com/dart-lang/webdev/assets/12737689/4cfb4ce1-096a-4f52-9704-b573e5e5eaa9">

I looked into it a bit and it seems that SDK Dap expects the results of `getScripts` to be file uris, but we return package: ones. 

@DanTup would it be possible for SDK Dap to unresolve the file uris before looking them up in the results of getScripts? Or should dwds change its output (it might be tricky;)

See: https://github.com/dart-lang/sdk/blob/b4be0315057bb1dd4dca30e991a51cd2ba9a6789/pkg/dds/lib/src/dap/adapters/dart.dart#L1037

`targetScriptFileUri` is a file: Uri on that line, but I think the callee we expect a package: one.

**Comment by annagrin** [comment]
Oh, I think @DanTup fixed it in https://github.com/dart-lang/sdk/commit/a95b5841011dfbf888189b13e98df15cf1bc22e9

**Comment by annagrin** [comment]
Confirmed as fixed, closing!

**Comment by DanTup** [comment]
Yep, somehow all of my original testing (and automated tests) were using files outside of `lib` (which always get file URIs) and I missed this 😔

Let me know if you hit any issues when using code with the fix above.
