### ISSUE TITLE
Problems debugging `static` members

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2386]
In Intellij, when inspecting a `static` member, DWDS throws an error: https://github.com/flutter/flutter-intellij/issues/7228#issuecomment-1984641063

For VS Code and Flutter DevTools, we don't show static members for web apps (we also don't show them for VM apps).

**Comment by bkonyi** [comment]
This appears to have been resolved as https://github.com/flutter/flutter-intellij/issues/7228#issuecomment-1984641063 has been closed.
