### ISSUE TITLE
Messaging has changed if pubspec yaml file not found by pub

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2393]
https://github.com/dart-lang/pub/pull/4186 changed the error message if a pubspec yaml file can't be found. 

Once this change is on a Dart dev branch, we can enable the webdev integration test that is checking for the missing pubspec message.

**Comment by bkonyi** [comment]
Resolved in https://github.com/dart-lang/webdev/commit/d715bcd73fd354ccab63df8293a38a2589c639ab.
