### ISSUE TITLE
Mark errors in daemon logs (for ex. with error=true)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#241]
Currently the daemon sends exceptions back using `app.log` and they look like this:

```
[1:48:13 PM]: <== [{"event":"app.log","params":{"appId":"xxx","log":"package:yyy/src/zzz.dart 3735:16  funcFoo4\n"}}]
[1:48:13 PM]: <== [{"event":"app.log","params":{"appId":"xxx","log":"package:yyy/src/zzz.dart 2991:13  funcFoo3\n"}}]
[1:48:13 PM]: <== [{"event":"app.log","params":{"appId":"xxx","log":"package:yyy/src/zzz.dart 2785:12  funcFoo2\n"}}]
[1:48:13 PM]: <== [{"event":"app.log","params":{"appId":"xxx","log":"package:yyy/src/zzz.dart 3773:16  funcFoo1\n"}}]
```

It's hard to tell that these logs are errors - the spec says that errors can have `error: true` set - is it possible to set it here?

Flutter doesn't mark errors either, but it's clear where they are because they're surrounded with markers like ` ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════` which  we detect in VS Code and consider anything in between as errors.

Either of these would work for me. I'd just like to be able to color that text red in the Debug Console like we do for other exceptions.

**Comment by grouma** [comment]
Sorry, I got sidetracked so only starting to look at this now. Can you provide more details on what exceptions you are trying to parse? I'm seeing similar behavior to Flutter run through webdev:

```
[{"event":"app.log","params":{"appId":"5X/R24Ft7Hakg45U1azPRQ==","log":"══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════\n"}}]
[{"event":"app.log","params":{"appId":"5X/R24Ft7Hakg45U1azPRQ==","log":"The following message was thrown building SpinningSquare(dirty, state:\n"}}]
-- exception details
[{"event":"app.log","params":{"appId":"5X/R24Ft7Hakg45U1azPRQ==","log":"main.dart 9:7                                                main\n"}}]
[{"event":"app.log","params":{"appId":"5X/R24Ft7Hakg45U1azPRQ==","log":"dart:sdk_internal 24967:9                                    <fn>\n"}}]
[{"event":"app.log","params":{"appId":"5X/R24Ft7Hakg45U1azPRQ==","log":"════════════════════════════════════════════════════════════════════════════════════════════════════\n"}}]
```

**Comment by DanTup** [comment]
Is that output from the daemon? When I raised this, I didn't see a header like `══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞══════════` at the start. If that's being included, then this should be fine, we detect those marked for Flutter (mobile) to know where the error starts/ends. I'll take another look tomorrow - thanks!

**Comment by grouma** [comment]
Yes. Maybe you were using an older version of Flutter web. Closing for now.

**Comment by DanTup** [comment]
My guess is that maybe I missed the start of the log due to #251, so I think fixing that probably gives me what I need :)

**Comment by grouma** [comment]
I have a solution for #251 and I'll hopefully get it in before i leave for vacation on Thursday. It's somewhat controversial though as it is introducing another round trip between the browser and webdev for every application load. The idea is that we don't execute the application main until webdev sends the command. That can only happen after the SSE connection is established, which is already gated behind a roundtrip between the client and webdev. I didn't notice any meaningful performance impact but I haven't fully measured it yet.
