### ISSUE TITLE
Make daemon error stacks consistent with Dart / Flutter

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#242]
In Dart and Flutter, the stack traces dumped when exceptions occur are in the same form:

```
[13:40:02] <== #0      MyBrokenHomePage.build (package:hello_world/broken.dart:21:5)
[13:40:02] <== #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:3788:28)
[13:40:02] <== #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3735:15)
[13:40:02] <== #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
[13:40:02] <== #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715:5)
[13:40:02] <== #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710:5)
[13:40:02] <== #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954:14)
```

This makes them familiar in the Debug Console, but in the VS Code extension we also detect the paths there and convert them to clickable links (VS Code can't do this for us because it doesn't understand `package:` URIs).

Errors in the daemon look like this (at least, for this type of project):

```
[1:48:13 PM]: <== [{"event":"app.log","params":{"appId":"xxx","log":"package:yyy/src/zzz.dart 3735:16  funcFoo4\n"}}]
[1:48:13 PM]: <== [{"event":"app.log","params":{"appId":"xxx","log":"package:yyy/src/zzz.dart 2991:13  funcFoo3\n"}}]
[1:48:13 PM]: <== [{"event":"app.log","params":{"appId":"xxx","log":"package:yyy/src/zzz.dart 2785:12  funcFoo2\n"}}]
[1:48:13 PM]: <== [{"event":"app.log","params":{"appId":"xxx","log":"package:yyy/src/zzz.dart 3773:16  funcFoo1\n"}}]
```

Is it possible/reasonable to tweak the format to be the same?

**Comment by grouma** [comment]
We should see if these messages are coming through `console.log` or `console.error`. If it is the latter it should be easy to fix.

**Comment by jakemac53** [comment]
What is the specific request here? I am confused that the first example doesn't seem to be using the daemon protocol at all? Should be be bailing out and logging to stderr instead for anything that is a failure (that seems quite weird?).

**Comment by DanTup** [comment]
> I am confused that the first example doesn't seem to be using the daemon protocol at all?

The first block in the code sample is from Flutter mobile. It does not currently wrap these errors in JSON, they just come via stderr (this isn't good, it's just how it is - it's something we should improve in future).

The second code block is from webdev daemon. That it's using JSON is good (though whether it should be individual lines, I'm not sure).

The request here was to make the format of the stack traces look the same. Eg. in Dart and Flutter we get:

```
#(frame index)      <function-name> (<uri>:<line>:<col>)
```

But for web we get:

```
<uri> <line>:<col>  <function-name>
```

I've changed my code so it can parse both (we want to make the frames clickable to jump to that location in the editor), however since the user also sees this in the console, it'd be nice if it was the same familiar format.

**Comment by DanTup** [comment]
> Should be be bailing out and logging to stderr instead for anything that is a failure (that seems quite weird?).

Note: This error is just a runtime error in the users app - like an error in the build method. We shouldn't be quitting or anything - in Flutter this results in the "red error" screen and the user can just fix their code and reload/restart and carry on. They shouldn't need to start a new debug session.

**Comment by jakemac53** [comment]
My assumption is this is a difference in how the vm and dartdevc log stack traces? I don't think we should really be doing anything with them on the webdev side of things (we don't even know its a stack trace).

However it does seem like it would make sense to file a general sdk issue to unify the stack traces? Maybe there is a good reason they are the way they are though.

**Comment by DanTup** [comment]
> My assumption is this is a difference in how the vm and dartdevc log stack traces? 

It's possible - I did wonder if it was because it was coming from the browser. I don't know enough about webdev/ddc to know who is building them though.

Oh, I just found this:

https://github.com/dart-lang/sdk/issues/31089

which has a sample that's more like the VM than the one above, so now I'm confused. Maybe @jmesserly may have some idea of why ours above is so different?

**Comment by DanTup** [comment]
@jakemac53 something else I noticed - there are no class names in the list (left here is web, right is VM) - is this likely something that can be improved, and if so is it something that needs to be done here, or in the SDK?

![Screenshot 2019-10-29 at 1 40 10 pm](https://user-images.githubusercontent.com/1078012/67773029-f703e280-fa52-11e9-8d15-2c17c1010669.png)

**Comment by jakemac53** [comment]
That would be more of a DDC question I think, @nshahan @Markzipan @vsmenon

**Comment by nshahan** [comment]
I think the consensus is that yes we could add information and reformat the stack traces to make them more consistent with the VM but until this becomes a high priority we will be waiting until a larger rewrite of stack trace handling happens. As it is now the logic for a lot of this is repeated in too many locations to make updating it quick and easy.
