### ISSUE TITLE
Remove unsound null safety options

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2427]
After https://github.com/dart-lang/webdev/pull/2426, which removed all the unsound null-safety tests, we should also remove everywhere where we allow unsound null safety to be specified. 

For example: https://github.com/dart-lang/webdev/blob/ae43e8e935727670e79976b1899152ef4a23df7b/dwds/lib/src/debugging/metadata/module_metadata.dart#L117-L119

**Comment by jyameo** [comment]
@bkonyi @elliette, just to clarify regarding this bug: do we want to completely remove all references to soundNullSafety, or should we enforce that its value is always true but retain the soundNullSafety variables for backward compatibility and to avoid potential regressions?

**Comment by bkonyi** [comment]
I think we can remove everything except the actual flag from the argument parser. We should hide the flag and mark it as deprecated just to make sure we're not breaking anyone.
