### ISSUE TITLE
pub global activate -sgit https://github.com/dart-lang/webdev

### ISSUE THREAD

**Issue by alescdb** [dart-lang/webdev#243]
Just a suggestion, it would be nice if we could activate the github version with :

```
shell> pub global activate -sgit https://github.com/dart-lang/webdev
Could not find a file named "pubspec.yaml" in "/tmp/pub_TALYDT".
```

**Comment by jakemac53** [comment]
The package actually lives under the `webdev` directory of this repo, which is the issue. I don't know if pub global activate supports providing a path, but pub does generally support this (in the pubspec.yaml). Thus I think this is a pub issue.

**Comment by natebosch** [comment]
Here is the canonical issue: https://github.com/dart-lang/pub/issues/1934

For now the workaround is to clone the repo manually and us a path for the `pub global activate`.

Moving this package back to the top level of the repo is not an option for us at this point.
