### ISSUE TITLE
`late` fields are obfuscated in the debugger

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2440]
Example:

![Screenshot 2024-05-28 at 3 06 50 PM](https://github.com/dart-lang/webdev/assets/21270878/947fe85b-0831-4deb-b0b4-08da41f8ad34)

See cl/637897346 for context.

### Some notes:

`late` fields used to be de-obfuscated by DWDS: https://github.com/dart-lang/webdev/pull/1355

This was removed in https://github.com/dart-lang/webdev/pull/2159 and replaced with the DDC runtime debugger API's `getObjectFieldNames` method. 

I see that the DDC runtime API does try to handle late fields: https://github.com/dart-lang/sdk/blob/1a9acb9171a4a6b69d5e537438d3191ff59cd6da/sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/debugger.dart#L546-L549

FYI @nshahan @Markzipan

**Comment by nshahan** [comment]
I've landed fixes for late local variables with these two changes (I think that is what we were discussing with this issue).
* https://github.com/dart-lang/webdev/pull/2445
* https://dart-review.googlesource.com/c/sdk/+/369506

There is technically DDC uses a different representation for class fields, and library level fields so those should be considered independently from each other and from the local variables.
