### ISSUE TITLE
Rename primary development branch to `main`

### ISSUE THREAD

**Issue by parlough** [dart-lang/webdev#2456]
The `dart-lang/webdev` repository is one of the few in the `dart-lang` org that still uses `master` as its default branch, resulting in an inconsistent contribution experience and not following the org's goals to use more inclusive language where possible.

GitHub has docs on [renaming a branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#renaming-a-branch) and automatically handles redirects from the old branch name, so no manual forwarding or commit duplication is likely necessary.

**Comment by bkonyi** [comment]
I agree with this, but I'm a bit nervous about the implications on build infrastructure. Are you aware of any gotchas we might encounter by making this change? Otherwise, it might be best to wait this out since there's a good chance we'll be moving this repo into the Dart SDK in the future.

**Comment by devoncarew** [comment]
We've done this for ~a dozen repos; it's relatively low impact on people's checkouts and such and worth doing. Here's the steps we've followed:

https://github.com/dart-lang/ecosystem/wiki/Renaming-master-branches-to-main

**Comment by bkonyi** [comment]
Sounds good, I'll start the process then!

**Comment by bkonyi** [comment]
@devoncarew, I don't have permission to rename the branch. Since the Developer Services team is taking over this repo, could you give me (and maybe @derekxu16?) admin permissions?

**Comment by devoncarew** [comment]
@bkonyi, done. (though generally, we want to have very few actual admins of a repo; ideally, just the org admins, who would get pinged with occasional change requests)

**Comment by bkonyi** [comment]
Thanks @devoncarew! I'll be sure to keep permissions limited to myself.

**Comment by bkonyi** [comment]
The `master` branch has been renamed to `main` and the relevant GitHub actions have been updated.
