### ISSUE TITLE
Move dependencies required by the injected client to dev

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#248]
Several direct dependencies of webdev are the result of the injected client. These aren't actually used since we only make use of the compiled client.

**Comment by jakemac53** [comment]
Since the client is under lib pub is going to complain about these right? We could potentially move the client to `web` or something and add a builder that copies the js file back to where we expect it?

**Comment by grouma** [comment]
Using a builder is probably the best approach. These files are manually built today. We can simply move them outside of lib and update the suggested command: https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/serve/injected/client.dart#L25
