### ISSUE TITLE
Cant install `webdev`

### ISSUE THREAD

**Issue by dickermoshe** [dart-lang/webdev#2492]
#### General info

- Dart 3.5.2 (stable) (Wed Aug 28 10:01:20 2024 +0000) on "linux_x64"
- on linux / Linux 5.15.153.1-microsoft-standard-WSL2 # 1 SMP Fri Mar 29 23:14:13 UTC 2024
- locale is C.UTF-8

#### Project info

- sdk constraint: '^3.3.0'
- dependencies: drift, drift_dev, drift_flutter, drift_postgres, http, json_annotation, path, path_provider, postgres, rxdart, sqlcipher_flutter_libs, sqlite3, sqlite3_flutter_libs, test, uuid, yaml
- dev_dependencies: args, build, build_runner, build_verify, build_web_compilers, characters, json_serializable, lints, source_span, sqlparser

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                           |
| -----: | ---: | -----------: | -------------------------------------------------------------------------------------- |
|  66 MB | 0.0% |     05:11:34 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/eZTqc7HbVXY8Bf3b         |
| 812 MB | 0.0% |     05:11:34 | dart language-server --protocol=lsp --client-id=VS-Code-Remote --client-version=3.96.0 |
|  84 MB | 0.0% |     05:11:34 | dart tooling-daemon --machine                                                          |
|  82 MB | 0.0% |     05:11:34 | flutter_tools.snapshot daemon --show-web-server-device                                 |

#### Error
```console
mick@MD-LAPTOP-1:~/newdrift/docs$ dart pub global activate webdev
Package webdev is currently active at version 3.6.0.
Downloading packages... . 
> devtools_shared 10.1.0 (was 10.0.2)
Building package executables... 
Failed to build webdev:webdev:
../../.pub-cache/hosted/pub.dev/dds-4.2.6/lib/src/devtools/handler.dart:166:12: Error: The argument type '({String? secret, String? uri})?' can't be assigned to the parameter type 'DtdInfo?'.
 - 'DtdInfo' is from 'package:devtools_shared/src/common.dart' ('../../.pub-cache/hosted/pub.dev/devtools_shared-10.1.0/lib/src/common.dart').
      dtd: dtd,
           ^
```

Link to `devtools_shared` issue: https://github.com/flutter/devtools/issues/8312

**Comment by bkonyi** [comment]
Thanks for the report! It looks like the latest release of `devtools_shared` should have been a major version bump, so it should probably be retracted and republished as 11.0.0. FYI @kenzieschmoll

**Comment by kenzieschmoll** [comment]
10.1.0 has been retracted: https://pub.dev/packages/devtools_shared/versions
