### ISSUE TITLE
webdev dart2js build tests started failing on Windows

### ISSUE THREAD

**Issue by parlough** [dart-lang/webdev#2504]
Failing test example: https://github.com/dart-lang/webdev/actions/runs/11165283178/job/31036724051#step:5:66

I'm assuming the culprit is https://github.com/dart-lang/sdk/commit/ff2d1a277f8e047311729d3562e2c5ea567ec9d2 and some downstream changes might be needed here or in `build_web_compilers`.

\cc @a-siva

**Comment by a-siva** [comment]
A revert has been submitted.
