### ISSUE TITLE
Exceptions thrown during initial main run are not forwarded through the daemon protocol

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#251]
flutter_web will correctly capture errors during main and log them to the console. However, the daemon command sets up a listener for `onStdoutEvent` after main has already begun:
https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/daemon/app_domain.dart#L48

This causes issues as these logs are not buffered and therefore can be lost.

**Comment by grouma** [comment]
cc @DanTup

**Comment by DanTup** [comment]
Aha, maybe that explains what I just wrote in the other issue :)

**Comment by grouma** [comment]
The solution to this will likely also solve our pause on load issue.
