### ISSUE TITLE
Firewall prompt on macOS when running daemon

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#258]
I see this when I launch a web app using the daemon.

![Screenshot 2019-04-04 at 2 59 29 pm](https://user-images.githubusercontent.com/1078012/55572472-89cbe100-56ff-11e9-98ae-f295a4ee9b32.png)

@kevmoo sees this too. Suspects it may be related to what we're binding to. We're binding many things here, so I'm not sure which one is triggering it.

**Comment by grouma** [comment]
I don't currently have access to a mac so I'll need some help debugging. Does this pop up also happen if you simply use `webdev serve` with the latest bits? What about running `pub run build_runner daemon`?

**Comment by kevmoo** [comment]
It absolutely happens w/ `webdev serve` w/ latest bits.

...but only the first run w/ a given SDK

**Comment by grouma** [comment]
What do you mean by first run with a given SDK?

I'm inclined to believe this is actually an issue with the `build_daemon` asset server. See here: https://github.com/dart-lang/build/blob/master/build_runner/lib/src/daemon/asset_server.dart#L27

We should probably update that to use `HttpMultiServer.loopback(port)`

**Comment by kevmoo** [comment]
Mac will post a notification to allow "process X" to listen on a port other
than loopback – but only once.

Once you approve "process X", it won't ask again.

It must be content-based (or something) – since building a new SDK or
installing a new SDK causes the message to come back.

**Comment by grouma** [comment]
I believe a pub upgrade should resolve this issue. Closing for now. Reopen if the problem persists.

**Comment by DanTup** [comment]
I just tried with latest changes and didn't see it, so fix looks good - thanks! 👍
