### ISSUE TITLE
prompt for delete conflicting hangs webdev

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/webdev#259]
Need to forward this through somehow...

**Comment by jakemac53** [comment]
Hmmm I think this is because of the daemon mode.

I think we probably just have to disable the prompt entirely and force the --delete-conflicting-outputs flag :/

**Comment by jakemac53** [comment]
cc @natebosch @grouma for thoughts... but I will run with that for now at least to unblock

**Comment by kevmoo** [comment]
auto-magica `--delete-conflicting-outputs` scares me 😨

**Comment by jakemac53** [comment]
To clarify I am just dropping support for prompts in daemon mode - which means it will fail and tell the user to add that flag. I will not be auto-adding it.

**Comment by jakemac53** [comment]
To add real support would require some special support for prompts from the build_daemon protocol - which gets pretty nasty when you consider multiple potential clients.

**Comment by natebosch** [comment]
> I think we probably just have to disable the prompt entirely

We definitely need to disable the prompt in daemon mode. Our only option to keep UX is to add support for prompts in the daemon protocol and then we'd need to support it in every client.

**Comment by natebosch** [comment]
I'd also be in favor of some mode with a message like "We moved conflicting files to `.dart_tool/build/conflicts/files`. See `.dart_tool/build/conflicts/manifest.txt` for a list".

**Comment by jakemac53** [comment]
> I'd also be in favor of some mode with a message like "We moved conflicting files to `.dart_tool/build/conflicts/files`. See `.dart_tool/build/conflicts/manifest.txt` for a list".

We would likely need an undo command or something to make restoring that easy... I don't really think it is worth it at this time.

**Comment by natebosch** [comment]
We could also consider adding some magic that detects whether the files are tracked in git and consider it safe to delete them if they are.

**Comment by jakemac53** [comment]
Another option I have considered which I think might be better is to create a manifest of generated to source files in the root dir of the package, which is separate from the asset graph.

People would check this in to avoid these warnings entirely (we would safely delete anything in this manifest).
