### ISSUE TITLE
Support setExceptionPauseMode=None for daemon/debugger

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#269]
This isn't critical, but I'm trying to minimise the places I make assumptions about the capabilities of the debugger. Currently when we run in `noDebug` mode (which is what we do always for Web) we send `setExceptionPauseMode: None` to make sure the debugger never breaks (we used to just not connect the debugger, but I've just changed that so we can read capabilities from the registered services).

Currently this fails like this:

```
[3:20:51 PM]: ==> {"id":"6","method":"setExceptionPauseMode","params":{"isolateId":"1","mode":"None"}}
[3:20:51 PM]: <== {"jsonrpc":"2.0","error":{"code":-32603,"message":"UnimplementedError"},"id":"6"}
```

Which results in an error in the log, which is a little confusing.

Is it possible to implement this method as a stub that is just silent if the `mode` passed is `None`, and just throw if it's set to something that's not supported? It'd keep my logs clean without having to code in exceptions (and have to remove them later).

(it's not a big deal, it's mostly for convenience, so if there's a reason you'd prefer not to do this, I don't mind working around it!)

**Comment by jakemac53** [comment]
I think we can probably provide real support for this pretty easily, I will take a look

**Comment by jakemac53** [comment]
Ya, https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setPauseOnExceptions :)

**Comment by DanTup** [comment]
Ok cool - though I presume if we set it to anything other than None, bad things will happen (because the debugger may pause, and we don't support breaking/stepping yet?)

**Comment by jakemac53** [comment]
We do support `resume` at least haha

**Comment by DanTup** [comment]
Works great now, thanks! 👍
