### ISSUE TITLE
`webdev build` should output by default

### ISSUE THREAD

**Issue by natebosch** [dart-lang/webdev#27]
Discussed in an internal thread. For users of builders that are only going to source it isn't always necessary to use `--output`, but web users generally want to build a deployable directory.

Question is whether we want to wait for the new build_runner and by default add `--output web:build`

Should also allow `--output NONE` to get no output and not forward to `build_runner`.

**Comment by kevmoo** [comment]
Hrm...perhaps...

**Comment by jakemac53** [comment]
As mentioned in the recent bug filed on package:build I would be in favor of this. I do also agree that `web:build` would actually be the right default.

**Comment by alorenzen** [comment]
Ok, I'm going to add support for `--output NONE` to disable output, and then set the defaults to `NONE` for `serve` and `web:build` for `build`.

**Comment by kevmoo** [comment]
Ack
