### ISSUE TITLE
Closing the browser should stop the daemon

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#271]
After launching via the daemon, if I close the browser, I just get:

```
[8:59:12 AM]: <== [{"event":"daemon.logMessage","params":{"level":"INFO","message":"Stopped debug service on ws://localhost:50582\n"}}]
```

However the daemon keeps running. For Flutter, the daemon automatically stops if the device is disconnected:

```
[9:05:23 AM]: <== Lost connection to device.
[9:05:23 AM]: <== [{"event":"app.stop","params":{"appId":"f9d90daf-1657-4d36-b078-519b51c88138"}}]
```

Does it make sense to do the same here? It seems weird to close the browser, but then switch back to the editor and it's still in an active debug session (but there's no way to re-launch the browser).

**Comment by jakemac53** [comment]
I think it makes sense to close yes - I actually just noticed the same this morning

**Comment by jakemac53** [comment]
We should likely do this even if you just close the tab (but not the whole window). We would have to start a whole new vm service client if you open the app again in a new tab, which would run on a different port.
