### ISSUE TITLE
Provide a way to start DevTools via the daemon

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#272]
Currently VS Code is spawning its own copy of the DevTools server when the user runs the command, however the daemon already has its own (eg. if I press Alt+D it opens in a new tab). It seems like we should just have one, so probably the daemon should have a command to let us tell it to open the DevTools.

I think we also need to route the DevTools URI back to the editor, so when it's upgraded to have APIs (eg. to support widget rebuild data in the editor) we can connect directly to it.

We might still end up with multiple Devtools spawning (eg. if the user is running a command line app too, VS Code may spawn its own copy), but at least we're not doing it for the same project.

This raises some interesting questions about versions, and who is installing/updating DevTools though. Currently VS Code assumes responsibility for it - should that continue to be the case? Can VS Code `pub global activate` a newer version then expect webdev to use it? What if devtools is already running it (eg. from pressing Alt+D) and *then* the user runs from VS Code and ti decides it should be updated?

(cc @jacob314)

**Comment by jakemac53** [comment]
Webdev has its own dependency on devtools so it would be a different version than what is pub global activated. We do this because we directly open devtools and need to ensure a compatible version (for instance one that supports the new `uri` query param).

In general we could pretty easily either surface the uri to load devtools from and/or a command to open it in the running chrome window.

**Comment by grouma** [comment]
We don't intend to support something the regular daemon doesn't support. We should sync with cc @jonahwilliams before we make progress here.

**Comment by DanTup** [comment]
Tbh, I've been thinking more about this, and I think it would be a bit weird (and different to how DevTools launches for non-web applications).

It does however mean there's a slightly weird situation where launching DevTools from VS Code could give you a different version to using the key-bind in the web project (one is the pub-activated version, and the other is the version you ship), and both could be running at the same time.

I don't think there's an easy fix for that though. Some other ideas:

1. Disable launching DevTools from webdev if running from VS Code (eg. allow us to pass a flag)
2. Allow WebDev to send a notification to VS Code when it wants to launch DevTools and let VS Code do it

I don't know if the "quirk" mentioned above is significant enough to warrant special handling for this though.

**Comment by jakemac53** [comment]
Fwiw, running both at the same time actually works fine in my experience, at least at this time. This might change in the future though if devtools starts registering its own extensions with the vm service.

**Comment by DanTup** [comment]
> This might change in the future though if devtools starts registering its own extensions with the vm service

That's a good point! We just added a service, though it's registered on-demand from a message on stdin. We will need to keep this in mind though (FYI @jacob314).

**Comment by grouma** [comment]
Closing this for now since it's unclear that the daemon command will stick around. This is something we can and should consider for our general web debugging workflow.
