### ISSUE TITLE
webdev daemon should prefer ‘app.log’ events to 'daemon.logMessage' ones

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#282]
The webdev daemon is sending most user facing output as 'daemon.logMessage', but this is really a diagnostic level event. It should prefer sending user facing output as ‘app.log’ events.

This is things like `Restarted application in 8ms` and other messages related to building the app.

**Comment by grouma** [comment]
According to https://github.com/dart-lang/webdev/issues/220#issuecomment-474731269 the `Restarted application` message should be output through `daemon.logMessage`. Is this no longer the case?

As for the messages coming from the build daemon, those will remain on the `daemon.logMessage`. The limitation is outlined in this comment: https://github.com/dart-lang/webdev/issues/219#issuecomment-476902149 I don't think we'll address this issue until we merge with Flutter.

**Comment by devoncarew** [comment]
> According to [#220 (comment)](https://github.com/dart-lang/webdev/issues/220#issuecomment-474731269) the `Restarted application` message should be output through `daemon.logMessage`. Is this no longer the case?

It's not the case - `daemon.logMessage` should only display to users if they're doing something like running with a verbose option on. `app.log` is for user facing output.

> As for the messages coming from the build daemon, those will remain on the `daemon.logMessage`. The limitation is outlined in this comment: [#219 (comment)](https://github.com/dart-lang/webdev/issues/219#issuecomment-476902149) I don't think we'll address this issue until we merge with Flutter.

Gotcha. We should track this issue then to make sure that when the webdev support does merge into flutter, we have a good experience wrt output to the user and displaying progress. Sounds like it'll be tough to address in the short term.

**Comment by DanTup** [comment]
> According to #220 (comment) the Restarted application message should be output through daemon.logMessage. Is this no longer the case?

Sorry, this was my bad. VS Code wasn't using `daemon.logMessage` at all and since you seemed to have issues using `app.logMessage` I just mapped it to the same thing as `app.logMessage` in VS Code (which seemed sensible initially). Devon just informed me the use case was different though, so many not the right choice.

I can easily change VS Code to do whatever, so if you two agree what would be best, I'll fix this end up.

**Comment by grouma** [comment]
For the restart events we have the appId so I'll update the logic to log to `app.log`. See https://github.com/dart-lang/webdev/pull/283

**Comment by devoncarew** [comment]
We could easily add a `daemon.log` event to the protocol spec and have VS Code and IntelliJ watch for those events. I think that would be preferable to having webdev continue to write user facing messages to `daemon.logMessage`.

**Comment by DanTup** [comment]
That sounds reasonable to me. If @grouma is ok with it, I'll wire it up in VS Code before sending the next preview build.

**Comment by grouma** [comment]
I'm fine with that. cc @jonahwilliams since this logic will ultimately be merged into Flutter.
