### ISSUE TITLE
ReloadManager.moduleTopologicalCompare throws when provided module is not in _moduleOrdering

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/webdev#285]
Hitting this on latest!

**Comment by grouma** [comment]
Is this related to https://github.com/dart-lang/webdev/issues/122?

**Comment by kevmoo** [comment]
Not as far as I know...

**Comment by kevmoo** [comment]
See my PR

**Comment by grouma** [comment]
I'm pretty sure this is the same issue. Your PR should address #122.

**Comment by grouma** [comment]
Discussed offline. What was triggering the issue in @kevmoo's case was editing a const expression. I believe that will result in the same issue as adding an import to a new library. We will get a new digest for a module we haven't seen before here:
https://github.com/dart-lang/webdev/blob/master/webdev/web/client.dart#L52

An alternative fix is to check for this condition and do a full reload. @jakemac53  thoughts?
