### ISSUE TITLE
Launch Dart DevTools in a new window instead of a new tab

### ISSUE THREAD

**Issue by jacob314** [dart-lang/webdev#287]
Currently I always end up moving devtools to its own window so starting it in its own window would save me a step.
Consider manipulating the location of the new window to minimize the overlap with the existing flutter web app window.

**Comment by alan-knight** [comment]
Note that this is broken right now because of the referenced fix, but we've switched to a different API which doesn't work in stable, but does work in beta so it should get resolved automatically soon.
