### ISSUE TITLE
using --user-data-dir= with a temp dir means that the window position is not restored

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#297]
`webdev` uses `--user-data-dir=<dir>` with a temp directory for the dir on each launch. This means that the window positions for that instance of Chrome are not restored. I often find myself positioning the chrome window so that it works well with the other tools I have open (IntelliJ, DevTools, ...), and then have to re re-position the window for the next launch.

**Comment by jakemac53** [comment]
Ya we should be dropping the vast majority of these flags imo, they are just annoying (you also lose your devtools settings etc)

**Comment by devoncarew** [comment]
I like a client scoped to `webdev`, or to that user project (separate from the user's regular Chrome), but would also like the settings and changes to be sticky. Perhaps using a global dir (`~/.webdev`)? Or, something like `<project-dir>/.dart_tool/webdev/`?

**Comment by grouma** [comment]
I unfortunately think this argument is required to open the debug port. I like the idea of scoping the directory to the user's project.

**Comment by grouma** [comment]
Adding more details before I forget. If you don't pass `--user-data-dir` the user's current chrome instance is reused even if you pass `--remote-debugging-port`. The debug port will not be opened but the process will succeed. This obviously will cause issues.

**Comment by devoncarew** [comment]
Yup, I've used `--user-data-dir` before for other tools. I'm guessing what we may want to try here is something like `--user-data-dir=<user-project-dir>/.dart_tool/webdev/` (or some other place which is persistent, but won't pollute user facing files).

**Comment by natebosch** [comment]
+1 for `--user-data-dir=<project>/.dart_tool/webdev/chrome_profile/`

**Comment by grouma** [comment]
This likely will be reopened by https://github.com/dart-lang/webdev/pull/342
