### ISSUE TITLE
Triggering a hot restart with no changes causes a blank page

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#302]
Steps to reproduce:

1. Run the basic hello world app with `--debug` (don't provide the `--auto` flag)
2. Open the devtools
3. Click hot restart
4. Notice the application goes blank

**Comment by devoncarew** [comment]
I see something like this from IntelliJ; generally, the first restart doesn't show content in the target chrome process, but the 2nd restart will. After making changes to the app, I have to restart twice to see those changes in the browser.

**Comment by jakemac53** [comment]
I can't repro this on hello_world but I can repro it for flutter. Looks like at least one part of it is a pretty easy fix.

**Comment by devoncarew** [comment]
Verified that this is working for IntelliJ now.
