### ISSUE TITLE
Update to latest vm_service_lib version

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/webdev#314]
This was causing travis hangs so it needs to be investigated, see https://github.com/dart-lang/webdev/pull/310

**Comment by jakemac53** [comment]
cc @devoncarew not sure if you have any specific ideas of what could have caused that

**Comment by devoncarew** [comment]
No, the upgrade should be a no-op for webdev. Is the hang consistent, and does a revert fix it?

**Comment by jakemac53** [comment]
We never landed the PR - the tests work fine at HEAD and hang with the latest.

**Comment by jakemac53** [comment]
This was landed, but now there is a `+2` release so I will leave it open :D

**Comment by natebosch** [comment]
I think this was addressed in #469
