### ISSUE TITLE
from the IntelliJ Inspector, I see 'Unsupported operation: Unsupported response type object'

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#315]
When the IntelliJ Inspector does an eval of:

```
WidgetInspectorService.instance.toObjectForSourceLocation("inspector-5", "tree_6")
```

We sometimes get back responses of:

```json
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Unsupported operation: Unsupported response type object"},"id":"22"}
```

I've guarded against these responses - made this call a best effort call. I'm uncertain what object the debugger proxy is seeing that's causing it to return 'Unsupported response type object'.

**Comment by jakemac53** [comment]
Basically right now we only support a very small set of return types (int, bool, String, etc). We don't support returning dart objects or javascript objects.

**Comment by devoncarew** [comment]
I'd be good to add the type to the error message - that would help identify what's not being encoded (and prioritize the missing types).

**Comment by jakemac53** [comment]
`object` is the type - but I agree that wasn't surfaced particularly well in the message

**Comment by devoncarew** [comment]
Hmm, `object` doesn't give a lot to go on. It's not a `DiagnosticsNode` or something?

**Comment by jakemac53** [comment]
I am sure it probably is ultimately some specific dart class - but all we get back from chrome is `object` (as in, a JS object, which is true but not helpful).

Figuring out more information about it requires doing some digging into the object and further evals etc, which we don't want to do at this time.

We could just list the short list of supported types?

**Comment by devoncarew** [comment]
Sounds like its a tree of objects, which we're asking JS to convert into json for us?

In any case, this would be nice for the inspector, but is not blocking it currently. I don't think there's any short term work necessary here, just the full conversion work when that happens.

**Comment by jakemac53** [comment]
> Sounds like its a tree of objects, which we're asking JS to convert into json for us?

Sort of, although we don't ask it to convert to json. Basically we just get an object id which we can use to do further actions on the object, and no more information besides that. It is very similar to the dart vm service protocol in that sense.

For "raw" js objects you can optionally ask for the actual value but that only works for things that can be serialized by whatever default means the chrome devtools protocol uses.

> In any case, this would be nice for the inspector, but is not blocking it currently. I don't think there's any short term work necessary here, just the full conversion work when that happens.

If there are actual features being disabled as a result that would be good to know also - that would help us prioritize the various parts.

**Comment by jakemac53** [comment]
Going to close this in favor of https://github.com/dart-lang/webdev/issues/135 which should cover it (although its not technically directly related)
