### ISSUE TITLE
Daemon fails to launch Chrome on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#320]
When trying to run on Windows, Chrome fails to launch:

```
CreateProcess
W failed 2
Unhandled exception:
ProcessException: The system cannot find the file specified.
  Command: Google\Chrome\Application\chrome.exe --user-data-dir=M:\Coding\xxxxxxxx\.dart_tool\webdev\chrome_profile --remote-debugging-port=58363 --disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:58356/
#0      Chrome.start (package:webdev/src/serve/chrome.dart:88:19)
```

I'm not sure if this is particular to how I installed Chrome, but the executable path for Windows does look a bit suspicious (see https://github.com/dart-lang/webdev/blob/662ea5c233b793160b680748b09e1a4e8ec6b240/webdev/lib/src/serve/chrome.dart#L18).

On my machine, Chrome is at `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` but I suspect it can probably be in `%APPDATA%` too.

**Comment by jakemac53** [comment]
I think we just borrowed this from the [test package](https://github.com/dart-lang/test/blob/ac21330338e0a7ad68fb19058bb92260706dd6cf/pkgs/test/lib/src/runner/browser/default_settings.dart#L16), but I wonder if it is doing something else special with that path?

**Comment by jakemac53** [comment]
Ah, looks like we are missing this logic https://github.com/dart-lang/test/blob/ac21330338e0a7ad68fb19058bb92260706dd6cf/pkgs/test/lib/src/runner/executable_settings.dart#L46.

cc @kenzieschmoll as well if you are still looking at a general browser package

**Comment by DanTup** [comment]
Works now, thanks!
