### ISSUE TITLE
Add tests to ensure the correct arguments are passed to build_runner

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/webdev#329]
Original title: webdev serve <dir> passes <dir> as an argument to the daemon

This can lead to options skew - it should just be setting the build target and not forwarding this as an argument to the daemon.

**Comment by grouma** [comment]
Updating bug as we just need to add a test.

**Comment by grouma** [comment]
These tests were added, e.g.: https://github.com/dart-lang/webdev/blob/a304b5e86a9a895a766f1bc3a6e017b33c940618/webdev/test/integration_test.dart#L22
