### ISSUE TITLE
provide an alternative to using `Alt-D`

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/webdev#330]
I have a custom window manager that captures `Alt-D` and I haven't figured out how to bypass it. It would be helpful to provide some alternative to launch the Dart DevTools in some other way.

Some ideas:
* add a flag to launch it preemtively (`--debug --launch-devtools`)
* add a flag to override the shortcut (`--debug --devtools-shortcut=Ctrl-Q` :wink: )

**Comment by jakemac53** [comment]
Probably the easiest thing tho do is just create a global function on the page that can launch devtools. That gives a more generic hook for frameworks or users, so you can create a bookmarklet that launches devtools and frameworks could create custom development widgets that launch it.

> * add a flag to launch it preemtively (`--debug --launch-devtools`)

We could consider something like this, but we already have a pretty complex handshake going on in terms of how we start the app and things, and it might end up creating a race condition as well.

> * add a flag to override the shortcut (`--debug --devtools-shortcut=Ctrl-Q` wink )

I _really_ don't want to try and parse arbitrary keys and convert that into a command haha.
