### ISSUE TITLE
Browser stops auto refreshing after long idle time

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/webdev#339]
If I run:

```
webdev serve --debug --auto restart
```

and leave my machine idle for an extended period (e.g., 30 min), the browser no longer auto-refreshes on edits.

@grouma and @jakemac53 suspect the SSE connection is termination and needs to be restarted.

**Comment by grouma** [comment]
For our internal `webdev` equivalent we have reconnect logic like this:

```
_sseClient.stream.listen(_sseMessageHandler, onError: (e) {
      // By default the SSE client uses keep-alive. Allow for a retry to connect
      // before giving up.
      _errorTimer = Timer(Duration(seconds: 5), () {
        _buildStreamController.addError(e);
        _sseClient.sink.close();
      });
    });
```

**Comment by grouma** [comment]
This should have been resolved with https://github.com/dart-lang/sse/pull/17
