### ISSUE TITLE
Devtools inspector when launched through VS Code doesn't show widget tree

### ISSUE THREAD

**Issue by efortuna** [dart-lang/webdev#340]
Launch a flutter web webpage through VS code. open the inspector and try to select any widget on the webpage. The only widget that shows is "root"

This is high priority, please. 

cc @jakemac53

**Comment by jakemac53** [comment]
confirmed that I can repro this with the vscode workflow

**Comment by jakemac53** [comment]
This was caused by vscode registering a pub root directory that wasn't compatible with flutter web, they will just disable that for now.
