### ISSUE TITLE
Minimal set of features to enable debugging

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/webdev#352]
Tracking issues for a minimal set of features to be able to turn on the debug pane using DWDS.

See:
- [x]  #345
- [x]  #346 
- [x] #347 
- [x] #348
- [x]  #349 
- [x] #350
- [x] #426

**Comment by alan-knight** [comment]
Added #426 to the list.

**Comment by grouma** [comment]
All linked issues have been closed.
