### ISSUE TITLE
Error messages and actions from build (e.g. --delete-conflicting-outputs ) are confusing

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/webdev#358]
We can get error messages that are really coming from build_runner or something else internal, and the actions it suggests don't directly work.

For example, if you try to run webdev from source after running it from a global activate, you can get

```
[INFO] BuildDefinition: Found 6 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you are submitting ge[SEVERE] BuildDefinition: Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`.
```
But if you then try to run with --delete-conflicting-outputs you get an error that this option doesn't exist. What you need to do is pass that as an argument after a --, e.g. 

```
dart bin/webdev.dart serve ../example:9876 -- --delete-conflicting-outputs
```

This may be the only relevant option, in which case it wouldn't be unreasonable to just pass it through from webdev.

**Comment by jakemac53** [comment]
I think long term here we want to figure out a way to eliminate this message entirely.

Discussed offline with @natebosch and we could add a field to `build.yaml` which specifies globs that are safe to delete always, and/or we could hardcode some (like `**.g.dart`).

**Comment by jakemac53** [comment]
cc @kevmoo

**Comment by kevmoo** [comment]
👍

**Comment by grouma** [comment]
We now support forwarding additional build arguments through webdev so the original issue should mostly be addressed. Closing for now. Feel free to re-open if I misunderstood.
