### ISSUE TITLE
Clean up Flutter detection when running Webdev

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/webdev#359]
If a user is running from a package that seems like an attempt to convert a flutter package to run on the web, be helpful.

To detect:
- depends on `flutter`, `flutter_test` packages
- has a `flutter` section in pubspec.yaml
- doesn't have a web directory

Let's help users trying out the new stuff

Keep any logic here isolated so we can remove it in the future

CC @vsmenon @timsneath

**Comment by jakemac53** [comment]
I can grab  this one, what behavior do we want from webdev when it detects this?

**Comment by jakemac53** [comment]
I think we did the most important part here, and are now on code freeze until after I/O.

Should we close this or leave it open and try to clean up further later? (we aren't currently checking for flutter sections or the `web` dir)

**Comment by natebosch** [comment]
Left a comment on the related PR. I don't think we should be hardcoding knowledge of what packages are flutter only - we should instead look for something else. Would it work to check if any transitive package is an "sdk" dependency type?

**Comment by grouma** [comment]
Repurposing this bug to align with Nate's comment.

**Comment by grouma** [comment]
Flutter no longer uses webdev so this issue no longer seems relevant.

**Comment by natebosch** [comment]
We do still have the code put in to handle this. Should it be removed?

https://github.com/dart-lang/webdev/blob/bc899b29976eef9bc5ee76c257af3a9ac31435e9/webdev/lib/src/pubspec.dart#L51

**Comment by grouma** [comment]
> Should it be removed?
https://github.com/dart-lang/webdev/pull/1169
