### ISSUE TITLE
"Failed to listen for SIGTERM, osError: OS Error: The request is not supported" on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#363]
On Windows, this happens when trying to start the daemon. I don't know why it says this is not supported, I wonder what Flutter daemon is doing :/

```
[11:58:12] [WebDaemon] [Error] Unhandled exception:
[11:58:12] [WebDaemon] [Error] 
[11:58:12] [WebDaemon] [Error] SignalException: Failed to listen for SIGTERM, osError: OS Error: The request is not supported.
, errno = 50
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by DanTup** [comment]
Can't see any obvious Windows-specific handling in Flutter:

https://github.com/flutter/flutter/blob/8e7c7fcbd48abf2ded5ec876759375453ac18cff/packages/flutter_tools/lib/src/resident_runner.dart#L741

**Comment by grouma** [comment]
I'll fiddle with this tomorrow. I tried to be clever and joined the streams:
https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/command/daemon_command.dart#L57

Maybe it doesn't play nicely with `StreamGroup`?

**Comment by grouma** [comment]
Fun: https://github.com/flutter/flutter/blob/8e7c7fcbd48abf2ded5ec876759375453ac18cff/packages/flutter_tools/lib/src/base/io.dart#L116

I'll do a similar work around...

**Comment by DanTup** [comment]
Weird! Does this mean on Windows that it will just ungracefully terminate? Let me know if you don't have easy access to Windows and need me to do any testing once you have a fix.

**Comment by grouma** [comment]
Working from home this morning on my personal Windows box. I have a fix: https://github.com/dart-lang/webdev/pull/370

I don't have the custom VS code set up yet though so I have only tested through the terminal.

**Comment by DanTup** [comment]
Hmmm, it doesn't crash anymore, but now I see the previous issue with clicking Stop in VS Code not closing the browser :(

**Comment by DanTup** [comment]
From the logs, it does look like the processes are dying (which is good), but the browser is left around. This is consistent with what happened before the SIGINT handler, since the Dart VM was just shutting down immediately. If we can't trap this signal on Windows, I'm no wondering how Flutter shuts down gracefully on Windows 🤔

**Comment by grouma** [comment]
Hmmm. Weird. As a temporary solution is it possible for you to not send `sigterm` and only send `sigint`?

**Comment by DanTup** [comment]
Ugh, apparently I've been confusing things. It is SIGINT we send:

```
const signal = force ? "SIGKILL" : "SIGINT";
```

I did previously say this, but then I (incorrectly) said I'd been mistaken (because in the same code we write "term" to log that VS code requested Termination, as opposed to Disconnection). My understanding is that these are generally treated the same (as a request to terminate gracefully) though.

**Comment by grouma** [comment]
So it sounds like we aren't properly capturing the `sigint` signal on Windows? Is that correct?

**Comment by DanTup** [comment]
I think so. I think I'm sending it and the process is terminating, but it didn't run its cleanup code. I believe the DartVM will shutdown (uncleanly) for signals that aren't handled (the original issue you fixed), but I don't know what the limitations or quirks on Windows are.

**Comment by grouma** [comment]
Can you try removing this logic: https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/command/daemon_command.dart#L63

I'm wondering if we get multiple signals so we are doing a hard exit. That logic is probably not necessary. We do similar stuff for our internal webdev / daemon as a way to allow `ctrl + c` to actually kill the program if it got into a weird state for whatever reason.

**Comment by DanTup** [comment]
Ok, here's what seems to happen:

```
[18:55:24] [WebDaemon] [Info] Spawning M:\Coding\Applications\Google\flutter\bin\cache\dart-sdk\bin\pub.bat with args ["global","run","webdev","daemon"]
[18:55:24] [WebDaemon] [Info]     PID: 14056
[18:55:26] [WebDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.4.2","pid":11916}}]
[18:55:45] [Observatory] [Info] Termination requested by VS Code
[18:55:45] [WebDaemon] [Info] ==> [{"id":"2","method":"app.stop","params":{"appId":"2IWOPZ/FnqS6KYLA2ybT+w=="}}]
[18:55:45] [WebDaemon] [Info] <== [{"id":"2","result":true}]
[18:55:45] [Observatory] [Info] TERM: Going to terminate with SIGINT...
[18:55:45] [Observatory] [Info] TERM: Terminating related process 11916 with SIGINT...
[18:55:45] [Observatory] [Info] TERM: Terminating main process 14056 with SIGINT...
[18:55:45] [Observatory] [Info] TERM: Waiting for process to finish...
[18:55:45] [Observatory] [Info] Process exited (14056, sigint)
```

So we do send two SIGINTS, but one is to the pid we got from the VM service header, and the other one is to the main process that we spawned (the shell). We do both, because we found shells to be unreliably at passing the signals on to spawned apps. So if it *is* being passed on in this case, then it could indeed by receiving two.

**Comment by grouma** [comment]
Cool. I'll send a fix shortly to not do a hard exit. Worst case a `sigkill` will act as expected. Moreover users aren't expected to run the `daemon` command from the terminal.

**Comment by DanTup** [comment]
Just tested with that line commented out, and it still didn't fix it - the browser still remained :(

**Comment by grouma** [comment]
Hmm. This could be a Chrome specific issue. I'll dig into it.

**Comment by grouma** [comment]
I have what I believe is a work around in https://github.com/dart-lang/webdev/pull/371

It would be good to understand what exactly VS code is doing and why it is not an issue with the Flutter CLI. Is the CLI delaying a response like we are now?

**Comment by grouma** [comment]
Looks like Flutter sends the response after the application completely stops: https://github.com/flutter/flutter/blob/8e7c7fcbd48abf2ded5ec876759375453ac18cff/packages/flutter_tools/lib/src/commands/daemon.dart#L532

**Comment by DanTup** [comment]
Testing with 2.0.4 on Windows everything looks good, thanks very much!
