### ISSUE TITLE
pubspec.yaml Version mismatch on MacOS

### ISSUE THREAD

**Issue by iRyanBell** [dart-lang/webdev#378]
I've installed the latest versions of Flutter, Dart SDK, and webdev.

<img width="1178" alt="Screen Shot 2019-05-07 at 4 12 18 PM" src="https://user-images.githubusercontent.com/25379378/57338686-2c9ec300-70e3-11e9-8263-a201783085ec.png">

When I run `webdev serve` I get an error `Could not find a file named "pubspec.yaml"...` where webdev is looking in the wrong directory.

**Comment by jakemac53** [comment]
I think this is actually a `pub` issue, let me see if I can dig it up

**Comment by jakemac53** [comment]
I couldn't find an issue in the pub repo, but I am pretty sure it is coming from the `pub deps` call that webdev makes https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/pubspec.dart#L65.

Can you try running `pub deps` or `flutter packages pub deps` and see if you get the same error? You may be able to resolve this with a `pub get` (or `flutter packages pub get`).

For instance I think this could happen if you are checking out a repo which has a `pubspec.lock` checked in, or if you manually deleted some old versions of packages from your pub cache (or your entire pub cache) at some point.

**Comment by GeertJohan** [comment]
I have the same error. `webdev serve` looks for pubspec.yaml files of dependencies in `$HOME/.pub-cache/`, but `flutter packages get` downloads dependencies to `$HOME/apps/flutter/.pub-cache`.

- `pub debs` gives the same error and exit code 66. :x: 
- `flutter packages pub deps` gives a nice tree of dependencies and exit code 0. :heavy_check_mark:

**Comment by jakemac53** [comment]
`webdev` will use the sdk that it was launched with, I think the root issue here is that the `webdev` executable created by `pub global activate` or `flutter packages pub global active` will both have a line like this:

`dart "<pub-cache>/global_packages/webdev/bin/webdev.dart.snapshot.dart2" "$@"`

Note that it just uses `dart`, which will be whatever `dart` is on your path. This means webdev may actually being ran from your dart sdk, not your flutter sdk (if that is first on your path).

**Comment by jakemac53** [comment]
Related to https://github.com/dart-lang/pub/issues/2128

**Comment by GeertJohan** [comment]
Ahh, this makes sense. I have installed dart systemwide via `apt-get`, and have installed Flutter manually to `~/apps/flutter`.
```bash
$ which dart
/usr/bin/dart
```
I'm now trying to get to a workarround, but that doesn't seem to work either. Not sure if related.
```bash
$ ~/apps/flutter/bin/cache/dart-sdk/bin/dart "/home/geertjohan/apps/flutter/.pub-cache/global_packages/webdev/bin/webdev.dart.snapshot.dart2" serve
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

… stacktrace …
```

**Comment by GeertJohan** [comment]
Without the symlink, but *with* the absolute path to dart (`~/apps/flutter/bin/cache/dart-sdk/bin/dart`), the `Could not find a file named "pubspec.yaml"` error still occurs. So the suggested solution in dart-lang/pub#2128 doesn't seem to solve the issue.

**Comment by jakemac53** [comment]
Interesting, I am also surprised that it is using a different pub cache at all - that seems like a different issue.

Is there some setting you are enabling in flutter to tell it to use a custom pub cache dir? For me they seem to share a pub cache, at least for binaries.

**Comment by GeertJohan** [comment]
So you don't have a folder .pub-cache in the flutter installation directory? How did you install flutter? Do you also have dart installed globally?

Some details on my end:
```
$ flutter --version
Flutter 1.5.4-hotfix.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (9 days ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
``

In my .profile:
```
export PATH="$HOME/bin:$PATH"
export PATH=$HOME/apps/flutter/bin:$PATH
export PATH="$PATH:/usr/lib/dart/bin"
export PATH="$PATH":"$HOME/.pub-cache/bin"
```

**Comment by GeertJohan** [comment]
Well this is intersting. I ran `rm -rf ~/apps/flutter/.pub-cache` followed by `flutter packages get`. Flutter didn't put the downloaded packages in ~/apps/flutter/.pub-cache, but put them in `~/.pub-cache`. This fixed the `Could not find a file named "pubspec.yaml"` error.

I'm now left with the following error (but may be unrelated?)
```
$ webdev serve                                                                                 ⏎
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

< stacktrace >
```

**Comment by GeertJohan** [comment]
> Perhaps a previous version of Flutter used to keep its own .pub-cache and that remnant now got me into trouble?

As an experiment I ran `mkdir ~/apps/flutter/.pub-cache` and `flutter packages get`. Once that folder exists, flutter will use it to download packages to. But when the folder doesn't exists, flutter falls back to `~/.pub-cache`.

**Comment by catalsdevelop** [comment]
same issue with @GeertJohan . my env:
* flutter v1.6.1-pre.80 with dart 2.3.1
* $FLUTTER_PATH `/Volumes/STORAGE/dev/fluttersdk`
* webdev 2.0.5

add `$FLUTTER_PATH/bin`, `$FLUTTER_PATH/.pub-cache/bin`, `$FLUTTER_PATH/bin/cache/dart-sdk/bin` to $PATH env

No matter how I install webdev with `pub global activate webdev`(installed to $HOME/.pub-cache/bin) or `flutter packages pub global activate webdev`(installed to $FLUTTER_PATH/.pub-cache/bin) , webdev always search files from `$HOME/.pub-cache`. I've checked **.packages**, all modules point to `$FLUTTER_PATH/.pub-cache`. 

For the present, I make a soft link to  `$HOME/.pub-cache` from `$FLUTTER_PATH/.pub-cache` and it works. But still confuse about the two `.pub-cache`.

**Comment by jakemac53** [comment]
Ya, I don't understand how/why some people have two pub caches and not others either.

I think some people mentioned simply deleting the flutter pub cache will make it start using the regular pub cache.

In the meantime though, you can run `flutter pub global run webdev` to force it to run from the flutter pub cache I believe.

**Comment by jakemac53** [comment]
I am going to close this issue here, as it is not related to `webdev` directly, but more of a pub/flutter issue. I have filed https://github.com/dart-lang/pub/issues/2128 which is part of the problem, but there is still the general issue of multiple pub caches as well.
