### ISSUE TITLE
Unexpected package URIs in errors (`foo/packages/foo`) on Travis Linux

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#379]
I got this failure in my integration tests on Travis:

```
[12:34:02] <== [{"event":"app.log","params":{"appId":"v2vuA+WRWLh78UEiFsfBvQ==","log":"When the exception was thrown, this was the stack:\n"}}]
[12:34:02] <== [{"event":"app.log","params":{"appId":"v2vuA+WRWLh78UEiFsfBvQ==","log":"dart:sdk_internal 4556:11                                                    throw\n"}}]
[12:34:02] <== [{"event":"app.log","params":{"appId":"v2vuA+WRWLh78UEiFsfBvQ==","log":"package:broken/packages/broken/main.dart 25:5                                methodThatThrows\n"}}]
```

The URI is `package:broken/packages/broken/main.dart`, but this should be `package:broken/main.dart`. I can't reproduce it locally (though the CI failures was Linux and I'm on macOS). The full log is here (search for `package:broken/packages/broken/` as there's a lot of logging after the failure, it's not at the end of the file):

https://test-results.dartcode.org/logs/web-tests/c06755497435013724da982a1a987d3ef0eb1398/linux/flutter_web_only_stable_stable/flutter_for_web_debugger_moves_known_files_from_call_stacks_to_metadata.txt

**Comment by DanTup** [comment]
(does seem to be reliable, and only on Linux 🤔)

**Comment by DanTup** [comment]
Sorry, I should've included that! :) It's not a pub package, it's just a sample app I have in Dart Code's integration tests. It's not even a referenced package, it's the running application itself:

https://github.com/Dart-Code/Dart-Code/tree/master/test/test_projects/flutter_web/broken

It's really just the sample Flutter web app, but made to throw:

https://github.com/Dart-Code/Dart-Code/blob/8ba29ba0612e1f41614bdcc2b327b89ed1ddc5e0/test/test_projects/flutter_web/broken/lib/main.dart#L30

I can't reproduce it locally, and on my CI builds it passes on macOS but fails on Linux. On macOS the path in the error is `package:broken/main.dart` but for Linux it's `package:broken/packages/broken/main.dart`.

**Comment by DanTup** [comment]
Actually this isn't Linux specific, macOS sees it too (pretty sure it didn't when I raised this though):

[12:45:51 GMT+0000 (GMT)] [WebDaemon] [Info] <== [{"event":"app.log","params":{"appId":"75fQJe+qBkLMvJsuMMppOg==","log":"package:broken/packages/broken/main.dart 30:5                                methodThatThrows\n"}}]

Not locally though 🤷‍♂️

**Comment by grouma** [comment]
I can reproduce this on my Linux box locally.

I think this is a `package:build` issue. The bootstrap contains this:

``` JS
let modulePaths = {
 "dart_sdk": "packages/build_web_compilers/src/dev_compiler/dart_sdk",
 "packages/broken/main": "packages/broken/main.ddc",
 "packages/collection/collection": "packages/collection/collection.ddc",
 "packages/collection/src/algorithms": "packages/collection/src/algorithms.ddc",
 "packages/collection/src/canonicalized_map": "packages/collection/src/canonicalized_map.ddc",
 "packages/collection/src/comparators": "packages/collection/src/comparators.ddc",
 "packages/collection/src/iterable_zip": "packages/collection/src/iterable_zip.ddc",
 "packages/collection/src/priority_queue": "packages/collection/src/priority_queue.ddc",
 "packages/collection/src/utils": "packages/collection/src/utils.ddc",
 "packages/flutter_web/animation": "packages/flutter_web/animation.ddc",
 "packages/flutter_web/cupertino": "packages/flutter_web/cupertino.ddc",
 "packages/flutter_web/foundation": "packages/flutter_web/foundation.ddc",
 "packages/flutter_web/gestures": "packages/flutter_web/gestures.ddc",
 "packages/flutter_web/io": "packages/flutter_web/io.ddc",
 "packages/flutter_web/material": "packages/flutter_web/material.ddc",
 "packages/flutter_web/physics": "packages/flutter_web/physics.ddc",
 "packages/flutter_web/scheduler": "packages/flutter_web/scheduler.ddc",
 "packages/flutter_web/services": "packages/flutter_web/services.ddc",
 "packages/flutter_web/src/animation/animation": "packages/flutter_web/src/animation/animation.ddc",
 "packages/flutter_web/src/cupertino/activity_indicator": "packages/flutter_web/src/cupertino/activity_indicator.ddc",
 "packages/flutter_web/src/foundation/assertions": "packages/flutter_web/src/foundation/assertions.ddc",
 "packages/flutter_web/src/gestures/arena": "packages/flutter_web/src/gestures/arena.ddc",
 "packages/flutter_web/src/physics/clamped_simulation": "packages/flutter_web/src/physics/clamped_simulation.ddc",
 "packages/flutter_web/src/scheduler/binding": "packages/flutter_web/src/scheduler/binding.ddc",
 "packages/flutter_web/src/services/clipboard": "packages/flutter_web/src/services/clipboard.ddc",
 "packages/flutter_web_ui/ui": "packages/flutter_web_ui/ui.ddc",
 "packages/meta/meta": "packages/meta/meta.ddc",
 "packages/typed_data/typed_buffers": "packages/typed_data/typed_buffers.ddc",
 "packages/vector_math/hash": "packages/vector_math/hash.ddc",
 "packages/vector_math/vector_math_64": "packages/vector_math/vector_math_64.ddc",
 "web/main": "main.ddc"
};
```

**Comment by grouma** [comment]
Ignore my previous (now deleted comment).

I can reproduce this consistently on my Linux box. I chatted with Jake and the issue is likely in `stack_trace_mapper.dart` within `package:build_web_compilers`.

If I do a simple `print(StackTrace.current)` the trace has the incorrect package paths.

I will investigate further and potentially move this bug to the build repo.

**Comment by grouma** [comment]
I did some further investigation. 

I'm going to jot down some notes as I am still not entirely sure where the issue is.

The `frame.uri` appears valid here:
https://github.com/dart-lang/build/blob/791e7e4855764fc74a31bdbe2c26c7cfe631e454/build_web_compilers/web/source_map_stack_trace.dart#L41

Its value is:
`http://localhost:39333/packages/broken/main.ddc.js`

However the `sourceUrl` for the `span` is invalid here:
https://github.com/dart-lang/build/blob/791e7e4855764fc74a31bdbe2c26c7cfe631e454/build_web_compilers/web/source_map_stack_trace.dart#L48

Its value:
`http://localhost:39333/packages/broken//packages/broken/main.dart`

The corresponding source map looks valid:
```JS
{"version":3,"sourceRoot":"","sources":["/packages/broken/main.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;UAO4B;AACxB,YAAO,gDACE,uBACA,wDACiB,2CAElB,sCAAwB;IAElC;;;;;;EACF;;;;;;;IAKe;;;;;;UAGa;AACxB,YAAO;IACT;;MAGE,WAAiB;AACjB,YAAO;IACT;;;QAZsB;QAAU;;;AAAU,yDAAW,GAAG;;EAAC;;;;;;;;;;;;;;;AAjB5C,wCAAO;EAAc","file":"main.ddc.js"}
```

This leads me to believe there is an issue in `package:source_map` but more investigation is required.

**Comment by grouma** [comment]
This is no longer an issue with the latest webdev and `Dart VM version: 2.5.0-dev.2.0 (Sun Aug 11 20:46:20 2019 +0200) on "linux_x64"`
