### ISSUE TITLE
Hot restart is broken with the edge sdk

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/webdev#383]
This looks like it is because our default handler for the root library expects the old library name (`main.dart`) instead of the new version (`org-dartlang-app:///web/main.dart`).

cc @natebosch we might want to consider a rollback until after next week

**Comment by natebosch** [comment]
>  our default handler for the root library

Where is that defined?

> we might want to consider a rollback until after next week

Are you expecting a dev publish that will break folks, or is that mostly for the flutter web team building against edge?

**Comment by jakemac53** [comment]
> Are you expecting a dev publish that will break folks, or is that mostly for the flutter web team building against edge?

Right, I don't want a dev to be published and break us in the middle of the summit

**Comment by jakemac53** [comment]
> Where is that defined?

https://github.com/dart-lang/build/blob/master/build_web_compilers/lib/src/dev_compiler_bootstrap.dart#L169

**Comment by jakemac53** [comment]
This is fixed now
