### ISSUE TITLE
Run webdev server not working

### ISSUE THREAD

**Issue by ngocdtph03070** [dart-lang/webdev#387]
Hello when running cmd basic project received an error message 
WebSocketChannelException: WebSocketChannelException: SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8)
Serving DevTools at http://127.0.0.1:50713
Starting resource servers...
> `
Unhandled exception:
SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8)
#0      _NativeSocket.lookup.<anonymous closure>  (dart:io-patch/socket_patch.dart:386:9)
#1      _RootZone.runUnary  (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue  (dart:async/future_impl.dart:126:18)
#3      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:639:45)
#4      Future._propagateToListeners  (dart:async/future_impl.dart:668:32)
#5      Future._completeWithValue  (dart:async/future_impl.dart:483:5)
#6      Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:513:7)
#7      _microtaskLoop  (dart:async/sched`

**Comment by grouma** [comment]
Closing in favor of https://github.com/dart-lang/webdev/issues/375
