### ISSUE TITLE
Hot reload socket issues

### ISSUE THREAD

**Issue by sinegovsky-ivan** [dart-lang/webdev#390]
- Dart SDK 2.2.0
- angular: 5.2.0
- build_runner: 1.2.3
- build_web_compilers: 1.2.0
- MacOSX 10.4
- Chrome 74

**Issue 1:** 
We are using https for local development, but hot-reload socket use ws:// prefix and chrome doesn't allow to use ws:// with https:

> Uncaught Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

This issue is fixed in https://github.com/dart-lang/build/pull/2271

**Issue 2:** 
We are using nginx as the proxy to our backend. Nginx has been redirecting all root requests (for example: foo.bar/) to our backend.
Since the socket connection is also using the root address, it is redirected to our backend instead of webdev hot-reload server.
Is any way to change socket endpoint? 
_For example localhost:8181/hot-reload-socket instead of localhost:8181._

**Comment by kevmoo** [comment]
@jakemac53 – done!

**Comment by jakemac53** [comment]
@sinegovsky-ivan Can you confirm this is a problem with webdev? After a bit more thought I think it actually won't be, we don't use web sockets for webdev we use SSE instead

**Comment by sinegovsky-ivan** [comment]
@jakemac53 currently it is a problem with build-runner: https://github.com/dart-lang/build/pull/2271.
But, as i know, dart team want to move bug-related code to this package.

**Comment by grouma** [comment]
Seems like this issue isn't relevant for this repo.
