### ISSUE TITLE
Access to Webdev Serve output

### ISSUE THREAD

**Issue by wtoalabi** [dart-lang/webdev#392]
I am planning to write the frontend for my next project in Dart.
The backend will be PHP (using the Laraval framework).

Right now, using dart2js is the only way to convert the dart code to JS.
And it is slow for my process.
After each iteration, I have to save and generate, then refresh the browser to view changes.

The only alternative I know of is to use webdev.
That works, but I dont have access to the generated file.

Which I need to give to Laravel.

The way it is done with JS/Webpack is that the you write your React/Vue and it saves (when you --watch) the generated JS into a specified folder...which is then picked up by the server.

So, my question is, is this possible in a way I have not found out yet?

Is there a way to watch dart files for changes and output the result into an output folder of choice?

Thanks!!!

**Comment by jakemac53** [comment]
You can use `-o <dir>` to create an output directory you can serve from.

**Comment by jakemac53** [comment]
Closing this as that should do what you want, see `-o` here https://github.com/dart-lang/webdev#webdev-serve.

**Comment by wtoalabi** [comment]
Thanks for the quick reply!!!!
Yes, I did that...and the folder was populated with these:
`.dart_tool`
`packages`
and
`.build.manifest`
What I need is a js file that I can reference.
Am I missing something?

**Comment by jakemac53** [comment]
Does your project show up if you do a `webdev serve` and load that uri? It sounds like maybe you don't have a standard package layout (application under web/example/test) or are missing some dependencies (build_web_compilers).

**Comment by wtoalabi** [comment]
Yes! 
I am not using the standard package structure.
My app is being served by laravel (PHP)  at the back-end. 
I need a way to generate JS script that I can link with the back-end server. 
I realized that if I were to use dart2js directly, I would have the JS file... But I want a faster workflow. 
1. Edit/Create dart file...
2. A watcher is triggered, which runs the compiler and 
3. Makes the resulting JS file accesssible to laravel... 
Just like webpack helps compile JS assets. 

Thanks!

**Comment by jakemac53** [comment]
Where is your application code at? You will need to force the `build_web_compilers|entrypoint` builder to run on that file, something like this in your `build.yaml` file (you may need to create one):

```
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - my/application.dart
```

**Comment by wtoalabi** [comment]
OK thanks!
