### ISSUE TITLE
cli add option to specify source

### ISSUE THREAD

**Issue by phanirithvij** [dart-lang/webdev#404]
I tried running

```shell
 flutter pub global run webdev serve
```

from a directory `D:\Projects\fun\flutter\test_app`

And it seems to think that it's in a different directory
The error it generated was

```dart
webdev could not run for this project.
Could not find a file named "pubspec.yaml" in "D:\Software\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\protobuf-0.13.11".
pub failed (78)
```

**Platform**: Windows 10
**webdev: version**: 2.0.5

And there's no flag or a cli option to specify the src directory
like:
```shell
 flutter pub global run webdev serve ./
# or
 flutter pub global run webdev serve --src ./
```

I installed webdev using the command

```shell
 flutter pub global activate webdev
```

Is there something wrong with my installation or my code execution?

**Comment by phanirithvij** [comment]
😂 issue: 404

**Comment by jakemac53** [comment]
This is a pub issue - you are ending up with two separate pub caches - a flutter specific one and a dart sdk specific one. See https://github.com/dart-lang/pub/issues/2128 for some details, we probably need to file a separate issue about the duplicate package caches.

**Comment by jakemac53** [comment]
To solve the issue you could try doing a regular `pub get`, instead of a `flutter pub get`, which will make sure the same package versions exist in your normal pub cache too.
