### ISSUE TITLE
Allow specifying a port for `webdev daemon`

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#424]
This came up at https://github.com/Dart-Code/Dart-Code/issues/1769 but is also mentioned in comments at https://github.com/dart-lang/webdev/issues/198#issuecomment-496526820. Currently it always calls `findUnusedPort` in the daemon.

**Comment by jakemac53** [comment]
I am not sure if it makes sense to add features to webdev daemon at this point, given it is flutter specific and that logic will be moving to the flutter SDK - cc @jonahwilliams .

**Comment by DanTup** [comment]
I did wonder that, but this code will all remain for non-Flutter web, right?

**Comment by jakemac53** [comment]
> I did wonder that, but this code will all remain for non-Flutter web, right?

That is an open question I guess - this was explicitly only intended to support the flutter web launch. The protocol is certainly not what we would have designed if we wanted to support some sort of general daemon protocol. I think it also has some fairly flutter specific parts. At the same time I can see from an IDE perspective it is nice to have a single protocol to talk to. Having that be the flutter protocol doesn't seem right though.

**Comment by DanTup** [comment]
Fair enough - if it's not certain this will remain, then I agree it's probably better to skip this until that's clear.

The daemon protocol isn't that huge, so while it'd be nice to avoid another implementation, I don't think having something different would be a huge pain if non-Flutter web was a little difference (for VS Code, at least :-)).

**Comment by jakemac53** [comment]
From my perspective almost all interactions would actually go through the dart vm service protocol. The daemon already has some overlap with that.

Basically, the goal on our end I think would be to make it look more like a Dart VM binary than a flutter binary.

**Comment by grouma** [comment]
Closing this for now until we agree upon the approach for general web debugging.
