### ISSUE TITLE
Investigate the impact of simplifying/removing the hot reload hooks

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/webdev#434]
Specifically, this would be removing all the [hooks](https://github.com/dart-lang/build/blob/master/docs/hot_module_reloading.md#using-hooks-to-handle-module-reloading), and potentially instead adding a single top level hook to replace those with.

This would be in anticipation of better built in hooks in DDC, that mirror what the dart VM does. This would also help unify the support and implementation of hot reload across backends.

We can use `pub_crawl` to check all packages on pub to see if anybody implements these hooks today, and if so what they use them for.

**Comment by jakemac53** [comment]
Note that the existing logic has to bail out if the module structure changes, so another advantage of this approach would be that we can handle far more types of edits without a hard refresh.

**Comment by jakemac53** [comment]
Ok, I used `pub_crawl` to pull search every package on pub that has a dev_dependency on build_runner for `hot$`, and there are zero results.

Seems like we can safely remove these hooks and simplify the logic, as well as making it able to handle more types of edits.

**Comment by grouma** [comment]
I believe this can be closed as we no longer support these hooks. The hot restart logic for Flutter Web / Webdev is now shared and contained in `package:dwds`.
