### ISSUE TITLE
DWDS - Figure out how to maintain our state and manage the lifecycles

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/webdev#439]
As we pull apart the giant ChromeProxyService we end up with a number of smaller objects (Debugger, Sources, Breakpoints) but they often need to communicate with each other or with the main server. And there's also an issue of how those objects change. If we do a full reload do they just go away and get recreated? What about in a hot restart? Hot reload? Even in a full reload we may want to e.g. re-establish breakpoints. And we will have the state in Chrome, what the tool on the other end of the VM service thinks the program state is, and our internal state 

Should we have our own representation of an isolate, encapsulating this? If we do, can/should it be effectively global? Can we assume we're only talking to one target at a time? Right now we have a lot of objects that get passed the proxy on construction and remember it as their context. Is that preferable to having it visible at the top level?

We should have a design discussion/doc about this.

**Comment by grouma** [comment]
This has mostly been addressed. We can open up more specific clean up bugs if need be.
