### ISSUE TITLE
webdev doesn't (seem) to update the original digest set after a hot reload

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/webdev#441]
1. Load app.
1. Force hot restart from devtools: no JS files loaded. Great.
1. Edit main.dart. Reload with main.dart.js. Great
1. Force hot restart from devtools.
    * expected: no JS files loaded
    * actual: main.dart.js reloaded

**Comment by kevmoo** [comment]
CC @vsmenon @jakemac53

**Comment by jakemac53** [comment]
https://github.com/dart-lang/webdev/blob/master/webdev/web/client.dart#L139 :man_facepalming:
