### ISSUE TITLE
library names incorrectly used as URIs

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/webdev#448]
I'm seeing issues when I try to use something without a regular package structure and the URIs are confused.

So if run test code

```
webdev serve example:8081 --debug
```
then if I open devtools and got to the debugger I don't get the sources.

I believe the issue is that in createIsolate we call _getLibraryNames and then we assign those names to the uri field of the Library object. But these aren't valid URIs for the library source files if there's additional path. In _constructLibrary we assign the uri to the scriptRef. Then we add it to _serverPathToScriptRef, but we haven't constructed the server path correctly.

**Comment by grouma** [comment]
I believe this has been resolved.
