### ISSUE TITLE
`build_web_compilers` version – 0.4.0 – is not within the allowed constraint – ^0.3.6

### ISSUE THREAD

**Issue by chalin** [dart-lang/webdev#48]
I can't run Angular example apps from within IntelliJ EAP. An attempt results in:

```nocode
/opt/brew/opt/dart/libexec/bin/pub global run webdev serve web:51764
webdev could not run for this project.
The `build_web_compilers` version – 0.4.0 – is not within the allowed constraint – ^0.3.6.
Dart Dev Server terminated
```

My app is using 0.4.0. Where is the 0.3.6 constraint coming from, webdev?

cc @kwalrath @jakemac53

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/webdev/pull/49

Published as `0.2.1`
