### ISSUE TITLE
Have an option for an un-minified client.js

### ISSUE THREAD

**Issue by willdrach-wk** [dart-lang/webdev#496]
I was recently debugging an error that looked something like this:
```
Instance of 'minified:p'\n    at Object.b (http://localhost:8888/webdev/src/serve/injected/client.js:367:3)\n    at nq.$0 (http://localhost:8888/webdev/src/serve/injected/client.js:5445:20)\n    at Object.uK (http://localhost:8888/webdev/src/serve/injected/client.js:1268:5)\n    at kK.uP (http://localhost:8888/webdev/src/serve/injected/client.js:1270:7)\n    at lL.$1 (http://localhost:8888/webdev/src/serve/injected/client.js:4865:3)\n    at vk (http://localhost:8888/webdev/src/serve/injected/client.js:441:17)\n    at MutationObserver.<anonymous> (http://localhost:8888/webdev/src/serve/injected/client.js:449:51)
```

It would be valuable to understand the error there, but with the minified code I don't even have a chance. @evanweible-wf and I found an example of where @grouma put up an unminified build (#472) to help debug a similar issue, and I was able to also get this working on my own fork, which lead to a better understanding of the error.

Simply enough, I think it would be easier for us as webdev users and you guys, as webdev devs, if we could provide unminified traces to help track down these "strange" errors, and for that reason I'd love to have the option to somehow specify that I want the server to run with an unminified `client.js`, ideally through just adding a `--no-minify` command line argument or something similar.

**Comment by jakemac53** [comment]
The main issue is that we ship this pre-compiled so that every user doesn't have to compile it. We are considering however just only ever shipping the unminified version. This isn't running in production apps so it doesn't really need to be minified.

**Comment by willdrach-wk** [comment]
Yeah, that makes sense to me.

**Comment by grouma** [comment]
Related: https://github.com/dart-lang/stagehand/issues/620#issuecomment-511594425
