### ISSUE TITLE
"UnimplementedError: The stream `Logging` is not supported"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#498]
The debugging protocol says it implements protocol 3.20, but it throws when subscribing to the Logging stream (added in 3.17).

```
-32603 UnimplementedError: The stream `Logging` is not supported.
#0      ChromeProxyService.onEvent.<anonymous closure> (package:dwds/src/services/chrome_proxy_service.dart:374:11)
#1      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#2      ChromeProxyService.onEvent (package:dwds/src/services/chrome_proxy_service.dart:351:31)
#3      VmServerConnection._delegateRequest (package:vm_service_lib/vm_service_lib.dart:992:40)
<asynchronous suspension>
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
```

VS Code subscribes to this event by default in the upcoming release (in order to print messages sent through `dart:developer`'s `log()` function). Web debugging is not enabled, so this won't affect anything yet - but I'm working through the debugger tests to try and figure out what works and what doesn't :-)

This might be slightly related to #185 (cc @grouma), though I think that was before the the stream was made public in 3.17. Having the stream be a no-op would be better than throwing IMO (assuming it can't be supported).

**Comment by jakemac53** [comment]
We have intentionally chosen to respond with an error if trying to use a feature we don't support, which allows clients to do feature detection. I think that is the correct decision.

We should however consider adding explicit handling of `UnimplementedError` to return error code 100 which from the spec means "Feature is disabled"? That would allow vscode to not surface these errors to the user.

**Comment by jakemac53** [comment]
Also fwiw we do actually support the Logging stream but I didn't know it had become public so we probably still support it by the old name, so we should fix that :).

**Comment by DanTup** [comment]
Ok, let me know if that's the case and you can update it or not (I couldn't find any obvious signs of functionality in the repo). If you don't support it, I'll need to update VS Code to handle this better.

**Comment by jakemac53** [comment]
Looks like I was wrong - but adding support should be pretty easy. Fwiw the supported streams all pretty much exist here https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/services/chrome_proxy_service.dart#L352.

**Comment by DanTup** [comment]
Looks like the other ones that aren't supported are no-ops currently?

If it's likely to be added (either working, or as a no-op) before web debugging ships, then I won't need to do anything. If not, I'll add some code to handle it before I ship anything with web-debugging enabled. For testing the web debugger in VS Code in the meantime, I have a setting that lets me turn off the logging support.

**Comment by grouma** [comment]
This is resolved correct? Closing. Please re-open if I'm mistaken.

**Comment by DanTup** [comment]
I don't think so - it still looks like subscribing to the `Logging` stream would throw:

https://github.com/dart-lang/webdev/blob/ad21fc30d3efb0caa98d43cc1d4f53a9158b1e8a/dwds/lib/src/services/chrome_proxy_service.dart#L345-368

**Comment by grouma** [comment]
I think I got confused with the Debugging stream because that's where we forward console logs.
