### ISSUE TITLE
build -r option is a no-op

### ISSUE THREAD

**Issue by chalin** [dart-lang/webdev#50]
Apparently the default for `build` is `--release`, which makes the shorthand `-r` a no-op (and actually, made me believe that the default was still _debug_ until @kevmoo corrected me on that). Consider dropping the `-r` shorthand.

**Comment by kevmoo** [comment]
But `--no-release` is an "op" – it let's you build to a directory w/ DDC.

**Comment by chalin** [comment]
Right, but then the only accepted option should be `--no-release`, not `--release` nor `-r`.

cc @kwalrath
