### ISSUE TITLE
Pausing within a package : uri causes issues with DevTools

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#505]
To reproduce simply set a breakpoint in a package colon location and hit said breakpoint.

For example run the gallery example and set a breakpoint here:
https://github.com/flutter/flutter_web/blob/master/examples/gallery/lib/demo/material/material_button_demo.dart#L35

Notice that the blue location error is not present when paused. DevTools also does not jump to the correct source location.

Alternatively, if you pause a running application, if the corresponding paused location is in a package : uri then the following error is logged to the console:

```
NoSuchMethodError: The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()
dart:core                                           Object.noSuchMethod
package:vm_service_lib/vm_service_lib.dart 4659:24  SourceLocation.toJson
package:vm_service_lib/vm_service_lib.dart 3134:47  Frame.toJson
package:vm_service_lib/vm_service_lib.dart 2867:47  Event.toJson
package:vm_service_lib/vm_service_lib.dart 999:28   VmServerConnection._delegateRequest.<fn>
```

This is almost certainly an issue with how we are treating URIs as everything else appears to work.

**Comment by jakemac53** [comment]
Fwiw the `toJson` issue means there is a required field which isn't populated (on a SourceLocation object).

**Comment by grouma** [comment]
Yup. The issue is that we don't have source information at all for the given spot. I'm fairly confident it's a URI issue which should be straight forward to resolve.
