### ISSUE TITLE
[package:dwds] Filter out .template.dart files from sources

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#506]
If you run webdev on an angular application and use Dart DevTools the generate .template.dart files will be included in sources. We probably don't want to display these. They also needlessly slow down things.

**Comment by grouma** [comment]
Also probably want to filter out `.shim.dart` as well.

**Comment by natebosch** [comment]
These are intentionally retained so they can be debugged. I'm not sure what mechanism we'd use to filter them, we shouldn't hardcore patterns.

**Comment by grouma** [comment]
If we are fine with hardcoding patterns we can easily filter them here:
https://github.com/dart-lang/webdev/blob/1837b9a2f1a747027195f7e25a469357e7eb32c0/dwds/lib/src/debugging/inspector.dart#L390

I don't see how they would be of much value for debugging.

**Comment by natebosch** [comment]
> If we are fine with hardcoding patterns we can easily filter them here:

I really don't think we should. If we decide to do anything it should be to add the .template.dart files to the [angular cleanup builder](https://github.com/dart-lang/angular/blob/6cc901af6db7820b100cfc9b846cefe67df7be3c/angular/lib/src/build.dart#L104).
This should be a framework decision, not a build system decision.

> I don't see how they would be of much value for debugging.

@matanlurey for thoughts.

**Comment by grouma** [comment]
> This should be a framework decision, not a build system decision.

That's a fair argument. I just noticed these files while playing around with the new debugging tools on the Angular Component Gallery. To my unexperienced eye they seemed pretty useless from a debugging context.

**Comment by jakemac53** [comment]
They are directly imported at least by the main entrypoint (and then transitively from there). In theory they would also be useful for debugging but i think in practice they are so opaque that they aren't really that useful.

Either way though I agree that webdev/build should not hardcode this. We could add some way of configuring extensions to hide or something though, and angular could advise users to do that.

**Comment by natebosch** [comment]
Do you see any downsides in behavior if Angular removes them with a post process builder?

**Comment by jakemac53** [comment]
I think its odd that you could see imports to files which you can't access. Whether or not they are useful I think we should show them. This is similar to the SDK sources - we don't show them today but we eventually want to.

**Comment by grouma** [comment]
@jacob314 one of the reasons I wanted to filter these files out is that the performance of DevTools is quite poor when there are 1k+ sources. Searching becomes quite slow.

**Comment by jakemac53** [comment]
At most this doubles the number of files so if we are already seeing issues then there is likely a larger issue here that needs to be resolved. Reducing by <2x won't solve anything long term.
