### ISSUE TITLE
Handle display of functions

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/webdev#533]
Right now they come up as "Unsupported type function" followed by the source.

**Comment by grouma** [comment]
@nshahan do we have built in support from DDC for getting a function name?

**Comment by natebosch** [comment]
What are you starting with? What is the context?

Are you going from a library object to its methods? Is this for when there is a function stored in a variable?

**Comment by natebosch** [comment]
Most function objects have a `.name` field, but it's not always what you want to use. Here is an example:

```dart
void topLevel() {}

class Foo {
  static void staticOnClass() {}
  void instanceMethod() {}
}

void main() {
  var a = topLevel;
  var b = Foo.staticOnClass;
  var c = Foo().instanceMethod;
  var d = () {};
  void e() {}
  a();
  b();
  c();
  d();
  e();
}
```

Assuming we are paused in this method the way to get at the names would be something like:

```js
a.name; // "topLevel"
b.name; // "staticOnClass", no way I can see to get name "Foo"
dart.getType(c._boundObject) + "." + c._boundMethod.name; // Foo.instanceMethod
// I can't find a way to get anything useful from `d` - a local function literal
e.name; // "e"
```


Can someone track down the VM behavior for all of these cases? If we need to add more support in DDC we can take a look.

**Comment by grouma** [comment]
It looks like support in the VM is pretty poor. They simply show `_Closure` for all of the above cases. However, upon hover they show something like `Closure: () => void from Function 'topLevel': static.`
