### ISSUE TITLE
Add support for  `preview-dart-2`

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/webdev#54]
We want to enable `preview-dart-2` as soon as we can, even when it is still only a flag for dart2js.

This should both run `build_runner` on the `--preview-dart-2` vm, as well as run DDC and Dart2Js with the `--preview-dart-2` flags set.

Open question: do we introduce this as a flag? And when do we make it the default?

**Comment by alorenzen** [comment]
Note, this is blocked by https://github.com/dart-lang/sdk/issues/32188

**Comment by kevmoo** [comment]
We have a matrix here.

We could have `webdev --preview-dart-2` run dart2js in the right mode.

But invoking webdev on the VM w/ --preview-dart-2 would be some other magic (likely `pub global run --preview-dart-2 webdev` or some such.

Then for the full effect: `pub global run --preview-dart-2 webdev serve --preview-dart-2`

**Comment by handicraftsman** [comment]
https://github.com/dart-lang/sdk/issues/32188#issuecomment-390324601

**Comment by kevmoo** [comment]
This would ONLY work for dart2js. Users would have to use `DART_VM_OPTIONS=--preview-dart-2" for the VM.

Still interesting?

**Comment by alorenzen** [comment]
@kevmoo let's at least enable dart2js/ddc with passing `--preview-dart-2` to build_runner. We should probably go ahead and turn this on by default.

It's a shame that there's no other way to enable for the VM, but hopefully we're close enough to flipping the default there that https://github.com/dart-lang/angular/issues/1353 is enough for now.

**Comment by natebosch** [comment]
>  let's at least enable dart2js/ddc with passing `--preview-dart-2` to build_runner.

There is no reasonable way to support this other that also plumbing special support for this flag through build_runner as well which would violate our goal of _not_ having special understanding of the compilers.

We don't have any syntax to allow _merging_ arguments in to some list of Strings option on a builder which is what would need to happen here.

**Comment by dgrove** [comment]
We are going to flip the flag very soon on the SDK, so if you're willing to clean up afterwards, that's another possibility.

**Comment by dgrove** [comment]
Removing block label, as  dart-lang/sdk#32188 has been closed.

**Comment by alorenzen** [comment]
dart-lang/sdk#32188 didn't completely fix the issue, see https://github.com/dart-lang/sdk/issues/33460. So we're still blocked here.

The work-around is to use `DART_VM_OPTIONS=--preview-dart-2 pub global run webdev build`

**Comment by matanlurey** [comment]
Is this done "enough" now that the default is Dart2?

**Comment by kevmoo** [comment]
Yeah. Need to roll to support latest build_runner, but that's orthogonal
