### ISSUE TITLE
Webdev Serve - Support Secure HTTP

### ISSUE THREAD

**Issue by binarypie** [dart-lang/webdev#564]
For our workflows we depend on various microservices all over HTTPS endpoints. Currently to properly experience (locally during development, production would never use webdev serve) what our users might experience using our products we are running a webserver on top of the the output of webdev build. We'd prefer a more streamlined day-to-day approach if we could pass in the cert/key and just let webdev serve to the work for us.

It looks like http_multi_sever supports serving content over HTTPS with the SecureContext object. Could we support that in `webdev serve` with the appropriate flags such as `tlskey= and tlscer=` or similar. 

I'd be happy to make the pull request if the project is interested in the functionality.

**Comment by grouma** [comment]
This is definitely on our radar and something we would like to have. Happy to review a PR.

**Comment by binarypie** [comment]
> This is definitely on our radar and something we would like to have. Happy to review a PR.

Any particular flag names you'd prefer for the key and cert?

**Comment by grouma** [comment]
We have a similar internal tool to `webdev` that uses `ssl-cert-chain` and `ssl-cert-key`. For consistency those probably make sense.

**Comment by jakemac53** [comment]
Implemented in https://github.com/dart-lang/webdev/pull/565
