### ISSUE TITLE
Ensure up-to-date dependencies

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/webdev#58]
Blocking https://github.com/dart-lang/angular/issues/1095.

> It's incredibly easy to use an out-of-date set of `build_runner`, `build_web_compilers`, and `build_test` - which, coupled with https://github.com/dart-lang/pub/issues/912, means that users frequently use out of date development dependencies, and when they try and upgrade, hit deadlocks or incomprehensible error messages, i.e (as an example only):
> 
> ```
> Resolving dependencies...
> Package angular_components has no versions that match >=0.9.0-alpha+8 <0.10.0 derived from:
> - merck_crm_mashup depends on version ^0.9.0-alpha+8
> Process finished with exit code 1
> ```

An _alternative_ would be support for `peer_dependencies` in `pub`: https://github.com/dart-lang/pub/issues/1837.

**Comment by grouma** [comment]
Closing as there is no work for us to do.

We have logic to ensure that the required `build_runner`, `build_web_compilers` and even `build_daemon` packages are used. With the recent changes to pub, the errors are not as cryptic.

I agree in an ideal world we would make use of `peer_dependencies` but I don't think those are coming any time soon..
