### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<String>' when calling `setVMTimelineFlags()`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#580]
I see the following exception when using DevTools to connect to and inspect a flutter for web app (this is against flutter at head):

```
dart_sdk.js:18998 type 'List<dynamic>' is not a subtype of type 'List<String>'
#0      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1094:19)
<asynchronous suspension>
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#7      _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#14     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#15     _StreamController._add (dart:async/stream_controller.dart:640:7)
#16     _StreamController.add (dart:async/stream_controller.dart:586:5)
...

 (-32603) from setVMTimelineFlags()
```

The issue might be in package:vm_service or in package:dwds - it probably needs a bit of investigation to figure out. I think what's happening is that somewhere along the way, the type args is lost from the List of strings which are the param to `setVMTimelineFlags(List<String>)`.

Perhaps, when parsing the arg from json, `package:vm_service` isn't creating the List w/ type args (`List<String>.from(foo)`)? It would then fail when trying to call `_serviceImplementation.setVMTimelineFlags()`.

cc @bkonyi

**Comment by devoncarew** [comment]
Thinking about this some more, I think the issue likely is in package:vm_service; when it pulls the lis tout of json it needs to create it as a String parameterized list.

https://github.com/dart-lang/sdk/blob/master/pkg/vm_service/lib/vm_service.dart#L1094

That's in generated code, so we'll need to adjust the generator. I'll move this issue to dart-lang/sdk repo.

**Comment by devoncarew** [comment]
> I'll move this issue to dart-lang/sdk repo.

I'll keep this open - once a fix is available from package:vm_service, we'll need to update the dep here, and re-publish, for the fix to be available to flutter.

**Comment by devoncarew** [comment]
This - https://github.com/dart-lang/webdev/pull/600 - brings the latest package:vm_service into dwds; we'll still need to push a new package:dwds to flutter in order to fix this issue.

**Comment by grouma** [comment]
This should now be resolved.
