### ISSUE TITLE
Consider moving devtools dependency to webdev pubspec

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/webdev#584]
devtools is currently bringing a lot of transitive dependencies, and I'm not sure but it seems as if the package itself is unused here. I'm currently unable to roll dwds though to flutter_tool because of the mockito dependency, but similar situations could occur in the future, especially since both packages are under heavy development.

**Comment by jakemac53** [comment]
It isn't imported but it is used, see https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/servers/devtools.dart#L28. We actually should be migrating this to use the server code provided by devtools though.

We could look at separating all that logic out into webdev, we would have to see how hard that is to do. Or we could potentially make all of devtools injectable.

**Comment by natebosch** [comment]
> because of the mockito dependency

What mockito dependency?

**Comment by jonahwilliams** [comment]
I removed it in https://github.com/flutter/devtools/pull/923

**Comment by grouma** [comment]
I don't think this is an issue. I consciously made `package:dwds` depend on `DevTools` as I wanted to support the `alt + d` workflow for Flutter Web. To do so, we need to spin up `DevTools` to serve the application. We can of course try to spin up a globally activated version but that may have compatibility issues with `package:dwds`'s vm service protocol implementation.

Jake made a good point that we have duplicate logic that should be cleaned up. I have opened issue https://github.com/dart-lang/webdev/issues/596 to track fixing this. I'm going to close this issue. Let me know if my thought process is incorrect.
