### ISSUE TITLE
add validation to ensure that package:dwds sends values for required fields

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#586]
The IntelliJ debugger currently has a bug where it checks for the absence of a field in a json debugger entity map to represent `null`. So, we consider `BoundVariable.declarationTokenPos` to be null if the map representing the bound variable doesn't have a `declarationTokenPos` entry. If it has one, we attempt to read its value as an int, and throw an exception a runtime:

```
java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsInt(JsonElement.java:244)
	at org.dartlang.vm.service.element.BoundVariable.getDeclarationTokenPos(BoundVariable.java:35)
	at io.flutter.vmService.frame.DartVmServiceStackFrame.addVars(DartVmServiceStackFrame.java:183)
	at io.flutter.vmService.frame.DartVmServiceStackFrame.addStaticFieldsIfPresentAndThenAllVars(DartVmServiceStackFrame.java:130)
...
```

We'll need to fix this in the IntelliJ plugin, but package:dwds may also consider not sending fields whose values are null.

**Comment by jakemac53** [comment]
This is really the vm_service package that is sending these - I think it is only doing it for "required" fields though that we aren't populating.

We could consider making there be a null check in the vm_service package so it would throw when serializing/deserializing required fields that are null?

**Comment by devoncarew** [comment]
`declarationTokenPos` may be optional and ok to be null, the IntelliJ code is just not doing the null checking properly.

There's a long pipeline to get changes into flutter web now
- land a change in the sdk for `vm_service`
- publish
- roll the dep into `package:dwds`
- publish
- bring the dep into flutter

**Comment by devoncarew** [comment]
Looking into it, it does look like `BoundVariable.declarationTokenPos` is a required field.

```
  // The token position where this variable was declared.
  int declarationTokenPos;
```

**Comment by devoncarew** [comment]
> We could consider making there be a null check in the vm_service package so it would throw when serializing/deserializing required fields that are null?

Having an option to validate that we're sending values for all required fields makes sense; either asserts, exceptions, or at least some logging. Clients will likely have assumptions that required fields exist. Do we know which required fields aren't being populated currently?

cc @alan-knight and @grouma as well

**Comment by jakemac53** [comment]
We don't know which ones aren't being populated because there is zero enforcement :/.

I think moving forward with a change to actually enforce them (at least on serialization, but probably also deserialization) would be the easiest way to discover all the missing ones.

**Comment by grouma** [comment]
That's correct. We don't have a good sense for what is required. @alan-knight and I have been working backwards from the DevTools codebase. We basically do what is minimally required to get certain features working. If IntelliJ or other clients have different requirements then those likely won't be satisfied.

**Comment by devoncarew** [comment]
I can file issues as I hit them, but it would also be good to have a list of which required fields aren't being populated, in order to future-proof the impl.

**Comment by devoncarew** [comment]
I opened https://github.com/dart-lang/webdev/issues/588 for the `declarationTokenPos` issue.

**Comment by devoncarew** [comment]
One technique here would be to add a new constructor to the vm service objects which takes named, required params for non-optional fields.
