### ISSUE TITLE
Any way to configure api proxy?

### ISSUE THREAD

**Issue by emctoo** [dart-lang/webdev#61]
Created a simple web project with stagehand, how would I configure some of my requests to some other services?

**Comment by alorenzen** [comment]
I'm not quite sure what you're asking for. Are you asking how to send RPCs within angular, or do you want `webdev serve` to proxy requests to a server?

**Comment by emctoo** [comment]
@alorenzen the latter case, but maybe not in angular, just those simple web page.

**Comment by alorenzen** [comment]
The way we've mostly set things up is to instead have the server proxy requests to `webdev serve`, not the other way around. Or a reverse proxy layer that routes to both `webdev serve` and to the other services.

This is not something that `webdev` (or [`build_runner`](https://github.com/dart-lang/build), which it is calling) is intended to handle.
