### ISSUE TITLE
Getting another exception on hot restart

### ISSUE THREAD

**Issue by natebosch** [dart-lang/webdev#610]
```
Instance of 'Event'
null
```

I can consistently repro, will need to dig in.

**Comment by natebosch** [comment]
pausing on caught exceptions doesn't work here for some reason.

**Comment by grouma** [comment]
Can you give repo steps?

**Comment by natebosch** [comment]
I have a skeleton project, my `main.dart` is:

```dart
void main() {
  print('hello world');
}
```

my `index.html` is:

```html
<head>
  <script defer src="main.dart.js"></script>
  <title> Sample </title>
</head>
```

my pubspec.yaml is:

```yaml
name: dart_repro

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  build_runner: any
  build_web_compilers: any
```

I run webdev with `webdev serve --hostname $(hostname) --debug-extension --auto=refresh`

When I make a change in the file I get an error in the console where my application is running, I don't need to have devtools open.

I also get the error if I refresh the browser myself.

```
Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

Instance of 'Event'
null

Navigated to http://<host>:8080/
Hello world!
```

**Comment by Hexer10** [comment]
I'm having the same issue, even with the stagehand's barebone web-app template, on the first load the page works fine, but whenever I hot-reload and/or refresh the page it doesn't load anymore, and I get that error in the console.

> Dart VM version: 2.4.1 (Wed Aug 7 13:15:56 2019 +0200) on "windows_x64"

**Comment by Hexer10** [comment]
Right after the error this gets printed in the console: `EventSource failed loading: GET "http://127.0.0.1:8080/$sseHandler?sseClientId=b245f810-d1b0-11e9-db0c-edb68679c0eb".` idk if it has something to do with this, but it's very annoying to have to stop and rerun `webdev` everytime I make any changes

**Comment by grouma** [comment]
@Hexer10 I think your issue is related to the injected client but slightly different. I believe you are running into #647. I'll investigate shortly.
