### ISSUE TITLE
HTTPS does not work in Docker

### ISSUE THREAD

**Issue by jompu** [dart-lang/webdev#618]
I'm trying to run AngularDart development environment on Docker with `webdev serve`. But HTTPS doesn't work, HTTP does. Even though the pull request says it should work: https://github.com/dart-lang/webdev/pull/565. 

With Webdev version 2.5.0.

**To reproduce:**
1. Clone https://github.com/angular-examples/quickstart/tree/master
2. Get TLS/SSL certificate and private key, e.g. with mkcert tool: https://github.com/FiloSottile/mkcert
3. Add following ´Dockerfile´ to the root of the repo.
```
FROM google/dart:2.4

RUN mkdir /app/

COPY ./lib /app/lib
COPY ./web /app/web
COPY ./test /app/test

# Copy certificate for https.
COPY ./.development-ssl /app/.development-ssl

ENV PATH /root/.pub-cache/bin:$PATH

# Install AngularDart tools.
RUN pub global activate webdev \
    && pub global activate stagehand

WORKDIR /app/

# Install dependencies for the app.
ADD ./pubspec.* ./
RUN pub get

EXPOSE 443

CMD ["webdev", "serve", \
        "--tls-cert-chain", "/app/.development-ssl/localhost+cert.pem", \
        "--tls-cert-key", "/app/.development-ssl/localhost+key.pem", \
        "--hostname", "0.0.0.0", \
        "web:443"]
```
4. Build Docker image and run as a container: `docker build -t quickstart . && docker run -p 8443:443 -d quickstart`
5. `curl -vvv https://localhost:8443` returns: 
```
* Rebuilt URL to: https://localhost:8443/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:8443 
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:8443
```
6. Now in Dockerfile, replace all 443 with 80 and comment --tls-cert-chain and --tls-cert-key lines.
7. Build Docker image and run as a container: `docker build -t quickstart . && docker run -p 8080:80 -d quickstart`
8. `curl http://localhost:8080` works.

**Comment by jompu** [comment]
Just tested that it works **without** Docker: `webdev serve --tls-cert-chain .development-ssl/localhost+cert.pem --tls-cert-key .development-ssl/localhost+key.pem --hostname 0.0.0.0 web:8443`

**Comment by jompu** [comment]
I have tested that a simple dart server works.

Running a simple dart server with this code:
```
import 'dart:async';
import 'dart:io';
import 'package:path/path.dart' as p;

String certificateChain = '.development-ssl/localhost+cert.pem';
String serverKey = '.development-ssl/localhost+key.pem';

Future main() async {
  Directory.current = p.dirname(Platform.script.toFilePath());
  var serverContext = SecurityContext(); /*1*/
  serverContext.useCertificateChain(certificateChain); /*2*/
  serverContext.usePrivateKey(serverKey, password: 'dartdart'); /*3*/

  var server = await HttpServer.bindSecure(
    "0.0.0.0",
    443,
    serverContext, /*4*/
  );
  print('Listening on https://${server.address.address}:${server.port}/');
  await for (HttpRequest request in server) {
    request.response.write('Hello, world!');
    await request.response.close();
  }
}
```

And Dockerfile:
```
FROM google/dart:2.4
  
RUN apt-get update -y && apt-get install -y ca-certificates libssl-dev

RUN mkdir /app/

COPY ./server.dart /app/

COPY ./.development-ssl /app/.development-ssl

ENV PATH /root/.pub-cache/bin:$PATH

WORKDIR /app/

# Install dependencies for the app.
ADD ./pubspec.* ./
RUN pub get

EXPOSE 443

CMD ["dart", "server.dart"]
```

**Comment by jompu** [comment]
The issue might be on this line: https://github.com/dart-lang/webdev/blob/a9975829c3d4a1880089b7996f77051093f224da/webdev/lib/src/serve/webdev_server.dart#L120

It is actually binding towards 127.0.0.1, not to given hostname. HttpMultiServer doesn't seem to have bindSecure like HttpServer does, which should fix the issue.

**Comment by jompu** [comment]
Made a related issue for HttpMultiServer: https://github.com/dart-lang/http_multi_server/issues/17

**Comment by grouma** [comment]
Thanks for the detailed issue. I'm sorry this one fell through the cracks. @natebosch will tackle the https://github.com/dart-lang/http_multi_server/issues/17 issue and I'll follow up with the DWDS changes.

**Comment by grouma** [comment]
@jompu Can you see if this works for you: https://github.com/dart-lang/webdev/pull/671

**Comment by binarypie** [comment]
I'm happy to see this fixed. This was something I'd mentioned in passing when doing the initial pull requests. I was just thinking about putting our front-end workflow into a container so I'll give this a test over the new couple days and report back.

**Comment by grouma** [comment]
Closing since there hasn't been an update. Please re-open if necessary.
