### ISSUE TITLE
flutter_tools|lib/src/build_runner/build_script.dart was not found in the asset graph

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#621]
I see this error when running a flutter web app:

```
Building application for the web...
flutter_tools|lib/src/build_runner/build_script.dart was not found in the asset graph, incremental builds will not work.
 This probably means you don't have your dependencies specified fully in your pubspec.yaml.
```

I'm not sure what entry I'm missing in my pubspec, but suspect that we're leaking some package:build_runner impl. details up through to users.

**Comment by grouma** [comment]
Is this still an issue? cc @jonahwilliams

**Comment by jonahwilliams** [comment]
I'm manually filtering out the message, but it seems like it should probably be skipped if I've passed the --skip-build-script-checks flag.

Not high priority.

**Comment by jakemac53** [comment]
Fwiw this happens because `flutter_tool` is not depended on by the package, since it is part of the sdk. Normally the build script would be generated inside the root package.
