### ISSUE TITLE
Isolate should start with `pauseEvent.kind` of `PauseStart` instead of `Resume`

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#629]
There's some discussion in here:

https://github.com/flutter/flutter/pull/39521#issuecomment-527550223

In the VM, when we run with `--start-paused`/`--pause-isolates-at-start` the isolates are in the `PauseStart` state. The editors use this as a signal to send breakpoints (and set things like exception pause mode) and then resume. Currently the isolates are already in the `resume` state (according to the `pauseEvent.kind` on the isolate requested upon connecting to the VM service).

**Comment by grouma** [comment]
DWDS doesn't have command line arguments so I don't follow this issue. You can simply not eagerly call `runMain` here:
https://github.com/dart-lang/webdev/blob/f8553bb2e09de933ef8d60f400c04bb003d07730/dwds/lib/src/connections/app_connection.dart#L23

**Comment by DanTup** [comment]
I opened this based on our discussion at https://github.com/flutter/flutter/pull/39521#issuecomment-527550223 :)

I understand dwds doesn't have flags, I guess we need support for a consuming library to be able to provide the equiv of `--start-paused`. I think @jonahwilliams already changed it not to call `main`, but the isolates have a `pauseEvent.kind` of `resume` instead of `PauseStart` as expected.

I don't know where the issue is - is it possible dwds doesn't start the isolates in `PauseStart` by default?

**Comment by grouma** [comment]
I see. Let me change the details.

**Comment by DanTup** [comment]
I think you have the title the wrong way around :) It should start in `PauseStart` (if it's starting paused, at least - see https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#eventkind for the descriptions for each state).

**Comment by grouma** [comment]
Ah yes. At least I'm implementing it correctly haha

**Comment by DanTup** [comment]
Great, thanks!
