### ISSUE TITLE
Include DevTools integration tests for package:dwds

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#633]
See this: https://github.com/flutter/devtools/blob/master/packages/devtools/test/inspector_controller_test.dart

**Comment by grouma** [comment]
See also: https://github.com/flutter/devtools/blob/master/packages/devtools/test/support/flutter_test_driver.dart

**Comment by jakemac53** [comment]
I have been looking into this - made enough progress to at least run tests but I have realized a few things in the process.

For the most part I think these tests should be ran only in the flutter repo using the flutter tool (anything flutter specific at least like the inspector tests). That is what users will actually be going through generally, and actually once the tech preview ends webdev won't be able to run flutter apps at all anyways, so these would just be deleted soon.

I will look into any debugger specific tests though and see if those make sense - although they likely do rely on the flutter daemon which we want to deprecate support for as well.

All of that being said I was able to get tests running and some of them pass - the golden tests have small differences like dependency ordering that would have to be worked through.

**Comment by jakemac53** [comment]
Ok, I landed a PR to create the `devtools_testing` package which I validated is enough to be able to run the integration tests.

Given that these test are very flutter specific and the flutter_web defork is complete, we should not be owning the actual running of these tests in `webdev`, but instead it should be done in the flutter repo.

@jonahwilliams how do you feel about moving this issue into the flutter repo?

**Comment by jakemac53** [comment]
The obvious disadvantage here is that we wouldn't catch any issues until the flutter_web team attempts to roll our updates into flutter, but I don't see any reasonable way around that.

**Comment by jonahwilliams** [comment]
SGTM. I think it is reasonable to detect regressions when we roll in dwds, that matches how we integrate other dart tooling
