### ISSUE TITLE
Support using Dart Debug extension without spawning DevTools

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#669]
I'm not sure where best to raise this, so feel free to move if this is the wrong place (FYI @grouma @jacob314 @jonahwilliams).

I was testing [Jonah's PR](https://github.com/flutter/flutter/pull/40627) for spawning Flutter web apps without Chrome (to support remote/container environments) but when I click the Dart debug extension button, it immediately spawns DevTools with the debugger active (which I think is unpausing the app, since it loads despite using `--start-paused`).

This won't work for VS Code - we need to be able to run the debug proxy, but with the debugger from DevTools disabled (and it not unpausing the app - since VS Code needs to send its breakpoints, etc) - at least until we could better support multiple debuggers.

Is there any way we can prevent this? (either by not spawning DevTools automatically, or allowing VS Code to pass through querystring parameters like it does when calling `launchDevTools`, to set the theme, hide debugger, etc.)? My preference would be to not spawn DevTools at all (since if you press the DevTools button in VS Code, you'll then get another instance which will look different due to dark theme, and may even be a different version if dwds is bundling its own - plus an upcoming VS Code may have a setting to "automatically open DevTools" which would result in two of them for web apps).

**Comment by grouma** [comment]
> ... but when I click the Dart debug extension

You are referring to [this](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm?hl=en) extension correct?

I don't see how the Dart Debug Extension could be unpausing the application. That seems like a Flutter CLI issue and is worth tracking under their repo.

We currently don't have infrastructure to pass DevTools parameters but I'm open to adding some. One possibility that would work with both the extension and the `alt + D` workflow is to embed these parameters into the application which can be read before launching DevTools. @jakemac53 and @alan-knight  for thoughts on this.

The question now is how Flutter / Webdev passes these parameters. @jonahwilliams thoughts on how this should be done?

**Comment by DanTup** [comment]
> You are referring to this extension correct?

Correct :)

> I don't see how the Dart Debug Extension could be unpausing the application.

Sorry, I meant I think DevTools is unpausing it. It's possible it's not, and the pause-at-start just isn't working correctly yet - but the main issue is that right now we can't support two debuggers (VS Code + DevTools) reliably (it's something we'd like to, but it needs some work - in VS Code at least).

> We currently don't have infrastructure to pass DevTools parameters but I'm open to adding some.

Is there a reason DevTools is required to be launched here? VS Code is already able to launch DevTools (it needs to to support non-web apps) so it seems weird to spawn a different version. It also prevents use of some of the things I've been adding lately like being able to re-use DevTools windows across sessions (VS Code usually spawns DevTools and then communicates over stdin with a JSON protocol, but that won't work if DevTools is spawned from the extension).

Is there a way to have the extension run to provide the debugger interaction without DevTools (eg. DevTools can still be launched by VS Code, so it's the same version, has all the params, and has the JSON API available to VS Code)?

**Comment by grouma** [comment]
> Is there a reason DevTools is required to be launched here?

Yes. The extension is intended to be used as a remote debugging workflow. We need to know where DevTools is being served from ahead of time so that we can embed that information into your running application. The extension reads this information to launch a tab running  DevTools for you since your command line app (Webdev or Flutter CLI) is presumably running on a remote device.

> Is there a way to have the extension run to provide the debugger interaction without DevTools (eg. DevTools can still be launched by VS Code, so it's the same version, has all the params, and has the JSON API available to VS Code)?

I can think of a few ways to get this to work. I'm a little confused with your workflow though. What's the point of the extension if you are using VS code in this scenario? Presumably you have it running on your local machine and can just initiate debugging through it?

Nonetheless, getting the extension to play nice with VS Code isn't a high priority for us right now. The intent behind the extension was to enable the "remote debugging" workflow which is critical for our Google3 users. 

Final note, there seems to be quite a bit of back and forth here. Feel free to set up 30 minutes on my calendar and I can give you an overview of how the extension works and its intended use.

**Comment by DanTup** [comment]
> I can think of a few ways to get this to work. I'm a little confused with your workflow though. What's the point of the extension if you are using VS code in this scenario? Presumably you have it running on your local machine and can just initiate debugging through it?

My goal here is just to allow debugging of a Flutter web app. This requires the web debugging proxy, and my understanding was that it required the Chrome extension (as a mechanism to drive the debugger in Chrome). It seems we're also getting DevTools. I thought (and hoped) these two things were separate. VS Code already has an integration with DevTools (which needs to stay, because it supports non-web apps), so all I really want is the proxy (the ability to connect the VS Code debugger to something that looks like the VM and let the user debug from VS Code).

> Nonetheless, getting the extension to play nice with VS Code isn't a high priority for us right now.

Understood. I thought running Flutter web apps from the IDEs (I think IntelliJ needs the same support) was a current goal. Nonetheless, it'd be good to know the direction this is heading in. Will the proxy be usable without DevTools?

**Comment by grouma** [comment]
> My goal here is just to allow debugging of a Flutter web app. 

That is a high priority goal for both internal and external users.

> This requires the web debugging proxy, and my understanding was that it required the Chrome extension.

Nope. The extension is only required when we don't launch Chrome with remote debugging enabled. The Flutter CLI launches Chrome by default so no need for the extension. I think it just needs to expose the proxy URL. There likely is work on our end though as we don't eagerly set one up.

>  so all I really want is the proxy

That's feasible and something we can look into doing.

> Will the proxy be usable without DevTools?

It is today. That's what I demoed with your custom extension and `webdev daemon`. I was able to set breakpoints and do general debugging through the proxy without using DevTools. 

Sounds like there are probably some action items for the webdev team so let's set up a quick 30 minute sync to get some clarity. I'm not familiar with your hours but feel free to set something up on my calendar.

**Comment by DanTup** [comment]
> Nope. The extension is only required when we don't launch Chrome with remote debugging enabled.

Whoops - sorry - this slipped my mind because I've also been working on something where we can't launch Chrome (this is still relevant, but in fewer places than I thought).

I'll ping you about setting up a meeting (I'm out next week, so may be best when I return).

**Comment by DanTup** [comment]
I had a quick go at "turning off" DevTools by commenting out some code here:

https://github.com/DanTup/webdev/commit/67df41303938a5732ae20a3f1516854c50ca5ae3

I also switched it from SSE to WebSockets (since it conveniently already had the code). Using this, I can run from VS Code without it spawning Chrome, and connect up the debugger (by opening the page and clicking the button for the Dart Debug extension).

I wasn't able to test stepping/breakpoints properly because of the path issues (they're fixed, but I had to use an older dwds to get this working).

This seems very promising - if the code commented out in the changeset above could be made optional (allowing us to pass a flag in), that would help a lot! Being able to use websockets as an option would be nice too (not just because it can be used before I add SSE support, but we could allow it to be overridden by users if they have issues).

**Comment by DanTup** [comment]
@grouma do you have any thoughts on the above? Does it seem reasonable to have an option that would essentially skip the code I commented out above?

**Comment by grouma** [comment]
I'm thinking this logic should be ignored when this is false: https://github.com/dart-lang/webdev/blob/ac450b77184d039439d8d4a9c5cc458176eadb84/dwds/lib/dwds.dart#L62

My one concern is that we won't know when to clean up the app services and therefore will likely leak memory.

**Comment by grouma** [comment]
> Can't we just make this part of the API that the client has to call? We're calling app.stop in Flutter, so Flutter could then call some cleanup code to tear down the debug proxy?

Yeah that would probably work. We can make a new extension like we did with screenshots:
https://github.com/dart-lang/webdev/blob/ac450b77184d039439d8d4a9c5cc458176eadb84/dwds/lib/src/dwds_vm_client.dart#L84

cc @jonahwilliams

**Comment by DanTup** [comment]
Sounds good. Is this something you're likely to have time to look at in the near future, or should I have a stab at it?

**Comment by grouma** [comment]
I can likely take a stab at this today.

**Comment by DanTup** [comment]
@grouma I don't suppose you got to this? It's less important than other dwds issues since it's only to support remote scenarios - but some of those scenarios are quite interesting :-)

**Comment by grouma** [comment]
It hasn't fallen through the cracks but it's unfortunately on my backlog.
