### ISSUE TITLE
WebSocketException: Connection to 'http://localhost:[...]/devtools/page/[...]#' was not upgraded to websocket

### ISSUE THREAD

**Issue by zanderso** [dart-lang/webdev#696]
From Flutter tool crash logging on an invocation with flags `--no-color run --machine --track-widget-creation --device-id=chrome lib\main.dart`

```
WebSocketException: WebSocketException: Connection to 'http://localhost:62678/devtools/page/2106B5DC2EE9DB2C3EAA7E7017C7FA42#' was not upgraded to websocket
  | at _WebSocketImpl.connect.<anonymous closure>.error | (websocket_impl.dart:1052 )
  | at _WebSocketImpl.connect.<anonymous closure> | (websocket_impl.dart:1061 )
  | at _rootRunUnary | (zone.dart:1132 )
  | at _CustomZone.runUnary | (zone.dart:1029 )
  | at _FutureListener.handleValue | (future_impl.dart:137 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:678 )
  | at Future._propagateToListeners | (future_impl.dart:707 )
  | at Future._completeWithValue | (future_impl.dart:522 )
  | at Future.wait.<anonymous closure> | (future.dart:400 )
  | at _rootRunUnary | (zone.dart:1132 )
  | at _CustomZone.runUnary | (zone.dart:1029 )
  | at _FutureListener.handleValue | (future_impl.dart:137 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:678 )
  | at Future._propagateToListeners | (future_impl.dart:707 )
  | at Future._completeWithValue | (future_impl.dart:522 )
  | at Future._asyncComplete.<anonymous closure> | (future_impl.dart:552 )
  | at _rootRun | (zone.dart:1124 )
  | at _CustomZone.run | (zone.dart:1021 )
  | at _CustomZone.runGuarded | (zone.dart:923 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:963 )
  | at _microtaskLoop | (schedule_microtask.dart:41 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:50 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:116 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:173 )
```

/cc @jakemac53 @jonahwilliams

**Comment by jakemac53** [comment]
This one might be something the flutter_tool should explicitly catch and try to handle on its own by giving some guidance to the user?

Possibly they can just try again or we can ask them to file an issue so we can help debug. If this is happening often enough we could develop an FAQ or something to point people at.

**Comment by zanderso** [comment]
@jonahwilliams wdyt?

**Comment by jonahwilliams** [comment]
Do you know at what we would expect this to be thrown? It looks like its during some devtools setup

**Comment by jakemac53** [comment]
This is almost certainly happening when we get an [incoming web socket connection](https://github.com/dart-lang/webdev/blob/b8b80d0d78b200709efa58b4cd23dc120a5c64b6/dwds/lib/src/services/debug_service.dart#L147) for the vm service. This `webSocketHandler` is coming from `shelf_web_socket` but I doubt it is at fault - I think this is simply a transient error when trying to upgrade the connection to a web socket connection.

This is likely surfacing as an unhandled async error to flutter tool - so it would have to be caught with a Zone. The code in the sdk that is throwing is [here](https://github.com/dart-lang/sdk/blob/98b286de216b7426fdefa0dabeafed48ebedecc2/sdk/lib/_http/websocket_impl.dart#L1061). It looks like a legitimate failure in response to a failed upgrade request.

It would maybe be nice for this message in the SDK to be more descriptive about why it failed, as there are several conditions here that could have triggered it.

**Comment by jakemac53** [comment]
Actually this looks like this might be happening from the flutter_tool end when it tries to connect to the vm service, and not inside our handler.

**Comment by jakemac53** [comment]
assigning jonah for now, feel free to re-assign as you see fit

**Comment by jonahwilliams** [comment]
I guess we can run the entire web tooling in a zone to handle this

**Comment by grouma** [comment]
@jonahwilliams is this issue still relevant?

**Comment by jonahwilliams** [comment]
It should be fixed now, though it would still be great if the exception was not thrown into the Zone uncaught exception handler
