### ISSUE TITLE
windows issues with the latest published dwds

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/webdev#709]
- Can't set breakpoints
- Pause works but can't resume

Angular repro instructions (may also repro with smaller apps but not sure):

```
pub global activate stagehand
pub global run stagehand web-angular
pub get
pub global activate webdev
pub global run webdev serve --debug
```

cc @jwren

**Comment by jakemac53** [comment]
I have confirmed I get the same behavior on the `fixtures/_test/hello_world` app as well.

**Comment by jwren** [comment]
cc @alexander-doroshko

**Comment by jakemac53** [comment]
note that pause/resume does appear to be working for me (at least on the hello world example) but I am not seeing any requests to set breakpoints coming in to dwds so that makes me think this is a devtools issue.

**Comment by jakemac53** [comment]
Related https://github.com/dart-lang/webdev/issues/711 and https://github.com/dart-lang/webdev/issues/710

**Comment by jakemac53** [comment]
This all looks fixed - I have confirmed I can set breakpoints etc now.
