### ISSUE TITLE
dart source not served when using https

### ISSUE THREAD

**Issue by biancashouse** [dart-lang/webdev#71]
In order to test with https, I use nginx to proxy from https://localhost:3000 -> http://localhost:8080.
If I test using http://localhost:8080, I can see main.dart in chrome's source tab.
If I test using https://localhost:3000, I only see main.dart.js !
The code server is serving up js but not the dart sources ?!

**Comment by jakemac53** [comment]
Going to close this as stale, please re-open or open a new issue if it is still a problem.

It sounds like this was an issue with the proxy server in this case though?
