### ISSUE TITLE
Support general Dart expression evaluation

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/webdev#715]
Support compiling and evaluating arbitrary Dart expressions in a REPL and in watch expressions.

The expectation is that we can do this through the CFE's compileExpression and having a command we can send to the persistent worker, with outlines already loaded, but this has to be verified. Watch expressions will also be more complicated because they need to be repeatedly evaluated in different contexts, where a variable might have a completely different type or be absent. So we may need something like the web_compiler of DDC that compiles entirely to dynamic calls.

**Comment by jakemac53** [comment]
This will have to work with the incremental compiler as well as we are exploring using that instead.

cc @jonahwilliams

**Comment by alan-knight** [comment]
I think that shouldn't be a problem. The poking at it I did so far was with IncrementalCompiler. We just need to be sure to get invalidation right when things change.

**Comment by grouma** [comment]
Related work: https://github.com/flutter/devtools/issues/714

**Comment by annagrin** [comment]
We added support for expression evaluation for all scenarios by default. Closing.
