### ISSUE TITLE
we'd like the ability to indicate which html file to open when Chrome launches

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#744]
Perhaps as something like a `--launch-url` flag? This would be in addition to the existing param specifying the directory to build.

**Comment by devoncarew** [comment]
We'd need support here for both `webdev serve` and `webdev daemon`.

**Comment by alexander-doroshko** [comment]
Not sure about the option name but the value would probably be the relative path from the served folder to the HTML file. E.g. `src/foo/bar/start.html` for file `/some/dart_root/web/src/foo/bar/start.html`.

**Comment by jakemac53** [comment]
I agree it should be relative to the directory being served - because it should correspond directly to what url we should launch in the browser.

That actually leads to another problem though - what if multiple directories are passed? You can for instance do `web:8080 test:8081` to serve both directories on different ports.

One possible remedy would be to require `--launch-url` to contain the full uri including the scheme/host/port - so for instance `http://localhost:8080/src/foo/bar/start.html`.

**Comment by jakemac53** [comment]
(we could also support this as a multi-argument so we would open up multiple tabs?)

**Comment by devoncarew** [comment]
Using the --launch-url arg might restrict the number of directories you can pass in to one? For an IDE launch, I think we're just going to have a single file (and app) to launch at a time.

**Comment by jakemac53** [comment]
From an IDE perspective that would likely be fine, but for `webdev serve` we would by default pass multiple directories so it becomes more complicated...

We could also potentially just have you pass the full package-relative path so `web/src/foo/bar/start.html` - we have enough information to know what host/port that is being served on and could map it to the full correct url.

**Comment by jakemac53** [comment]
Ok - I talked with @grouma  about this.

We settled on the following:

- Change the argument name to `--launch-app`
- This should provide full package relative paths
- We will convert that path to the correct url to launch based on the serve configuration for that directory
  - We will throw with an argument error if you aren't serving the top level directory of the app you asked to launch.

This works nicely with our default serving logic, it enables for instance `webdev serve --launch-app=web/sub/index.html --launch-app=test/my_test.html` to work out of the box. And it should work nicely with the daemon protocol as well.

**Comment by jakemac53** [comment]
So in investigating this I also noticed that the `daemon` command currently doesn't support any arguments. It appears it won't fail on trailing args (like `web:8080`) although it ignores them, and it will throw on any arg preceded with a `-` or `--`.

I can add support for some args though, and make it respect the trailing args although probably only a single top level dir.

**Comment by alexander-doroshko** [comment]
> I can add support for some args though, and make it respect the trailing args although probably only a single top level dir.

Great, thank you!
