### ISSUE TITLE
[dwds] Type arguments in "vars" collection have type of @Instance instead of @TypeArguments

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#760]
When getting the variables in a stack frame from the proxy, the type arguments have a type of `@Instance` but should be `@TypeArguments`:

https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#boundvariable

```js
{
	"jsonrpc": "2.0",
	"result": {
		"type": "Stack",
		"frames": [
			{
				"type": "Frame",
				"index": 0,
				"code": {
					"type": "@Code",
					"id": "476",
					"name": "genericMethod",
					"kind": "Dart"
				},
				"location": { /* ... */},
				"vars": [
					{
						"type": "BoundVariable",
						"name": "TBool",
						"value": {
							"type": "@Instance", // <--------------------
							"id": "{\"injectedScriptId\":1,\"id\":1363}",
							"kind": "Closure",
							"class": {
								"type": "@Class",
								"id": "477",
								"name": "Closure"
							},
```

In VS Code, we hide type arguments from the local variables window (because we have issues evaluating them to get useful display values) but these ones fall through.

**Comment by alan-knight** [comment]
This might be interesting. From a function we can call [_runtimeType].typeFormals() to find the type parameters. But in a frame we don't actually have a handle to the function, just a name and location. Doing a lookup based on that seems complicated and expensive. But I'm not sure at the moment what else we can do. Or we could go completely heuristic and assume that parameters at the beginning of the argument list whose name starts with a capital letter and whose value is a Class are type arguments.

**Comment by alan-knight** [comment]
It appears that the type parameters get passed in as JS classes, and that there are no other circumstances (except maybe JS Interop?) where we pass those. If you pass a class as a regular parameter what you get is a Dart Type. So that may be enough.
