### ISSUE TITLE
Flutter errors show paths starting org-dartlang-app in messages 

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#790]
This may be related to discussions we've had before about paths, but I think most of them were considered resolved.

Currently the errors shown to the user for Flutter web apps show `org-dartlang-app` in their messages (left), which looks a little strange (for non-web flutter, the full path is shown (right)):

![Screenshot 2019-10-29 at 1 40 10 pm](https://user-images.githubusercontent.com/1078012/67772477-08002400-fa52-11e9-8ae9-56eae814a305.png)

Is this expected/intended, or should this show a full file path like non-web?

**Comment by jakemac53** [comment]
This looks like a problem with the kernel transformer. It looks like it is grabbing the fully resolved absolute file uri instead of the uri that the file was actually compiled as. Neither of these are correct imo.

For this case the expected uri would be `package:hellow_world/broken.dart`.

**Comment by jakemac53** [comment]
cc @jacob314

**Comment by grouma** [comment]
@jakemac53 Does this issue belong in this repo?

**Comment by grouma** [comment]
Closing this issue as I believe all flutter web URLs are now package based. Please re-open if this is still a problem.
