### ISSUE TITLE
Dart Debug Extension continuously attempts failed SSE connect requests

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#794]
The underlying issue may actually be in `package:sse` but we need to investigate.

**Comment by DanTup** [comment]
I don't know if this is the same issue, but I just opened the Inspect window for the extension, and it's sat trying to connect to URLs that failed many many hours ago and I closed the windows for:

![Screenshot 2019-11-08 at 12 51 45 pm](https://user-images.githubusercontent.com/1078012/68477960-a0529180-0226-11ea-8331-ca9822e91cf2.png)

**Comment by grouma** [comment]
Yup. This is the same issue. I'll hopefully tackle this today.
