### ISSUE TITLE
Support relative URLs for debug extension service

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#805]
I don't know if this is simple, but I've hit an issue trying to get debugging working on GitPod. dwds requires the hostname/port of where the debug extension service is running in order to connect back (it's injected into the `$dartExtensionUri` variable).

On GitPod, we don't have good access to what the URL will be, as it looks like: `8080-some-big-long-guid.ws-eu01.gitpod.io` (at least, not in a way that doesn't involve writing very GitPod-specific code - and we'd likely need to do some equivalent for other similar services like VS Online).

I tried changing the URL in dwds to be relatvive (just `/$debug`), however that was resolved relative to the Chrome extension and not the page that was loaded.

Is it possible the debug extension could read the URL of the page and support relative URLs there? Although we'll eventually know the hostname/port, it won't be until after we're already running so we can't easily provide it. The workflow is something like:

- Run `flutter run`
- Wait for Flutter to give us back the URL of the app (which it will think is `localhost:xxx`)
- Call an API in VS Code/GitPod/etc. that asks for `localhost:xxxx` to be exposed to the user (this API will both set up a mapping/port forwarding, and then return the "public URL" that maps to it)
- Spawn URL in the browser

Even if we knew the hostname up-front, it seems like passing it to Flutter with `--web-hostname` will fail because then it tries to bind to that host (I don't know if this is Flutter or webdev code, but the hostname to listen to locally and the one the user will use will not match in these remote/online scenarios):

```
Launching lib/main.dart on Chrome in debug mode...
SocketException: Failed to create server socket (OS Error: Cannot assign requested address, errno = 99), address = 8080-b6896d6e-cf9e-42dd-ba84-5709097c4725.ws-eu01.gitpod.io, port = 0
```

**Comment by grouma** [comment]
I don't think a relative URL helps here. The application may reside behind a proxy so a relative request may not forward correctly (this is often the case for our internal users). For this reason, we embed the complete URL of the extension backend. However, I did _just_ add a feature for rewriting embedded URLs. See: https://github.com/dart-lang/webdev/pull/804

Exposing support of that somehow in the Flutter Tool should unblock you.

**Comment by DanTup** [comment]
> The application may reside behind a proxy so a relative request may not forward correctly

I was thinking that the URL would be resolved in the browser, so the hostname/port would essentially match what was in the address bar (I presume the debug service is always running on the same host/port as the app?).

> I did just add a feature for rewriting embedded URLs. See: #804

I think the issue will be that we're unlikely to be able to get at the hostname/port that will be used *before* we run Flutter (since it gets mapped by VS Online/GitPod once the process is running). We really need the whole app up and running, and then be able to expose it through a proxy at a hostname that we don't know in advance (which means nothing in the app would be able to rely on knowing the hostname up-front - even the Flutter process wouldn't know the hostname that's being used to expose to the user).

**Comment by grouma** [comment]
> I was thinking that the URL would be resolved in the browser, so the hostname/port would essentially match what was in the address bar (I presume the debug service is always running on the same host/port as the app?).

No the debug service always runs on a different a port. It should always be on the same hostname though.

> I think the issue will be that we're unlikely to be able to get at the hostname/port that will be used before we run Flutter (since it gets mapped by VS Online/GitPod once the process is running). We really need the whole app up and running, and then be able to expose it through a proxy at a hostname that we don't know in advance (which means nothing in the app would be able to rely on knowing the hostname up-front - even the Flutter process wouldn't know the hostname that's being used to expose to the user)

You could experiment with a URL encoder that simply converts all URLs to relative paths.

**Comment by DanTup** [comment]
> No the debug service always runs on a different a port.

Oh, I didn't spot that. In that case we're probably blocked until VS Code's new APIs for forward arbitrary ports without having to open them in browsers is available (and GitPod then gets the same).

I'll see if I can rig it temporarily to ensure the rest of it would work though. Thanks!
