### ISSUE TITLE
What is the webdev equivalent of -D option?

### ISSUE THREAD

**Issue by PhilipRoman** [dart-lang/webdev#81]
I recently upgraded from `pub` to `webdev` and noticed that there is no way to set a Dart environment variable (the ones you get using `new String.fromEnvironment("x")`) when running `webdev build` or `webdev serve`. What is the recommended alternative?

**Comment by PhilipRoman** [comment]
Nevermind, my searching did not hit the existing issue about this.

**Comment by zoechi** [comment]
Also did not for me. Do you remember where you found it?

**Comment by PhilipRoman** [comment]
#73

**Comment by zoechi** [comment]
@PhilipRoman  Thanks!
