### ISSUE TITLE
--live-reload doesn't work on macos

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/webdev#82]
It seems that editing the code while 

```dart
webdev serve --live-reload
```

is running doesn't refresh anything on macOS. 

What I did:

```sh
pub global activate stagehand
pub global activate webdev

stagehand web-angular
pub get
webdev serve --live-reload
```

Then tried to edit both `todo_list_component.dart` and `todo_list_component.html`.
A build has been triggered, but nothing happens until I refresh the page. 

tried both with dart 2.0.0 and 2.1.0-dev.2.0

____

alternatively, the build step after an editing can take 7+ seconds for a simple label edit.

**Comment by kevmoo** [comment]
CC @natebosch @jakemac53

**Comment by jakemac53** [comment]
You need to have build_web_compilers >=0.4.2 as well, can you confirm you have that?

**Comment by rrousselGit** [comment]
Confirmed. By looking into `.packages` I have 0.4.2+2 installed

**Comment by jakemac53** [comment]
@samogot can you take a look?

**Comment by natebosch** [comment]
It's working for me on mac following the same repro steps.

- Dart VM version: 2.1.0-dev.2.0 (Wed Aug 22 20:11:29 2018 +0200) on "macos_x64"
- stagehand version: 3.1.2
- webdev 0.2.4+1
- build_runner 0.10.1+1
- build_web_compilers 0.4.2+2

I can edit some text in todo_list_component.html and when a build finished my browser reloads.

**Comment by rrousselGit** [comment]
Oddly enough, doing it again worked this time.
There may have been a bug in one dependency that got fixed in the meantime. Because I did nothing more than just what was listed above.

I guess we can close it for now. I'll see if it happens again
