### ISSUE TITLE
dependencies issue. Because dweb depends on flutter_web any which doesn't exist

### ISSUE THREAD

**Issue by tianna1121** [dart-lang/webdev#820]
Hi, I am trying the latest version of webdev & flutter dev. When I run "flutter pub get" command, it shows "Because dweb depends on flutter_web any which doesn't exist (could not find package flutter_web at https://pub.dartlang.org), version solving failed."

I've already changed flutter dependency to flutter_web. If I use flutter as dependency, it shows: "pub get failed (1; Because dweb depends on flutter any which requires SDK version <2.0.0, version solving failed.)"

**Comment by natebosch** [comment]
I'm guessing your project is called `dweb`?

I don't think `flutter_web` is the dependency you want to use. When you depend on flutter, make sure you are using as an `sdk:` dependency. See, for instance, https://flutter.dev/docs/development/packages-and-plugins/using-packages#css-example

See https://flutter.dev/docs/get-started/web for the latest instructions on using flutter web.
