### ISSUE TITLE
Could not find web/index.html or any files in web.

### ISSUE THREAD

**Issue by Timmmm** [dart-lang/webdev#824]
I sometimes get this error:

    Could not find web/index.html or any files in web.

Even though I *definitely* have `web/index.html`. I have run `pub run build_runner clean`, but it seems there is some cached state that that doesn't fully clean.

I haven't been able to narrow down exactly what causes it. But I have been renaming the `web` directory and running `webdev` with a different directory like `webdev serve foo:8080`. That worked, then I renamed it back and now `webdev serve` doesn't work.

**Comment by Timmmm** [comment]
Observe:

```
$ ls web
favicon.png  index.html  main.dart  styles.css
$ webdev serve
[INFO] Reading cached asset graph completed, took 433ms
[INFO] Checking for updates since last build completed, took 1.3s
[INFO] Serving `web` on http://127.0.0.1:8080
[INFO] Running build completed, took 451ms
[INFO] Caching finalized dependency graph completed, took 318ms
[INFO] Succeeded after 780ms with 0 outputs (0 actions)
[INFO] --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
^Z
[1]+  Stopped                 webdev serve
$ bg
[1]+ webdev serve &
$ curl localhost:8080
Could not find web/index.html or any files in web.
```

**Comment by Timmmm** [comment]
I even deleted `.dart_tool`, re-ran `pub get` and it *still* can't find `web/index.html`. Infuriating!

**Comment by Timmmm** [comment]
Ok I finally realised, I had added a `build.yaml` containing this:

```
targets:
  $default:
    sources:
      - "node/**"
      - "test/**"
```

Once I removed it, it worked. So the problem is that the error message should be:

    Could not find node/index.html or any files in node.

**Comment by Timmmm** [comment]
Ah or is it that it *is* looking in `web`, but only for files that are listed in `sources`? In which case the error should be:

    Could not find web/index.html or any files in web. If you are using build.yaml make sure the files are listed as sources.

**Comment by natebosch** [comment]
The only files that get involved in the build must be sources - I'm not sure we'll be able to find _every_ possible place where a misconfigured target can cause and error, but I suppose we could update this one.

**Comment by Timmmm** [comment]
This is much better, thanks! I'm sure it will save people time, and it's little touches like this that make a platform really nice to use.
