### ISSUE TITLE
Sample StageXL web app hangs instead of stopping on a breakpoint

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/webdev#836]
Dart SDK 2.7, stagehand 3.3.4, webdev 2.5.4 (activated today), Chrome 78.0.3904.108.
I tried with Ubuntu 18.04 and Windows 10 - both have the bug, probably the same issue on Mac.

Steps:

- pub global activate stagehand
- pub global run stagehand web-stagexl
- pub get
- pub global activate webdev
- pub global run webdev daemon

Chrome opens, Dart app runs, animation on click works fine. So far so good.

- open DevTools (Alt+D)
- set a breakpoint inside a mouse listener (e.g. on line 43 with code `if (rotation != null) return;`
- go back to the dart web app tab and click the logo once again.

Expected: the app suspends on a breakpoint, DevTools show vars, stack, Resume button enabled .

Actual: the app hangs, nothing changes on the DevTools tab. No way to resume the app.

**Comment by alexander-doroshko** [comment]
The issue is still valid. Cc @grouma

**Comment by grouma** [comment]
Got a stack trace:

```
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'int' in type cast
#0      new ClassMetaData (package:dwds/src/debugging/metadata.dart:36:36)
#1      ClassMetaData.metaDataFor (package:dwds/src/debugging/metadata.dart:69:14)
<asynchronous suspension>
#2      InstanceHelper._instanceRefForRemote (package:dwds/src/debugging/instance.dart:346:44)
#3      InstanceHelper.instanceRefFor (package:dwds/src/debugging/instance.dart:303:12)
#4      Debugger._boundVariable (package:dwds/src/debugging/debugger.dart:363:42)
#5      Debugger.variablesFor.<anonymous closure> (package:dwds/src/debugging/debugger.dart:351:50)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#7      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#8      Future.wait (dart:async/future.dart:393:26)
#9      Debugger.variablesFor (package:dwds/src/debugging/debugger.dart:350:39)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
```

I should have a fix shortly.
