### ISSUE TITLE
Add a --version flag

### ISSUE THREAD

**Issue by natebosch** [dart-lang/webdev#84]

**Comment by kevmoo** [comment]
this is a job for source_gen!

This is a common-enough pattern, I wonder if we should ship a package for it.

- [ ] https://github.com/dart-lang/dart_style/blob/6f3efd209ff1828835936397b64be79265cc0c19/bin/format.dart#L18
- [ ] https://github.com/dart-lang/dartdoc/blob/13e8396ed1c25312fbb783d56b10066b58b6ac06/lib/dartdoc.dart#L40
- [ ] https://github.com/dart-lang/pana/blob/c8bc1e65f0717793e7c5a6de3f91430b92ed7788/lib/src/version.g.dart#L9
   - actually uses a builder
