### ISSUE TITLE
Restore dwds/ensure_build_test.dart

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/webdev#840]
I removed this because I couldn't get it to do only the version.dart file, but we should get it fixed and put back.

**Comment by jakemac53** [comment]
Note that this file is already out of date - we definitely need to restore this test asap or the version file will not be correctly updated (based on past experience nobody will remember to do this).

**Comment by jakemac53** [comment]
I don't know if it matters or not that we published dwds `0.8.1` with the wrong version field? @alan-knight @grouma

**Comment by grouma** [comment]
Oh fun. This shouldn't be an issue though. The intent behind this logic is to allow for graceful breaking changes in the debug extension.

**Comment by alan-knight** [comment]
It shouldn't matter, because the thing that depends on the version field isn't landed yet.
