### ISSUE TITLE
Support binding debug extension service to network IPs

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#845]
When running on GitPod we can only expose ports that are bound to the network IP (unless we know the port number up-front before the container is created). The hostname Flutter passes in to this code is `localhost` which is correct for the URLs, but not for the binding, so I had to do this:

https://github.com/DanTup/webdev/commit/3ed7a3d8a73bf8e9cfb65a015797293f1cdfb3ef

I'm happy to send a PR, but I'm not sure where would be best to handle this (and whether it should be behind a flag/option or is reasonable to always do)?

@grouma

**Comment by DanTup** [comment]
@grouma Do you have any thoughts on this? You mentioned using `package:http_multi_server` but that's already being used inside `ExtensionBackend.start`. We need to give it the string `any` instead of `localhost` for it to bind to non-loopback IPs (however the other code building the URL into `extensionUri` needs to return `localhost` since `http://any` won't work).

**Comment by grouma** [comment]
I took a look at this today. I have a better understanding what's going on now. I don't think it makes sense to do the change you suggested. Flutter should really be passing `any` as the hostname as that aligns with the intended behavior. I think we should special case `any` when we provide the`extensionUri`. Feel free to send a PR my way.

**Comment by DanTup** [comment]
> Flutter should really be passing `any` as the hostname as that aligns with the intended behavior. I think we should special case any when we provide the `extensionUri`.

Got it - that sounds like it should work (and addresses the question about whether it should be opt-in). I'll try it out to ensure the "any" doesn't end up anywhere else it shouldn't and open a PR. Thanks!

**Comment by DanTup** [comment]
Ok, to avoid doing magic based on the string `any` we could do this:

```
extensionBackend = await ExtensionBackend.start(hostname);
extensionUri = Uri(
        scheme: 'http',
        host: extensionBackend.hostname, // <-- read hostname from extensionBackend
        port: extensionBackend.port,
        path: r'$debug')
    .toString();
```

However this has a side-effect of returning `127.0.0.1` or `::1` when you pass `localhost` (as well as `any`). This appears to already be the case for the DevTools URL that's generated, since it essentially does the same:

```
final server = await HttpMultiServer.bind(hostname, port);
shelf.serveRequests(server, handler);
final devToolsUrl = 'http://${server.address.host}:${server.port}';
```

I'll test it works for what I need and open a PR, but if this isn't acceptable here then we'd need to special case it, something like:

```
ionBackend = await ExtensionBackend.start(hostname);
extensionUri = Uri(
        scheme: 'http',
        host: hostname == 'any' ? 'localhost' : hostname,
        port: extensionBackend.port,
        path: r'$debug')
    .toString();
```

But I don't know if it's weird to be start to replicating the HTTP server's "any" behaviour in webdev.

**Comment by DanTup** [comment]
Ugh, doing that revealed some other issues because on GitPod we get the IPv6 loopback and that doesn't get mapped correctly to the public host.

I've raised an issue with GitPod about that (VS Online appears not to support IPv6, that wouldn't happen there), though I'll hold off opening a PR until I have your opinion on the above (mainly whether you want `any` to be fully supported as a hostname, what's acceptable to return in the outbound URLs when that's used, and whether it's acceptable to get `127.0.0.1` or `::1` back when passing `localhost` in).

**Comment by grouma** [comment]
The first approach:

```
extensionBackend = await ExtensionBackend.start(hostname);
extensionUri = Uri(
        scheme: 'http',
        host: extensionBackend.hostname, // <-- read hostname from extensionBackend
        port: extensionBackend.port,
        path: r'$debug')
    .toString();
```

Seems to be the proper thing to do.

**Comment by DanTup** [comment]
@grouma that's what I tried - but passing `localhost` into `ExtensionBackend.start` then results in `extensionUri` being `127.0.0.1` (or `::1`) whereas today it would always be `localhost` - this seems to be HttpMultiServer behaviour. Is that a reasonable change to you (and won't break anyone)?

**Comment by grouma** [comment]
I don't anticipate any issues.
