### ISSUE TITLE
Do not live reload if build fails

### ISSUE THREAD

**Issue by grundid** [dart-lang/webdev#86]
Live reload works great, but once the build fails it won't work even if you fix the build. 

Once solution would be not to reload if the build failed or serve a static page if the build failed that would still keep the connection between the build system and the browser.

**Comment by samogot** [comment]
Try to update to the latest `build_runner` (0.10.2). It should be fixed there, together with adding hot-reload mode

**Comment by grundid** [comment]
Thx. Haven't tested hot-reload yet, but live-reload now works perfectly.
