### ISSUE TITLE
argument for disable browser CORS policy

### ISSUE THREAD

**Issue by amreniouinnovent** [dart-lang/webdev#862]
I wonder if we could get an argument for disabling CORS Policy for debugging purposes until the backend developer whitelisted the domain and the port?

When I started to test my Android app if it will work on Flutter web or not I got the CORS issue.
I think it would be nice for first-time developers trying the mobile code to work on the web so maybe disable CORS would help to investigate the web-behavior.

```
{
	"name": "Flutter",
	"request": "launch",
	"type": "dart",
	"args": ["--no-cors", "true"]
}
```

My proposal rejected in Flutter but I hope it to get accepted here
https://github.com/flutter/flutter/issues/46904

**Comment by wytrych** [comment]
That would be great! We are currently running a proxy server in front of the webdev to be able to test our app locally (we have a Java backend and a Dart frontend and we can't load it with CORS).

**Comment by amreniouinnovent** [comment]
@wytrych Run the chrome while disabling CORS by https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

What is the frontend dart framework you are using ? is it Angular Dart?

**Comment by wytrych** [comment]
We're just using vanilla dart, home-built framework. Yeah I know about disabling CORS in chrome, but you can't do that in Safari which we need to support as well.

**Comment by wytrych** [comment]
Well actually seems like Safari does have "Disable CORS" in the Develop menu...

**Comment by btphan95** [comment]
It's frustrating having to disable CORS on Chrome every. single. time.

**Comment by grouma** [comment]
This issue isn't relevant to this repro. We no longer build Flutter Web applications with `package:webdev`.

**Comment by Sunbreak** [comment]
> This issue isn't relevant to this repro. We no longer build Flutter Web applications with `package:webdev`.

What about AngularDart?
