### ISSUE TITLE
Best way to do cache busting (content hashes)?

### ISSUE THREAD

**Issue by matanui159** [dart-lang/webdev#888]
Can't find this documented or asked about anywhere and not sure which repo to ask in so I'm asking here.

What is the recommended way to do cache-busting (eg. by renaming the output js files to the hash of the output) in Dart web? If there is a recommended way should it be documented somewhere?

**Comment by jakemac53** [comment]
There isn't any "official" guidance here - but I do have a small non-official package [built_html](https://pub.dev/packages/built_html) which can do this.

**Comment by matanui159** [comment]
However, this doesn't do cache busting on deferred chunks

**Comment by jakemac53** [comment]
Correct there is no cache busting uri strategy for that which I am aware of. You need to instead do must-revalidate and etags

**Comment by matanui159** [comment]
Thats sometimes not possible due to where you're hosting your content (eg. itch.io uploads)

**Comment by matanui159** [comment]
It's also not possible via post-process build steps due to deferred chunks being created in the same stage. The only way I've found for it to be potentially possible (although I have not tested it) is to create your own build CLI that runs the usual build and then goes through and renames all the `js` files and updates any references to them in other `js` or `html` files (as a sort of post, post build step).

But shouldn't something like this which is usually quite important be easier to do?

**Comment by matanui159** [comment]
The best way would be a option to `build_web_compilers` if possible, or possibly as a post, post build step as I suggested but built into `webdev`. I have done a bit of a code dive and will look further into the code this arvo.

For now can this issue be reopened?

**Comment by matanui159** [comment]
After more code dives I find this very difficult to achieve with the way the build is setup right now. The best way I can see this working is as something `webdev` does after using `build_runner` but with the extra options and overall "hacky" feeling of it (IMO) it would probably be better to leave that to an external tool that calls `webdev` or `build_runner`.

I will close this for now
