### ISSUE TITLE
Reuse scope filter logic with evaluation support

### ISSUE THREAD

**Issue by grouma** [dart-lang/webdev#909]
We recently provided custom scope filter logic while showing the variables at a paused breakpoint. See:
https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/debugging/dart_scope.dart

We should reuse the above logic here:
https://github.com/dart-lang/webdev/blob/ec1ae51f5079bc9b948ab2cbef8ccbd4a7edf771/dwds/lib/src/services/expression_evaluator.dart#L208

**Comment by annagrin** [comment]
this is fixed in https://github.com/dart-lang/webdev/commit/abda1c391bdbd3e79d68fac1e4ed00cf3df1b19e#
