### ISSUE TITLE
webdev could not run for this project.

### ISSUE THREAD

**Issue by guzths** [dart-lang/webdev#92]
Error Message
```
λ webdev serve
webdev could not run for this project.
Could not find a file named "pubspec.yaml" in "C:\Users\username\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\protobuf-0.10.4".
```

Installation went fine:
```
λ pub global activate webdev
Package webdev is currently active at version 1.0.0.
Resolving dependencies...
+ args 1.5.0
+ charcode 1.1.2
+ collection 1.14.11
+ io 0.3.3
+ meta 1.1.6
+ path 1.6.2
+ pub_semver 1.4.2
+ source_span 1.4.1
+ stack_trace 1.9.3
+ string_scanner 1.0.4
+ webdev 1.0.0
+ yaml 2.1.15
Downloading webdev 1.0.0...
Downloading stack_trace 1.9.3...
Downloading io 0.3.3...
Downloading yaml 2.1.15...
Downloading meta 1.1.6...
Downloading charcode 1.1.2...
Downloading path 1.6.2...
Downloading string_scanner 1.0.4...
Downloading source_span 1.4.1...
Downloading args 1.5.0...
Downloading pub_semver 1.4.2...
Downloading collection 1.14.11...
Precompiling executables...
Precompiled webdev:bin\webdev.
Installed executable webdev.
Activated webdev 1.0.0.
```

If I install protobuf globally with `pub global activate protobuf` then it stops with this error but goes to the next package it can't find. I've tried to manually install 3 packages but gave up because it could be hundreds of packages.

Using windows 10 with cmder. Dart SDK installed from gekorm (which is working just fine)

**Comment by kevmoo** [comment]
In which directory are you running `webdev serve`? It looks like you're running it within `C:\Users\username\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\protobuf-0.10.4` – which is a bit weird...

**Comment by guzths** [comment]
I just saw that I had an "ios" and an "android" folder on my web project. It looks like I had some flutter stuff commented out on pubspec.yaml, probably thought it won't cause any problem but it did. As soon as I remove the folders and removed that code completely, webdev just works.

@kevmoo Thanks for the fast response. It was my fault for trying stuff in a hurry, sorry about that.

**Comment by dbacinski** [comment]
I have the same issue after fetching clean project. There is a workaround to it: https://github.com/flutter/flutter/issues/32313#issuecomment-490523545
