### ISSUE TITLE
Exception using DevTools with dwds version of Flutter SDK 

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/webdev#926]
I am using an unmerged branch of the Flutter SDK to experiment with package:dwds in flutter: https://github.com/flutter/flutter/pull/51004. VSCode and IntelliJ debugging are working as expected, but the DevTools throws an exception.

## Steps to Reproduce
1. check out this version of the Flutter SDK: https://github.com/flutter/flutter/pull/51004
2. [Install DevTools](https://flutter.dev/docs/development/tools/devtools/cli)
3. run `flutter pub global run devtools ` in one shell
4. run `flutter run -d chrome` in another shell
5. open DevTools and paste websocket url
6. set a breakpoint in a Flutter app.
7. Hot restart
8. Observe the hot restart button is disabled. Open Chrome DevTools in the DevTools tab to see the exception

## Stack Trace
```
main.dart.js:10935 TypeError: Cannot read property 'get$id' of null
    at DebuggerState._debugger_state$_handleIsolateEvent$1 (main.dart.js:36659)
```

```
main.dart.js:10925 DevTools exception: [RPCError] WipError 39: {code: -32000, message: Invalid remote object id}
main.dart.js:10928 #0      AppInspector.jsCallFunctionOn (package:dwds/src/debugging/inspector.dart:190:9)
<asynchronous suspension>
#1      ClassMetaData.metaDataFor (package:dwds/src/debugging/metadata.dart:66:36)
#2      InstanceHelper.instanceFor (package:dwds/src/debugging/instance.dart:91:40)
#3      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:320:41)
<asynchronous suspension>
#4      ChromeProxyService.getObject (package:dwds/src/services/chrome_proxy_service.dart:389:19)
#5      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1253:51)
```

[stack_trace.txt](https://github.com/dart-lang/webdev/files/4344668/stack_trace.txt)

**Comment by grouma** [comment]
We've included a ton of fixes in the last couple of releases. I recall fixing a very related issue. I tried to reproduce this issue with version `3.1.2` of `package:dwds` and I'm unable to do so.

cc @jonahwilliams
