### ISSUE TITLE
webdev (2.5.6) serve (dartdevc) compilation fails with 2.8.0-dev.15.0

### ISSUE THREAD

**Issue by whesse** [dart-lang/webdev#936]
The non-release, dartdevc build of my Dart Angular web app is failing with dev SDK releases 2.8.0-dev.15.0 and 2.8.0-dev.16.0.  It is working with 2.8.0-dev.10.0, and probably most of the ones between dev.10 and dev.15, I'll narrow it down more.  Webdev is 2.5.6

I'm unclear whether this is a webdev problem or a dartdevc problem, or specific to the interface between the two.  The error I see is "Bad state: Process is detached" when it tries to run the ddc compiler.

I'll look into debugging this, running in verbose modes, and pinning down the version where the problem begins.  The problem can be reproduced by checking out the dart-lang/dart_ci repository and trying to build with the command:

pub global run webdev serve web:53322 --no-release -v

The stack trace shows a failure in bazel_worker, but it looks like the process it started got detached, not a bug in the bazel_worker code.  Because public angular has not been updated in a year, it had some conflicting old dependencies, so I also tried updating them, but got the same result. My overrides (which made no difference to the failure) are:
dependency_overrides:
  bazel_worker: '0.1.23'
  protobuf: '>=0.14.4'

[INFO]Heartbeat: 28.4s elapsed, 4080/4090 actions completed.
[FINE]angular:angular on package:angular_test/compatibility.dart: Running AngularDart Compiler
[SEVERE]build_web_compilers:ddc on package:intl/date_symbols.ddc.module: Bad state: Process is detached
#0      _ProcessImpl.exitCode (dart:io-patch/process_patch.dart:546:29)
#1      BazelWorkerDriver._runWorkQueue.<anonymous closure> (package:bazel_worker/src/driver/driver.dart:116:16)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl

**Comment by jakemac53** [comment]
You will need to update your `bazel_worker` version to the latest, there was a breaking change in the sdk which broke that package.

**Comment by jakemac53** [comment]
(specifically, you need version `0.1.23+1`)

**Comment by whesse** [comment]
This seems to be an unfixable breakage in the angular workflow now, because if I use bazel_worker 0.1.23+1, then I need to use protobuf 0.14.4, and angular framework code breaks with protobuf 0.14.4.

I will file an issue against Dart angular about this.
The workaround is to use dart2js by adding the --release flag to webdev serve.

**Comment by jakemac53** [comment]
Oh right! cc @kevmoo @vsmenon this is what I was talking about a few weeks ago

**Comment by natebosch** [comment]
Side note - when pasting stack traces in github issues please surround them with code fences.
