### ISSUE TITLE
Bad state: No element from package:dwds when hot reloading in a flutter web app

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#947]
I saw this on flutter master today; this was after several reloads in the same app (the Flutter web version of Devtools).

```
Unexpected Server Error Bad state: No element
  #0 List.first (dart:core-patch/growable_array.dart:219:5)
  #1 _disableBreakpointsAndResume (package:dwds/src/dwds_vm_client.dart:112:32)  
  #2 DwdsVmClient.create.  (package:dwds/src/dwds_vm_client.dart:57:13)
  #3 VmService._routeRequest (package:vm_service/src/vm_service.dart:2058:39)
  #4 VmService._processRequest (package:vm_service/src/vm_service.dart:2035:25)
  #5 VmService._processMessageStr (package:vm_service/src/vm_service.dart:2001:9)
  #6 VmService._processMessage (package:vm_service/src/vm_service.dart:1958:7)
  #7 _rootRunUnary (dart:async/zone.dart:1192:38)
  #8 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
  #9 _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
  #10 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
  #11 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
  #12 _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
  #13 _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
  #14 _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
  #15 _rootRunUnary (dart:async/zone.dart:1192:38)
  #16 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
  #17 _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
```

**Comment by jakemac53** [comment]
It looks like a hot restart happened while there was no app actually connected (there were no `isolates` on the vm object).

@grouma we should likely at least add a try/catch in this handler https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/dwds_vm_client.dart#L57

**Comment by jakemac53** [comment]
Or possibly `client.registerServiceCallback` should always do this and return an error response if the callback throws?

**Comment by jakemac53** [comment]
Oh - it looks like this message was actually from a an rpc error response https://github.com/dart-lang/sdk/blob/master/pkg/vm_service/lib/src/vm_service.dart#L2092.

So we may not want to do anything here unless it actually crashed webdev for something.

**Comment by devoncarew** [comment]
I still was connected to the app, and it was still running, it's just that this exception was thrown when I did a hot restart.

Perhaps _disableBreakpointsAndResume() needs to be tolerate when there are no isolates currently known? Or, perhaps there's a race condition in discovering isolates?

**Comment by grouma** [comment]
I think we just need to validate that the isolate isn't null here:
https://github.com/dart-lang/webdev/blob/cbccfaf6e7194c7683266aa0adafe14daf58e3f8/dwds/lib/src/dwds_vm_client.dart#L112

@devoncarew is there an easy repro I can test with?

**Comment by devoncarew** [comment]
> @devoncarew is there an easy repro I can test with?

Unfortunately, no - I've just seen this the once. Likely a long tail issue, but I wanted to report it esp. given that issues w/ stack traces are more actionable -

**Comment by grouma** [comment]
I'll add some safety checks nonetheless and hopefully it will resolve itself.

**Comment by grouma** [comment]
I was thinking something like this: https://github.com/dart-lang/webdev/pull/948

**Comment by devoncarew** [comment]
FYI, I've started seeing this several times an hour.

<img width="633" alt="Screen Shot 2020-04-11 at 4 53 39 PM" src="https://user-images.githubusercontent.com/1269969/79057322-23807500-7c15-11ea-8970-2b8438e269f9.png">

I have to terminate Chrome and re-run the app to work around this. If a version of package:dwds w/ this fix hasn't yet been rolled into flutter, it's worth doing.

**Comment by grouma** [comment]
We can be more defensive in this section of code but I'm curious to know why we are sending a hotRestart request without an active isolate. My understanding is that Flutter Tools waits for a successful hot reload before attempting to do another. I'm also curious why we don't see the new state error here: https://github.com/dart-lang/webdev/pull/948

**Comment by mordivgor** [comment]
I face the same issue.
For the easier reproduction - I realized that is more probable if we are waiting some more time (couple of minutes) between hot restarts. If they are being done quite often, then such thing does not appear.
