### ISSUE TITLE
Daemon doesn't quit when sent SIGINT/SIGTERM

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#950]
If I run a project with `pub global run webdev serve` and hit Ctrl+C (in my macOS terminal), it quits fine. However if I do the same for `pub global run webdev daemon`, it doesn't quit. I think this worked in the past, as it's causing some of Dart-Code's integration tests to fail.

```
pub global run webdev daemon
[{"event":"daemon.connected","params":{"version":"0.4.2","pid":18408}}]
[{"event":"daemon.log","params":{"log":"[INFO] Connecting to the build daemon..."}}]
[{"event":"daemon.log","params":{"log":"[INFO] Generating build script..."}}]
[{"event":"daemon.log","params":{"log":"[INFO] Generating build script completed, took 280ms"}}]
[{"event":"daemon.log","params":{"log":"[INFO] "}}]
[{"event":"daemon.log","params":{"log":"[INFO] Starting daemon..."}}]
[{"event":"daemon.log","params":{"log":"[INFO] Initializing inputs"}}]
// Trim boring stuff
```

Then I hit Ctrl+C and see:

```
^C[{"event":"app.log","params":{"appId":"Zx8LtUMQv8Vik6vK2PDePw==","log":"Lost connection to device."}}]
[{"event":"app.stop","params":{"appId":"Zx8LtUMQv8Vik6vK2PDePw=="}}]
[{"event":"daemon.log","params":{"log":"[INFO] Stopped debug service on ws://127.0.0.1:59201\n"}}]
```

However, it then continues to sit there and does not terminate (it does close the browser window though).

The app I'm testing with is here:

https://github.com/Dart-Code/Dart-Code/tree/master/src/test/test_projects/web/hello_world

I'm using a globally activated v2.5.6 of webdev.

**Comment by jakemac53** [comment]
this might be related to some of the SSE stuff if we still have a connection open

**Comment by DanTup** [comment]
Yeah, removing keepAlive seems to stop this. I'll see if I can find a fix!

**Comment by DanTup** [comment]
I've opened a PR in SSE that I think will address this:

https://github.com/dart-lang/sse/pull/27

It exposes a `shutdown()` method on the `SseHandler` that can be called from the shutdown code here, to ensure all connections are closed (ignoring their `keepAlives`).

**Comment by DanTup** [comment]
Using the code in that PR, this is the change I believe should be made here to call it:

<img width="740" alt="Screenshot 2020-04-15 at 17 19 28" src="https://user-images.githubusercontent.com/1078012/79361502-483e5a80-7f3d-11ea-85b1-8d8d0856a8a0.png">

I'm not sure whether the code I've removed/commented here can be completely replaced though (and whether the comment should be kept/how it should be updated).

**Comment by DanTup** [comment]
@grouma oops, my bad comment in that other PR caused this to close, but we still need changes here to call shutdown.

**Comment by grouma** [comment]
Feel free to send a PR and I'll reopen.
