### ISSUE TITLE
Add support for build_runner's "watch" mode

### ISSUE THREAD

**Issue by jay9909** [dart-lang/webdev#96]
When working with separate front- and back-end development environments, it would be helpful to support a "watch" feature like build_runner used to that would watch the source for changes and re-compile when a source file is updated, but did not serve the app itself.

For example, I use Go App Engine and thus use their development server for back-end work.  build_runner used to let me have the auto-rebuild features with an --output path that would dump the compiled front-end into the appropriate GAE dev_appserver directory.  webdev has the watch/rebuild built into the "serve" command but no way to disable actually serving the app.

**Comment by kevmoo** [comment]
FYI: we only add features to `webdev` (now) that are required to enable IDE support.

Unless you want something beyond what you get with `pub run build_runner watch`, I'm going to close this out.
