### ISSUE TITLE
some type failures in tests not failing the CI

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#985]
There are some type issues when running the tests:

```
Failed to handle API message from client:
{"id":0,"method":"connected","params":{"uri":"ws://127.0.0.1:32813/so4YV_Awchk=/ws"}}
type 'int' is not a subtype of type 'String'
```

https://travis-ci.org/github/dart-lang/webdev/jobs/682770764

These don't fail the CI, but are worth looking into.

**Comment by jakemac53** [comment]
ah looks like we are expecting the ID as a string or something here, cc @grouma

**Comment by jakemac53** [comment]
We should also see if we can figure out why this wasn't failing CI, as it most likely should have been.

**Comment by devoncarew** [comment]
Yeah, I wasn't sure if this was coming from package:wip, package:vm_service, or elsewhere.

**Comment by grouma** [comment]
This looks like it's actually coming from Dart DevTools:
https://github.com/flutter/devtools/blob/7d536114b3ebc59e996d7c673602544fedf5701c/packages/devtools_server/lib/src/client_manager.dart#L110

There isn't really anything we can do in `package:dwds`. Transferring issue over.

**Comment by grouma** [comment]
Hmm. Since https://github.com/flutter/devtools is under /flutter I can't transfer over. I'll close this in favor of: https://github.com/flutter/devtools/issues/1905
